const description =
  "Nova Scotia has 49 municipalities - 4 regional municipalities, 25 towns, 9 county municipalities and 11 district municipalities that cover 99.8% of the territory's land mass.";

// ['name', 'status', 'county'],
const municipalities = [
  ["Cape Breton", "regional municipality", "Capte Breton"],
  ["Halifax", "regional municipality", "Halifax"],
  ["Queens", "regional municipality", "Queens"],
  ["West Hants", "regional municipality", "Hants"],
  ["Annapolis", "county municipality", "Annapolis"],
  ["Antigonish", "county municipality", "Antigonish"],
  ["Colchester", "county municipality", "Colchester"],
  ["Cumberland", "county municipality", "Cumberland"],
  ["Inverness", "county municipality", "Inverness"],
  ["Kings", "county municipality", "Kings"],
  ["Pictou", "county municipality", "Pictou"],
  ["Richmond", "county municipality", "Richmond"],
  ["Victoria", "county municipality", "Victoria"],
  ["Argyle", "district municipality", "Yarmouth"],
  ["Barrington", "district municipality", "Shelburne"],
  ["Chester", "district municipality", "Lunenburg"],
  ["Clare", "district municipality", "Digby"],
  ["Digby", "district municipality", "Digby"],
  ["East Hants", "district municipality", "Hants"],
  ["Guysborough", "district municipality", "Guysborough"],
  ["Lunenburg", "district municipality", "Lunenburg"],
  ["Shelburne", "district municipality", "Shelburne"],
  ["St. Mary's", "district municipality", "Guysborough"],
  ["Yarmouth", "district municipality", "Yarmouth"],
  ["Amherst", "town", "Cumberland"],
  ["Anapolis Royal", "town", "Annapolis"],
  ["Antigonish", "town", "Antigonish"],
  ["Berwick", "town", "Kings"],
  ["Bridgewater", "town", "Lunenburg"],
  ["Clark's Harbour", "town", "Shelburne"],
  ["Digby", "town", "Digby"],
  ["Kentville", "town", "Kings"],
  ["Lockeport", "town", "Shelburne"],
  ["Lunenburg", "town", "Lunenburg"],
  ["Mahone Bay", "town", "Lunenburg"],
  ["Middleton", "town", "Annapolis"],
  ["Mulgrave", "town", "Guysborough"],
  ["New Glasgow", "town", "Pictou"],
  ["Oxford", "town", "Cumberland"],
  ["Pictou", "town", "Pictou"],
  ["Port Hawkesbury", "town", "Inverness"],
  ["Shelburne", "town", "Shelburne"],
  ["Stellarton", "town", "Pictou"],
  ["Stewiacke", "town", "Colchester"],
  ["Trenton", "town", "Pictou"],
  ["Truro", "town", "Colchester"],
  ["Westville", "town", "Pictou"],
  ["Wolfville", "town", "Kings"],
  ["Yarmouth", "town", "Yarmouth"],
];

export { description, municipalities };
