const description =
  "New Foundland and Labrador has 274 municipalities that cover 2.3% of the province's land mass. Of 274 municipalities, 3 are cities, 266 are towns and 5 are Inuit community governments.";

// ['name', 'status']
const municipalities = [
  ["Corner Brook", "city"],
  ["Mount Pearl", "city"],
  ["St. John's", "city"],
  ["Admirals Beach", "town"],
  ["Anchor Point", "town"],
  ["Appleton", "town"],
  ["Aquaforte", "town"],
  ["Arnold's Cove", "town"],
  ["Avondale", "town"],
  ["Badger", "town"],
  ["Baie Verte", "town"],
  ["Baine Harbour", "town"],
  ["Bauline", "town"],
  ["Bay Bulls", "town"],
  ["Bay de Verde", "town"],
  ["Bay L'Argent", "town"],
  ["Bay Roberts", "town"],
  ["Baytona", "town"],
  ["Beachside", "town"],
  ["Bellburns", "town"],
  ["Belleoram", "town"],
  ["Birchy Bay", "town"],
  ["Bird Cove", "town"],
  ["Bishop's Falls", "town"],
  ["Bonavista", "town"],
  ["Botwood", "town"],
  ["Branch", "town"],
  ["Brent's Cove", "town"],
  ["Brighton", "town"],
  ["Brigus", "town"],
  ["Bryant's Cove"],
  ["Buchans", "town"],
  ["Burgeo", "town"],
  ["Buin", "town"],
  ["Burlington", "town"],
  ["Burnt Islands", "town"],
  ["Campbellton", "town"],
  ["Cape Broyle", "town"],
  ["Cape St. George", "town"],
  ["Carbonear", "town"],
  ["Carmanville", "town"],
  ["Cartwright, Labrador", "town"],
  ["Centreville-Wareham-Trinity", "town"],
  ["Chance Cove", "town"],
  ["Change Islands", "town"],
  ["Channel-Port aux Basques"],
  ["Chapel Arm", "town"],
  ["Charlottetown", "town"],
  ["Clarenville", "town"],
  ["Clarke's Beach", "town"],
  ["Coachman's Cove", "town"],
  ["Colinet", "town"],
  ["Colliers", "town"],
  ["Come By Chance", "town"],
  ["Comfort Cove-Newstead", "town"],
  ["Conception Bay South", "town"],
  ["Conception Harbour", "town"],
  ["Conche", "town"],
  ["Cook's Harbour", "town"],
  ["Cormack", "town"],
  ["Cottlesville", "town"],
  ["Cow Head", "town"],
  ["Cox's Cove", "town"],
  ["Crow Head", "town"],
  ["Cupids", "town"],
  ["Daniel's Harbour", "town"],
  ["Deer Lake", "town"],
  ["Dover", "town"],
  ["Eastport", "town"],
  ["Elliston", "town"],
  ["Embree", "town"],
  ["Englee", "town"],
  ["English Harbour East", "town"],
  ["Fermeuse", "town"],
  ["Ferryland", "town"],
  ["Flatrock", "town"],
  ["Fleur de Lys", "town"],
  ["Flower's Cove", "town"],
  ["Fogo Island", "town"],
  ["Forteau", "town"],
  ["Fortune", "town"],
  ["Fox Cove-Mortier", "town"],
  ["Frenchman's Cove", "town"],
  ["Gallants", "town"],
  ["Gambo", "town"],
  ["Gander", "town"],
  ["Garnish", "town"],
  ["Gaskiers-Point La Haye", "town"],
  ["Gaultois", "town"],
  ["George's Brook-Milton", "town"],
  ["Gillams", "town"],
  ["Glenburnie-Birchy Head-Shoal Brook", "town"],
  ["Glenwood", "town"],
  ["Glovertown", "town"],
  ["Goose Cove East", "town"],
  ["Grand Bank", "town"],
  ["Grand Falls-Windsor", "town"],
  ["Grand le Pierre", "town"],
  ["Greenspond", "town"],
  ["Hampden", "town"],
  ["Hant's Harbour", "town"],
  ["Happy Adventure", "town"],
  ["Happy Valley-Goose Bay", "town"],
  ["Harbour Breton", "town"],
  ["Harbour Grace", "town"],
  ["Harbour Main-Chapel's Cove-Lakeview", "town"],
  ["Hare Bay", "town"],
  ["Hawke's Bay", "town"],
  ["Heart\s Content", "town"],
  ["Heart's Delight-Islington", "town"],
  ["Heart's Desire", "town"],
  ["Hermitage-Sandyville", "town"],
  ["Holyrood", "town"],
  ["Howley", "town"],
  ["Hughes Brook", "town"],
  ["Humber Arm South", "town"],
  ["Indian Bay", "town"],
  ["Irishtown-Summerside", "town"],
  ["Isle aux Morts", "town"],
  ["Jackson's Arm", "town"],
  ["Keels", "town"],
  ["King's Cove", "town"],
  ["King's Point", "town"],
  ["Kippens", "town"],
  ["Labrador City", "town"],
  ["Lamaline", "town"],
  ["L'Anse-au-Clair", "town"],
  ["L'Anse-au-Loup", "town"],
  ["Lark Harbour", "town"],
  ["LaScie", "town"],
  ["Lawn", "town"],
  ["Leading Tickles", "town"],
  ["Lewin\s Cove", "town"],
  ["Lewisporte", "town"],
  ["Little Bay", "town"],
  ["Little Burnt Bay", "town"],
  ["Logy Bay-Middle Cove-Outer Cove", "town"],
  ["Long Harbour-Mount Arlington Heights", "town"],
  ["Lord's Cove", "town"],
  ["Lourdes", "town"],
  ["Lumsden", "town"],
  ["Lushes Bight-Beaumont-Beaumont North", "town"],
  ["Main Brook", "town"],
  ["Mary's Harbour", "town"],
  ["Marystown", "town"],
  ["Massey Drive", "town"],
  ["Mclvers", "town"],
  ["Meadows", "town"],
  ["Middle Arm", "town"],
  ["Miles Cove", "town"],
  ["Millertown", "town"],
  ["Milltown-Head of Bay d'Espoir", "town"],
  ["Ming's Bight", "town"],
  ["Morrisville", "town"],
  ["Mount Carmel-Mitchells Brook-St. Catherines", "town"],
  ["Mount Moriah", "town"],
  ["Musgrave Harbour", "town"],
  ["Musgravetown", "town"],
  ["New Perlican", "town"],
  ["New-Wes-Valley", "town"],
  ["Nipper's Harbour", "town"],
  ["Norman's Cove-Long Cove", "town"],
  ["Norris Arm", "town"],
  ["Norris Point", "town"],
  ["North River", "town"],
  ["North West River", "town"],
  ["Northern Arm", "town"],
  ["Old Perlican", "town"],
  ["Pacquet", "town"],
  ["Paradise", "town"],
  ["Parkers Cove", "town"],
  ["Parson's Pond"],
  ["Pasadena", "town"],
  ["Peterview", "town"],
  ["Petty Harbour-Maddox Cove", "town"],
  ["Pilley's Island", "town"],
  ["Pinware", "town"],
  ["Placentia", "town"],
  ["Point au Gaul", "town"],
  ["Point Lance", "town"],
  ["Point Leamington", "town"],
  ["Point May", "town"],
  ["Point of Bay", "town"],
  ["Pool's Cove", "town"],
  ["Port Anson", "town"],
  ["Port au Choix", "town"],
  ["Port au Port East", "town"],
  ["Port au Port West-Aguathuna-Felix Cove", "town"],
  ["Port Blandford", "town"],
  ["Port Hope Simpson", "town"],
  ["Port Kirwan", "town"],
  ["Port Rexton", "town"],
  ["Port Saunders", "town"],
  ["Portugal Cove South", "town"],
  ["Portugal Cove-St. Philip's", "town"],
  ["Pouch Cove", "town"],
  ["Raleigh", "town"],
  ["Ramea", "town"],
  ["Red Bay", "town"],
  ["Red Harbour", "town"],
  ["Reidville", "town"],
  ["Rencontre East", "town"],
  ["Renews-Cappahayden", "town"],
  ["River of Ponds", "town"],
  ["Riverhead", "town"],
  ["Robert's Arm", "town"],
  ["Rocky Harbour", "town"],
  ["Roddickton-Bide Arm", "town"],
  ["Rose Blanche-Harbour le Cou", "town"],
  ["Rushoon", "town"],
  ["Salmon Cove", "town"],
  ["Salvage", "town"],
  ["Sandringham", "town"],
  ["Sandy Cove", "town"],
  ["Seal Cove (Fortune Bay)", "town"],
  ["Seal Cove (White Bay)", "town"],
  ["Small Point-Adam's Cove-Blackhead-Broad Cove", "town"],
  ["South Brook", "town"],
  ["South River", "town"],
  ["Southern Harbour", "town"],
  ["Spaniard's Bay", "town"],
  ["Springdale", "town"],
  ["St. Alban's", "town"],
  ["St. Anthony", "town"],
  ["St. Bernard's-Jacques-Fontaine", "town"],
  ["St. Brendan's", "town"],
  ["St. Bride's", "town"],
  ["St. George's", "town"],
  ["St. Jacques-Coomb's Cove", "town"],
  ["St. Joseph's", "town"],
  ["St. Lawrence", "town"],
  ["St. Lewis", "town"],
  ["St. Lunaire-Griquet", "town"],
  ["St. Mary's", "town"],
  ["St. Pauls", "town"],
  ["St. Shott's", "town"],
  ["St. Vincent's-St. Stephen's-Peter's River", "town"],
  ["Steady Brook", "town"],
  ["Stephenville", "town"],
  ["Stephenville Crossing", "town"],
  ["Summerford", "town"],
  ["Sunnyside", "town"],
  ["Terra Nova", "town"],
  ["Terrenceville", "town"],
  ["Torbay", "town"],
  ["Traytown", "town"],
  ["Trepassey", "town"],
  ["Trinity", "town"],
  ["Trinity Bay North", "town"],
  ["Triton", "town"],
  ["Trout River", "town"],
  ["Twillingate", "town"],
  ["Upper Island Cove", "town"],
  ["Victoria", "town"],
  ["Wabana", "town"],
  ["Wabush", "town"],
  ["West St. Modeste", "town"],
  ["Westport", "town"],
  ["Whitbourne", "town"],
  ["Whiteway", "town"],
  ["Winterland", "town"],
  ["Winterton", "town"],
  ["Witless Bay", "town"],
  ["Woodstock", "town"],
  ["Woody Point, Bonne Bay", "town"],
  ["York Harbour", "town"],
  ["Hopedale", "inuit community government"],
  ["Makkovik", "inuit community government"],
  ["Nain", "inuit community government"],
  ["Postville", "inuit community government"],
  ["Rigolet", "inuit community government"],
];

export { description, municipalities };
