const description =
  "Ontario has 444 municipalities that covers 17% of the province's land mass. 444 municipalities are further divided into 30 upper-tier municipalities and 414 local municipalities. 414 local municipalities consist of 241 lower-tier municipalities and 173 single-tier municipalities.";

// ['name, status, censusDivision']
const lowerTier = [
  ["Addington Highlands", "township", "Lennox and Addington"],
  ["Adelaide Metcalfe", "township", "Middlesex"],
  ["Adjala-Tosorontia", "township", "Simcoe"],
  ["Admaston/Bromley", "township", "Renfrew"],
  ["Ajax", "town", "Durham"],
  ["Alfred and Plantagenet", "township", "Prescott and Russell"],
  ["Algonquin Highlands", "township", "Haliburton"],
  ["Alnwick/Haldimand", "township", "Northumberland"],
  ["Amaranth", "township", "Dufferin"],
  ["Amherstburg", "town", "Essex"],
  ["Arnprior", "town", "Renfrew"],
  ["Arran-Elderslie", "municipality", "Bruce"],
  ["Ashfield-Colborne-Wawanosh", "township", "Huron"],
  ["Asphodel-Norwood", "township", "Peterborough"],
  ["Athens", "township", "Leeds and Grenville"],
  ["Augusta", "township", "Leeds and Grenville"],
  ["Aurora", "town", "York"],
  ["Aylmer", "town", "Elgin"],
  ["Bancroft", "town", "Hastings"],
  ["Bayham", "municipality", "Elgin"],
  ["Beckwith", "township", "Lanark"],
  ["Blandford-Blenheim", "township", "Oxford"],
  ["Bluewater", "municipality", "Huron"],
  ["Bonnechere Valley", "township", "Renfrew"],
  ["Bracebridge", "town", "Muskoka"],
  ["Bradford West Gwillimbury", "town", "Simcoe"],
  ["Brampton", "city", "Peel"],
  ["Brighton", "municipality", "Northumberland"],
  ["Brock", "township", "Durham"],
  ["Brockton", "municipality", "Bruce"],
  ["Brooke-Alvinston", "municipality", "Lambton"],
  ["Brudenell, Lyndoch and Raglan", "township", "Renfrew"],
  ["Burlington", "city", "Halton"],
  ["Caledon", "town", "Peel"],
  ["Cambridge", "city", "Waterloo"],
  ["Carleton Place", "town", "Lanark"],
  ["Carlow/Mayo", "township", "Hastings"],
  ["Cassalman", "village", "Prescott and Russell"],
  ["Cavan Monaghan", "township", "Peterborough"],
  ["Central Elgin", "municipality", "Elgin"],
  ["Central Frontenac", "township", "Frontenac"],
  ["Central Huron", "municipality", "Huron"],
  ["Centre Hastings", "municipality", "Hastings"],
  ["Centre Wellington", "township", "Wellington"],
  ["Champlain", "township", "Prescott and Russell"],
  ["Chatsworth", "township", "Grey"],
  ["Clarence-Rockland", "city", "Prescott and Russell"],
  ["Clarington", "municipality", "Durham"],
  ["Clearview", "township", "Simcoe"],
  ["Cobourg", "town", "Northumberland"],
  ["Collingwood", "town", "Simcoe"],
  ["Cramahe", "township", "Northumberland"],
  ["Dawn-Euphemia", "township", "Lambton"],
  ["Deep River", "town", "Renfrew"],
  ["Deseronto", "town", "Hastings"],
  ["Douro-Dummer", "township", "Peterborough"],
  ["Drummond/North Elmsley", "township", "Lanark"],
  ["Dutton/Dunwich", "municipality", "Elgin"],
  ["Dysart et al", "municipality", "Haliburton"],
  ["East Garafraxa", "township", "Dufferin"],
  ["East Gwillimbury", "town", "York"],
  ["East Hawkesbury", "township", "Prescott and Russell"],
  ["East Zorra-Tavistock", "township", "Oxford"],
  ["Edwardsburgh/Cardinal", "township", "Leeds and Grenville"],
  ["Elizabethtown-Kitley", "township", "Leeds and Grenville"],
  ["Enniskillen", "township", "Lambton"],
  ["Erin", "town", "Wellington"],
  ["Essa", "township", "Simcoe"],
  ["Essex", "town", "Essex"],
  ["Faraday", "township", "Hastings"],
  ["Fort-Erie", "town", "Niagara"],
  ["Front of Yonge", "township", "Leeds and Grenville"],
  ["Frontenac Islands", "township", "Frontenac"],
  ["Georgian Bay", "township", "Muskoka"],
  ["Georgian Bluffs", "township", "Grey"],
  ["Georgina", "town", "York"],
  ["Goderich", "town", "Huron"],
  ["Grand Valley", "town", "Dufferin"],
  ["Gravenhurst", "town", "Muskoka"],
  ["Greater Madawaska", "township", "Renfrew"],
  ["Greater Napanee", "town", "Lennox and Addington"],
  ["Grey Highlands", "municipality", "Grey"],
  ["Grimsby", "town", "Niagara"],
  ["Guelph/Eramosa", "township", "Wellington"],
  ["Halton Hills", "town", "Halton"],
  ["Hamilton", "township", "Northumberland"],
  ["Hanover", "town", "Grey"],
  ["Hastings Highlands", "municipality", "Hastings"],
  ["Havelock-Belmont-Methuen", "township", "Peterborough"],
  ["Hawkesbury", "town", "Prescott and Russell"],
  ["Head, Clara and Maria", "township", "Renfrew"],
  ["Highlands East", "municipality", "Haliburton"],
  ["Horton", "township", "Renfrew"],
  ["Howick", "township", "Huron"],
  ["Huntsville", "town", "Muskoka"],
  ["Huron East", "municipality", "Huron"],
  ["Huron-Kinloss", "township", "Bruce"],
  ["Ingersoll", "town", "Oxford"],
  ["Innisfil", "town", "Simcoe"],
  ["Killaloe, Hagarty and Richards", "township", "Renfrew"],
  ["Kincardine", "municipality", "Bruce"],
  ["King", "township", "York"],
  ["Kingsville", "town", "Essex"],
  ["Kitchener", "city", "Waterloo"],
  ["Lake of Bays", "township", "Muskoka"],
  ["Lakeshore", "town", "Essex"],
  ["Lambton Shores", "municipality", "Lambton"],
  ["Lanark Highlands", "township", "Lanark"],
  ["LaSalle", "town", "Essex"],
  ["Laurentian Hills", "town", "Renfrew"],
  ["Laurentian Valley", "township", "Renfrew"],
  ["Leamington", "municipality", "Essex"],
  ["Leeds and the Thousand Islands", "township", "Leeds and Grenville"],
  ["Limerick", "township", "Hastings"],
  ["Lincoln", "town", "Niagara"],
  ["Loyalist", "township", "Lennox and Addington"],
  ["Lucan Biddulph", "township", "Middlesex"],
  ["Madawaska Valley", "township", "Renfrew"],
  ["Madoc", "township", "Hastings"],
  ["Malahide", "township", "Elgin"],
  ["Mapleton", "township", "Wellington"],
  ["Markham", "city", "York"],
  ["Marmora and Lake", "municipality", "Hastings"],
  ["McNab/Braeside", "township", "Renfrew"],
  ["Meaford", "municipality", "Grey"],
  ["Melancthon", "township", "Dufferin"],
  ["Merrickville-Wolford", "village", "Leeds and Grenville"],
  ["Middlesex Centre", "municipality", "Middlesex"],
  ["Midland", "town", "Simcoe"],
  ["Milton", "town", "Halton"],
  ["Minden Hills", "township", "Haliburton"],
  ["Minto", "town", "Wellington"],
  ["Mississauga", "city", "Peel"],
  ["Mississippi Mills", "town", "Lanark"],
  ["Mono", "town", "Dufferin"],
  ["Montague", "township", "Lanark"],
  ["Morris-Turnberry", "municipality", "Huron"],
  ["Mulmur", "township", "Dufferin"],
  ["Muskoka Lakes", "township", "Muskoka"],
  ["The Nation", "municipality", "Prescott and Russell"],
  ["New Tecumseth", "town", "Simcoe"],
  ["Newbury", "village", "Middlesex"],
  ["Newmarket", "town", "York"],
  ["Niagara Falls", "city", "Niagara"],
  ["Niagara-on-the-Lake", "town", "Niagara"],
  ["North Algona Wilberforce", "township", "Renfrew"],
  ["North Dumfries", "township", "Waterloo"],
  ["North Dundas", "township", "Stormont, Dundas and Glengarry"],
  ["North Frontenac", "township", "Frontenac"],
  ["North Glengarry", "township", "Stormont, Dundas and Glengarry"],
  ["North Grenville", "municipality", "Leeds and Grenville"],
  ["North Huron", "township", "Huron"],
  ["North Kawartha", "township", "Peterborough"],
  ["North Middlesex", "municipality", "Middlesex"],
  ["North Perth", "municipality", "Perth"],
  ["North Stormont", "township", "Stormont, Dundas and Glengarry"],
  ["Northern Bruce Peninsula", "municipaolity", "Bruce"],
  ["Norwich", "township", "Oxford"],
  ["Oakville", "town", "Halton"],
  ["Oil Springs", "village", "Lambton"],
  ["Orangeville", "town", "Dufferin"],
  ["Oro-Medonte", "township", "Simcoe"],
  ["Oshawa", "city", "Durham"],
  ["Otonabee-South Monaghan", "township", "Peterborough"],
  ["Owen Sound", "city", "Grey"],
  ["Perth", "town", "Lanark"],
  ["Pelham", "town", "Niagara"],
  ["Penetanguishene", "town", "Simcoe"],
  ["Perth East", "township", "Perth"],
  ["Perth South", "township", "Perth"],
  ["Petawawa", "town", "Renfrew"],
  ["Petrolia", "town", "Lambton"],
  ["Pickering", "city", "Durham"],
  ["Plympton-Wyoming", "town", "Lambton"],
  ["Point Edward", "village", "Lambton"],
  ["Port Colborne", "city", "Niagara"],
  ["Port Hope", "municipality", "Northumberland"],
  ["Puslinch", "township", "Wellington"],
  ["Ramara", "township", "Simcoe"],
  ["Renfrew", "town", "Renfrew"],
  ["Richmond Hill", "city", "York"],
  ["Rideau Lakes", "township", "Leeds and Grenville"],
  ["Russell", "township", "Prescott and Russell"],
  ["Sarnia", "city", "Lambton"],
  ["Saugeen Shores", "town", "Bruce"],
  ["Scugog", "township", "Durham"],
  ["Selwyn", "township", "Peterborough"],
  ["Severn", "township", "Simcoe"],
  ["Shelburne", "town", "Dufferin"],
  ["South Bruce", "municipality", "Bruce"],
  ["South Bruce Peninsula", "town", "Bruce"],
  ["South Dundas", "municipality", "Stormont, Dundas and Glengarry"],
  ["South Frontenac", "township", "Frontenac"],
  ["South Glengarry", "township", "Stormont, Dundas and Glengarry"],
  ["South Huron", "municipality", "Huron"],
  ["South Stormont", "township", "Stormont, Dundas and Glengarry"],
  ["Southgate", "township", "Grey"],
  ["Southwest Middlesex", "municipality", "Middlesex"],
  ["South-West Oxford", "township", "Oxford"],
  ["Southwold", "township", "Elgin"],
  ["Springwater", "township", "Simcoe"],
  ["St. Catharines", "city", "Niagara"],
  ["St. Clair", "township", "Lambton"],
  ["Stirling-Rawdon", "township", "Hastings"],
  ["Stone Mills", "township", "Lennox and Addington"],
  ["Strathroy-Caradoc", "municipality", "Middlesex"],
  ["Tay", "township", "Simcoe"],
  ["Tay Valley", "township", "Lanark"],
  ["Tecumseth", "town", "Essex"],
  ["Thames Centre", "municipality", "Middlesex"],
  ["Thorold", "city", "Niagara"],
  ["The Blue Mountains", "town", "Grey"],
  ["Tillsonburg", "town", "Oxford"],
  ["Tiny", "township", "Simcoe"],
  ["Trent Hills", "municipality", "Northumberland"],
  ["Trent Lakes", "municipality", "Peterborough"],
  ["Tudor and Cashel", "township", "Hastings"],
  ["Tweed", "municipality", "Hastings"],
  ["Tyendinaga", "township", "Hastings"],
  ["Uxbridge", "township", "Durham"],
  ["Vaughan", "city", "York"],
  ["Wainfleet", "township", "Niagara"],
  ["Warwick", "township", "Lambton"],
  ["Wasaga Beach", "town", "Simcoe"],
  ["Waterloo", "city", "Waterloo"],
  ["Welland", "city", "Niagara"],
  ["Wellesley", "township", "Waterloo"],
  ["Wellington North", "township", "Wellington"],
  ["West Elgin", "municipality", "Elgin"],
  ["West Grey", "municipality", "Grey"],
  ["West Lincoln", "township", "Niagara"],
  ["West Perth", "municipality", "Perth"],
  ["Westport", "village", "Leeds and Grenville"],
  ["Whitby", "town", "Durham"],
  ["Whitchurch-Stouffville", "town", "York"],
  ["Whitewater", "township", "Renfrew"],
  ["Wilmot", "township", "Waterloo"],
  ["Wollaston", "township", "Hastings"],
  ["Woodstock", "city", "Oxford"],
  ["Woolwich", "township", "Waterloo"],
  ["Zorra", "township", "Oxford"],
];

const singleTier = [
  ["Alberton", "township", "Rainy River"],
  ["Armour", "township", "Parry Sound"],
  ["Armstrong", "township", "Timiskaming"],
  ["Assiginack", "township", "Manitoulin"],
  ["Atikokan", "town", "Rainy River"],
  ["Baldwin", "township", "Sudbury"],
  ["Barrie", "city", "Simcoe"],
  ["Belleville", "city", "Hastings"],
  ["Billings", "township", "Manitoulin"],
  ["Black River-Matheson", "township", "Cochrane"],
  ["Blind River", "town", "Algoma"],
  ["Bonfield", "township", "Nipissing"],
  ["Brant", "city", "Brant"],
  ["Brantford", "city", "Brant"],
  ["Brethour", "township", "Timiskaming"],
  ["Brockville", "city", "Leeds and Grenville"],
  ["Bruce Mines", "town", "Algoma"],
  ["Burk's Falls", "village", "Parry Sound"],
  ["Burpee and Mills", "township", "Manitoulin"],
  ["Callander", "municipality", "Parry Sound"],
  ["Calvin", "municipality", "Nipissing"],
  ["Carling", "township", "Parry Sound"],
  ["Casey", "township", "Timiskaming"],
  ["Central Manitoulin", "municipality", "Manitoulin"],
  ["Chamberlain", "township", "Timiskaming"],
  ["Chapleau", "township", "Sudbury"],
  ["Chapple", "township", "Rainy River"],
  ["Charlton and Dack", "municipality", "Timiskaming"],
  ["Chatham-Kent", "municipality", "Chatham-Kent"],
  ["Chisholm", "township", "Nipissing"],
  ["Cobalt", "town", "Timiskaming"],
  ["Cochrane", "town", "Cochrane"],
  ["Cockburn Island", "township", "Manitoulin"],
  ["Coleman", "township", "Timiskaming"],
  ["Conmee", "township", "Thunder Bay"],
  ["Cornwall", "city", "Stormont, Dundas and Glengarry"],
  ["Dawson", "township", "Rainy River"],
  ["Dorion", "township", "Thunder Bay"],
  ["Dryden", "city", "Kenora"],
  ["Dubreuilville", "township", "Algoma"],
  ["Ear Falls", "township", "Kenora"],
  ["East Ferris", "municipality", "Nipissing"],
  ["Elliot Lake", "city", "Algoma"],
  ["Emo", "township", "Rainy River"],
  ["Englehart", "town", "Timiskaming"],
  ["Espanola", "town", "Sudbury"],
  ["Evanturel", "township", "Timiskaming"],
  ["Fauquier-Strickland", "Township", "Cochrane"],
  ["Fort Frances", "town", "Rainy River"],
  ["French River", "municipality", "Sudbury"],
  ["Gananoque", "town", "Leeds and Grenville"],
  ["Gauthier", "township", "Timiskaming"],
  ["Gillies", "township", "Thunder Bay"],
  ["Gordon/Barrie Island", "municipality", "Manitoulin"],
  ["Gore Bay", "town", "Manitoulin"],
  ["Greater Sudbury", "city", "Greater Sudbury"],
  ["GreenStone", "municipality", "Thunder Bay"],
  ["Guelph", "city", "Wellington"],
  ["Haldimand", "city", "Haldimand-Norfolk"],
  ["Hamilton", "city", "Hamilton"],
  ["Harley", "township", "Timiskaming"],
  ["Harris", "township", "Timiskaming"],
  ["Hearst", "town", "Cochrane"],
  ["Hilliard", "township", "Timiskaming"],
  ["Hilton", "township", "Algoma"],
  ["Hilton Beach", "village", "Algoma"],
  ["Hornepayne", "township", "Algoma"],
  ["Hudson", "township", "Timiskaming"],
  ["Huron Shores", "municipality", "Algoma"],
  ["Ignace", "township", "Kenora"],
  ["Iroquois Falls", "town", "Cochrane"],
  ["James", "township", "Timiskaming"],
  ["Jocelyn", "township", "Algoma"],
  ["Johnson", "township", "Algoma"],
  ["Joly", "township", "Parry Sound"],
  ["Kapuskasing", "town", "Cochrane"],
  ["Kawartha Lakes", "city", "Kawartha Lakes"],
  ["Kearney", "town", "Parry Sound"],
  ["Kenora", "city", "Kenora"],
  ["Kerns", "township", "Timiskaming"],
  ["Killarney", "municipality", "Sudbury"],
  ["Kingston", "city", "Frontenac"],
  ["Kirkland Lake", "town", "Timiskaming"],
  ["La Vallee", "township", "Rainy River"],
  ["Laird", "township", "Algoma"],
  ["Lake of the Woods", "township", "Rainy River"],
  ["Larder Lake", "township", "Timiskaming"],
  ["Latchford", "town", "Timiskaming"],
  ["London", "city", "Middlesex"],
  ["Macdonald, Meredith and Aberdeen Additional", "township", "Algoma"],
  ["Machar", "township", "Parry Sound"],
  ["Machin", "municipality", "Kenora"],
  ["Magnetawan", "municipality", "Parry Sound"],
  ["Manitouwadge", "township", "Thunder Bay"],
  ["Marathon", "town", "Thunder Bay"],
  ["Markstay-Warren", "municipality", "Sudbury"],
  ["Matachewan", "township", "Timiskaming"],
  ["Mattawa", "town", "Nipissing"],
  ["Mattawan", "township", "Nipissing"],
  ["Mattice-Val Côté", "township", "Cochrane"],
  ["McDougall", "municipality", "Parry Sound"],
  ["McGarry", "township", "Timiskaming"],
  ["McKellar", "township", "Parry Sound"],
  ["McMurrich/Monteith", "township", "Parry Sound"],
  ["Moonbeam", "township", "Cochrane"],
  ["Moosonee", "town", "Cochrane"],
  ["Morley", "township", "Rainy River"],
  ["Nairn and Hyman", "township", "Sudbury"],
  ["Neebing", "municipality", "Thunder Bay"],
  ["Nipigon", "township", "Thunder Bay"],
  ["Nipissing", "township", "Parry Sound"],
  ["Norfolk", "ciy", "Haldimand-Norfolk"],
  ["North Bay", "city", "Nipissing"],
  ["Northeastern Manitoulin and the Islands", "municipality", "Manitoulin"],
  ["O'Connor", "township", "Thunder Bay"],
  ["Oliver Paipoonge", "municipality", "Thunder Bay"],
  ["Opasatika", "township", "Cochrane"],
  ["Orillia", "city", "Simcoe"],
  ["Ottawa", "city", "Ottawa"],
  ["Papineau-Cameron", "township", "Nipissing"],
  ["Parry Sound", "town", "Parry Sound"],
  ["Pelee", "township", "Essex"],
  ["Peterborough", "city", "Peterborough"],
  ["Pembroke", "city", "Renfrew"],
  ["Perry", "township", "Parry Sound"],
  ["Pickle Lake", "township", "Kenora"],
  ["Plummer Additional", "township", "Algoma"],
  ["Powassan", "municipality", "Parry Sound"],
  ["Prescott", "town", "Leeds and Grenville"],
  ["Prince", "township", "Algoma"],
  ["Prince Edward", "city", "Prince Edward"],
  ["Quinte West", "city", "Hastings"],
  ["Rainy River", "town", "Rainy River"],
  ["Red Lake", "municipality", "Kenora"],
  ["Red Rock", "municipality", "Thunder Bay"],
  ["Ryerson", "township", "Parry Sound"],
  ["Sables-Spanish Rivers", "township", "Sudbury"],
  ["Sault Ste. Marie", "city", "Algoma"],
  ["Schreiber", "township", "Thunder Bay"],
  ["Seguin", "township", "Parry Sound"],
  ["Shuniah", "municipality", "Thunder Bay"],
  ["Sioux Lookout", "municipality", "Kenora"],
  ["Sioux Narrows-Nestor Falls", "township", "Kenora"],
  ["Smith Falls", "town", "Lanark"],
  ["Smooth Rock Falls", "town", "Cochrane"],
  ["South Algonquin", "township", "Nipissing"],
  ["South River", "village", "Parry Sound"],
  ["Spanish", "town", "Algoma"],
  ["St. Joseph", "township", "Algoma"],
  ["St. Marys", "town", "Perth"],
  ["St. Thomas", "city", "Elgin"],
  ["St. Charles", "municipality", "Sudbury"],
  ["Stratford", "city", "Perth"],
  ["Strong", "township", "Parry Sound"],
  ["Sundridge", "village", "Parry Sound"],
  ["Tarbutt", "township", "Algoma"],
  ["Tehkummah", "township", "Manitoulin"],
  ["Temagami", "municipality", "Nipissing"],
  ["Temiskaming Shores", "city", "Timiskaming"],
  ["Terrace Bay", "township", "Thunder Bay"],
  ["Thessalon", "town", "Algoma"],
  ["Thornloe", "village", "Timiskaming"],
  ["Thunder Bay", "city", "Thunder Bay"],
  ["The Archipelago", "township", "Parry Sound"],
  ["The North Shore", "township", "Algoma"],
  ["Timmins", "city", "Cochrane"],
  ["Toronto", "city", "Toronto"],
  ["Val Rita-Harty", "township", "Cochrane"],
  ["Wawa", "municipality", "Algoma"],
  ["West Nipissing", "municipality", "Nipissing"],
  ["White River", "township", "Algoma"],
  ["Whitestone", "municipality", "Parry Sound"],
  ["Windsor", "city", "Essex"],
];

// ['name', 'status']
const upperTier = [
  ["Bruce", "county"],
  ["Dufferin", "county"],
  ["Durham", "Regional Municipality"],
  ["Elgin", "county"],
  ["Essex", "county"],
  ["Frontenac", "county"],
  ["Grey", "county"],
  ["Haliburton", "county"],
  ["Halton", "Regional Municipality"],
  ["Hastings", "county"],
  ["Huron", "county"],
  ["Lambton", "county"],
  ["Lanark", "county"],
  ["Leeds and Grenville", "United Counties"],
  ["Lennox and Addington", "county"],
  ["Middlesex", "county"],
  ["Muskoka", "Regional Municipality"],
  ["Niagara", "Regional Municipality"],
  ["Northumberland", "county"],
  ["Oxford", "Regional Municipality"],
  ["Peel", "Regional Municipality"],
  ["Perth", "county"],
  ["Peterborough", "county"],
  ["Prescott and Russell", "United Counties"],
  ["Renfrew", "county"],
  ["Simcoe", "county"],
  ["Stormont, Dundas and Glengarry", "United Counties"],
  ["Waterloo", "Regional Municipality"],
  ["Wellington", "county"],
  ["York", "Regional Municipality"],
];

const municipalities = [...lowerTier, ...singleTier, ...upperTier];

export { description, municipalities };
