// lowerTier shows a array collection of string arrays that include name, tier, mtype (municipality type), partOf (part of upperTier municipality)

const lowerTier = [
  ["Addington Highlands", "lower-tier", "township", "Lennox and Addington"],
  ["Adelaide Metcalfe", "lower-tier", "township", "Middlesex"],
  ["Adjala-Tosorontia", "lower-tier", "township", "Simcoe"],
  ["Admaston/Bromley", "lower-tier", "township", "Renfrew"],
  ["Ajax", "lower-tier", "town", "Durham"],
  ["Alberton", "single-tier", "township", "Rainy River"],
  ["Alfred and Plantagenet", "lower-tier", "township", "Prescott and Russell"],
  ["Algonquin Highlands", "lower-tier", "township", "Haliburton"],
  ["Alnwick/Haldimand", "lower-tier", "township", "Northumberland"],
  ["Amaranth", "lower-tier", "township", "Dufferin"],
  ["Amherstburg", "lower-tier", "town", "Essex"],
  ["Armour", "single-tier", "township", "Parry Sound"],
  ["Armstrong", "single-tier", "township", "Timiskaming"],
  ["Arnprior", "lower-tier", "town", "Renfrew"],
  ["Arran-Elderslie", "lower-tier", "municipality", "Bruce"],
  ["Ashfield-Colborne-Wawanosh", "lower-tier", "township", "Huron"],
  ["Asphodel-Norwood", "lower-tier", "township", "Peterborough"],
  ["Assiginack", "single-tier", "township", "Manitoulin"],
  ["Athens", "lower-tier", "township", "Leeds and Grenville"],
  ["Atikokan", "single-tier", "town", "Rainy River"],
  ["Augusta", "lower-tier", "township", "Leeds and Grenville"],
  ["Aurora", "lower-tier", "town", "York"],
  ["Aylmer", "lower-tier", "town", "Elgin"],
  ["Baldwin", "single-tier", "township", "Sudbury"],
  ["Bancroft", "lower-tier", "town", "Hastings"],
  ["Barrie", "single-tier", "city", "Simcoe"],
  ["Bayham", "lower-tier", "municipality", "Elgin"],
  ["Beckwith", "lower-tier", "township", "Lanark"],
  ["Belleville", "single-tier", "city", "Hastings"],
  ["Billings", "single-tier", "township", "Manitoulin"],
  ["Black River-Matheson", "single-tier", "township", "Cochrane"],
  ["Blandford-Blenheim", "lower-tier", "township", "Oxford"],
  ["Blind River", "single-tier", "town", "Algoma"],
  ["Bluewater", "lower-tier", "municipality", "Huron"],
  ["Bonfield", "single-tier", "township", "Nipissing"],
  ["Bonnechere Valley", "lower-tier", "township", "Renfrew"],
  ["Bracebridge", "lower-tier", "town", "Muskoka"],
  ["Bradford West Gwillimbury", "lower-tier", "town", "Simcoe"],
  ["Brampton", "lower-tier", "city", "Peel"],
  ["Brant", "single-tier", "city", "Brant"],
  ["Brantford", "single-tier", "city", "Brant"],
  ["Brethour", "single-tier", "township", "Timiskaming"],
  ["Brighton", "lower-tier", "municipality", "Northumberland"],
  ["Brock", "lower-tier", "township", "Durham"],
  ["Brockton", "lower-tier", "municipality", "Bruce"],
  ["Brockville", "single-tier", "city", "Leeds and Grenville"],
  ["Brooke-Alvinston", "lower-tier", "municipality", "Lambton"],
  ["Bruce Mines", "single-tier", "town", "Algoma"],
  ["Brudenell, Lyndoch and Raglan", "lower-tier", "township", "Renfrew"],
  ["Burk's Falls", "single-tier", "village", "Parry Sound"],
  ["Burlington", "lower-tier", "city", "Halton"],
  ["Burpee and Mills", "single-tier", "township", "Manitoulin"],
  ["Caledon", "lower-tier", "town", "Peel"],
  ["Callander", "single-tier", "municipality", "Parry Sound"],
  ["Calvin", "single-tier", "municipality", "Nipissing"],
  ["Cambridge", "lower-tier", "city", "Waterloo"],
  ["Carleton Place", "lower-tier", "town", "Lanark"],
  ["Carling", "single-tier", "township", "Parry Sound"],
  ["Carlow/Mayo", "lower-tier", "township", "Hastings"],
  ["Casey", "single-tier", "township", "Timiskaming"],
  ["Cassalman", "lower-tier", "village", "Prescott and Russell"],
  ["Cavan Monaghan", "lower-tier", "township", "Peterborough"],
  ["Central Elgin", "lower-tier", "municipality", "Elgin"],
  ["Central Frontenac", "lower-tier", "township", "Frontenac"],
  ["Central Huron", "lower-tier", "municipality", "Huron"],
  ["Central Manitoulin", "single-tier", "municipality", "Manitoulin"],
  ["Centre Hastings", "lower-tier", "municipality", "Hastings"],
  ["Centre Wellington", "lower-tier", "township", "Wellington"],
  ["Chamberlain", "single-tier", "township", "Timiskaming"],
  ["Champlain", "lower-tier", "township", "Prescott and Russell"],
  ["Chapleau", "single-tier", "township", "Sudbury"],
  ["Chapple", "single-tier", "township", "Rainy River"],
  ["Charlton and Dack", "single-tier", "municipality", "Timiskaming"],
  ["Chatham-Kent", "single-tier", "municipality", "Chatham-Kent"],
  ["Chatsworth", "lower-tier", "township", "Grey"],
  ["Chisholm", "single-tier", "township", "Nipissing"],
  ["Clarence-Rockland", "lower-tier", "city", "Prescott and Russell"],
  ["Clarington", "lower-tier", "municipality", "Durham"],
  ["Clearview", "lower-tier", "township", "Simcoe"],
  ["Cobalt", "single-tier", "town", "Timiskaming"],
  ["Cobourg", "lower-tier", "town", "Northumberland"],
  ["Cochrane", "single-tier", "town", "Cochrane"],
  ["Cockburn Island", "single-tier", "township", "Manitoulin"],
  ["Coleman", "single-tier", "township", "Timiskaming"],
  ["Collingwood", "lower-tier", "town", "Simcoe"],
  ["Conmee", "single-tier", "township", "Thunder Bay"],
  ["Cornwall", "single-tier", "city", "Stormont, Dundas and Glengarry"],
  ["Cramahe", "lower-tier", "township", "Northumberland"],
  ["Dawn-Euphemia", "lower-tier", "township", "Lambton"],
  ["Dawson", "single-tier", "township", "Rainy River"],
  ["Deep River", "lower-tier", "town", "Renfrew"],
  ["Deseronto", "lower-tier", "town", "Hastings"],
  ["Dorion", "single-tier", "township", "Thunder Bay"],
  ["Douro-Dummer", "lower-tier", "township", "Peterborough"],
  ["Drummond/North Elmsley", "lower-tier", "township", "Lanark"],
  ["Dryden", "single-tier", "city", "Kenora"],
  ["Dubreuilville", "single-tier", "township", "Algoma"],
  ["Dutton/Dunwich", "lower-tier", "municipality", "Elgin"],
  ["Dysart et al", "lower-tier", "municipality", "Haliburton"],
  ["Ear Falls", "single-tier", "township", "Kenora"],
  ["East Ferris", "single-tier", "municipality", "Nipissing"],
  ["East Garafraxa", "lower-tier", "township", "Dufferin"],
  ["East Gwillimbury", "lower-tier", "town", "York"],
  ["East Hawkesbury", "lower-tier", "township", "Prescott and Russell"],
  ["East Zorra-Tavistock", "lower-tier", "township", "Oxford"],
  ["Edwardsburgh/Cardinal", "lower-tier", "township", "Leeds and Grenville"],
  ["Elizabethtown-Kitley", "lower-tier", "township", "Leeds and Grenville"],
  ["Elliot Lake", "single-tier", "city", "Algoma"],
  ["Emo", "single-tier", "township", "Rainy River"],
  ["Englehart", "single-tier", "town", "Timiskaming"],
  ["Enniskillen", "lower-tier", "township", "Lambton"],
  ["Erin", "lower-tier", "town", "Wellington"],
  ["Espanola", "single-tier", "town", "Sudbury"],
  ["Essa", "lower-tier", "township", "Simcoe"],
  ["Essex", "lower-tier", "town", "Essex"],
  ["Evanturel", "single-tier", "township", "Timiskaming"],
  ["Faraday", "lower-tier", "township", "Hastings"],
  ["Fauquier-Strickland", "single-tier", "Township", "Cochrane"],
  ["Fort-Erie", "lower-tier", "town", "Niagara"],
  ["Fort Frances", "single-tier", "town", "Rainy River"],
  ["French River", "single-tier", "municipality", "Sudbury"],
  ["Front of Yonge", "lower-tier", "township", "Leeds and Grenville"],
  ["Frontenac Islands", "lower-tier", "township", "Frontenac"],
  ["Gananoque", "single-tier", "town", "Leeds and Grenville"],
  ["Gauthier", "single-tier", "township", "Timiskaming"],
  ["Georgian Bay", "lower-tier", "township", "Muskoka"],
  ["Georgian Bluffs", "lower-tier", "township", "Grey"],
  ["Georgina", "lower-tier", "town", "York"],
  ["Gillies", "single-tier", "township", "Thunder Bay"],
  ["Goderich", "lower-tier", "town", "Huron"],
  ["Gordon/Barrie Island", "single-tier", "municipality", "Manitoulin"],
  ["Gore Bay", "single-tier", "town", "Manitoulin"],
  ["Grand Valley", "lower-tier", "town", "Dufferin"],
  ["Gravenhurst", "lower-tier", "town", "Muskoka"],
  ["Greater Madawaska", "lower-tier", "township", "Renfrew"],
  ["Greater Napanee", "lower-tier", "town", "Lennox and Addington"],
  ["Greater Sudbury", "single-tier", "city", "Greater Sudbury"],
  ["GreenStone", "single-tier", "municipality", "Thunder Bay"],
  ["Grey Highlands", "lower-tier", "municipality", "Grey"],
  ["Grimsby", "lower-tier", "town", "Niagara"],
  ["Guelph", "single-tier", "city", "Wellington"],
  ["Guelph/Eramosa", "lower-tier", "township", "Wellington"],
  ["Haldimand", "single-tier", "city", "Haldimand-Norfolk"],
  ["Halton Hills", "lower-tier", "town", "Halton"],
  ["Hamilton", "lower-tier", "township", "Northumberland"],
  ["Hamilton", "single-tier", "city", "Hamilton"],
  ["Hanover", "lower-tier", "town", "Grey"],
  ["Harley", "single-tier", "township", "Timiskaming"],
  ["Harris", "single-tier", "township", "Timiskaming"],
  ["Hastings Highlands", "lower-tier", "municipality", "Hastings"],
  ["Havelock-Belmont-Methuen", "lower-tier", "township", "Peterborough"],
  ["Hawkesbury", "lower-tier", "town", "Prescott and Russell"],
  ["Head, Clara and Maria", "lower-tier", "township", "Renfrew"],
  ["Hearst", "single-tier", "town", "Cochrane"],
  ["Highlands East", "lower-tier", "municipality", "Haliburton"],
  ["Hilliard", "single-tier", "township", "Timiskaming"],
  ["Hilton", "single-tier", "township", "Algoma"],
  ["Hilton Beach", "single-tier", "village", "Algoma"],
  ["Hornepayne", "single-tier", "township", "Algoma"],
  ["Horton", "lower-tier", "township", "Renfrew"],
  ["Howick", "lower-tier", "township", "Huron"],
  ["Hudson", "single-tier", "township", "Timiskaming"],
  ["Huntsville", "lower-tier", "town", "Muskoka"],
  ["Huron East", "lower-tier", "municipality", "Huron"],
  ["Huron Shores", "single-tier", "municipality", "Algoma"],
  ["Huron-Kinloss", "lower-tier", "township", "Bruce"],
  ["Ignace", "single-tier", "township", "Kenora"],
  ["Ingersoll", "lower-tier", "town", "Oxford"],
  ["Innisfil", "lower-tier", "town", "Simcoe"],
  ["Iroquois Falls", "single-tier", "town", "Cochrane"],
  ["James", "single-tier", "township", "Timiskaming"],
  ["Jocelyn", "single-tier", "township", "Algoma"],
  ["Johnson", "single-tier", "township", "Algoma"],
  ["Joly", "single-tier", "township", "Parry Sound"],
  ["Kapuskasing", "single-tier", "town", "Cochrane"],
  ["Kawartha Lakes", "single-tier", "city", "Kawartha Lakes"],
  ["Kearney", "single-tier", "town", "Parry Sound"],
  ["Kenora", "single-tier", "city", "Kenora"],
  ["Kerns", "single-tier", "township", "Timiskaming"],
  ["Killaloe, Hagarty and Richards", "lower-tier", "township", "Renfrew"],
  ["Killarney", "single-tier", "municipality", "Sudbury"],
  ["Kincardine", "lower-tier", "municipality", "Bruce"],
  ["King", "lower-tier", "township", "York"],
  ["Kingston", "single-tier", "city", "Frontenac"],
  ["Kingsville", "lower-tier", "town", "Essex"],
  ["Kirkland Lake", "single-tier", "town", "Timiskaming"],
  ["Kitchener", "lower-tier", "city", "Waterloo"],
  ["La Vallee", "single-tier", "township", "Rainy River"],
  ["Laird", "single-tier", "township", "Algoma"],
  ["Lake of Bays", "lower-tier", "township", "Muskoka"],
  ["Lake of the Woods", "single-tier", "township", "Rainy River"],
  ["Lakeshore", "lower-tier", "town", "Essex"],
  ["Lambton Shores", "lower-tier", "municipality", "Lambton"],
  ["Lanark Highlands", "lower-tier", "township", "Lanark"],
  ["Larder Lake", "single-tier", "township", "Timiskaming"],
  ["LaSalle", "lower-tier", "town", "Essex"],
  ["Latchford", "single-tier", "town", "Timiskaming"],
  ["Laurentian Hills", "lower-tier", "town", "Renfrew"],
  ["Laurentian Valley", "lower-tier", "township", "Renfrew"],
  ["Leamington", "lower-tier", "municipality", "Essex"],
  [
    "Leeds and the Thousand Islands",
    "lower-tier",
    "township",
    "Leeds and Grenville",
  ],
  ["Limerick", "lower-tier", "township", "Hastings"],
  ["Lincoln", "lower-tier", "town", "Niagara"],
  ["London", "single-tier", "city", "Middlesex"],
  ["Loyalist", "lower-tier", "township", "Lennox and Addington"],
  ["Lucan Biddulph", "lower-tier", "township", "Middlesex"],
  [
    "Macdonald, Meredith and Aberdeen Additional",
    "single-tier",
    "township",
    "Algoma",
  ],
  ["Machar", "single-tier", "township", "Parry Sound"],
  ["Machin", "single-tier", "municipality", "Kenora"],
  ["Madawaska Valley", "lower-tier", "township", "Renfrew"],
  ["Madoc", "lower-tier", "township", "Hastings"],
  ["Magnetawan", "single-tier", "municipality", "Parry Sound"],
  ["Malahide", "lower-tier", "township", "Elgin"],
  ["Manitouwadge", "single-tier", "township", "Thunder Bay"],
  ["Mapleton", "lower-tier", "township", "Wellington"],
  ["Marathon", "single-tier", "town", "Thunder Bay"],
  ["Markham", "lower-tier", "city", "York"],
  ["Markstay-Warren", "single-tier", "municipality", "Sudbury"],
  ["Marmora and Lake", "lower-tier", "municipality", "Hastings"],
  ["Matachewan", "single-tier", "township", "Timiskaming"],
  ["Mattawa", "single-tier", "town", "Nipissing"],
  ["Mattawan", "single-tier", "township", "Nipissing"],
  ["Mattice-Val Côté", "single-tier", "township", "Cochrane"],
  ["McDougall", "single-tier", "municipality", "Parry Sound"],
  ["McGarry", "single-tier", "township", "Timiskaming"],
  ["McKellar", "single-tier", "township", "Parry Sound"],
  ["McMurrich/Monteith", "single-tier", "township", "Parry Sound"],
  ["McNab/Braeside", "lower-tier", "township", "Renfrew"],
  ["Meaford", "lower-tier", "municipality", "Grey"],
  ["Melancthon", "lower-tier", "township", "Dufferin"],
  ["Merrickville-Wolford", "lower-tier", "village", "Leeds and Grenville"],
  ["Middlesex Centre", "lower-tier", "municipality", "Middlesex"],
  ["Midland", "lower-tier", "town", "Simcoe"],
  ["Milton", "lower-tier", "town", "Halton"],
  ["Minden Hills", "lower-tier", "township", "Haliburton"],
  ["Minto", "lower-tier", "town", "Wellington"],
  ["Mississauga", "lower-tier", "city", "Peel"],
  ["Mississippi Mills", "lower-tier", "town", "Lanark"],
  ["Mono", "lower-tier", "town", "Dufferin"],
  ["Montague", "lower-tier", "township", "Lanark"],
  ["Moonbeam", "single-tier", "township", "Cochrane"],
  ["Moosonee", "single-tier", "town", "Cochrane"],
  ["Morley", "single-tier", "township", "Rainy River"],
  ["Morris-Turnberry", "lower-tier", "municipality", "Huron"],
  ["Mulmur", "lower-tier", "township", "Dufferin"],
  ["Muskoka Lakes", "lower-tier", "township", "Muskoka"],
  ["Nairn and Hyman", "single-tier", "township", "Sudbury"],
  ["The Nation", "lower-tier", "municipality", "Prescott and Russell"],
  ["Neebing", "single-tier", "municipality", "Thunder Bay"],
  ["New Tecumseth", "lower-tier", "town", "Simcoe"],
  ["Newbury", "lower-tier", "village", "Middlesex"],
  ["Newmarket", "lower-tier", "town", "York"],
  ["Niagara Falls", "lower-tier", "city", "Niagara"],
  ["Niagara-on-the-Lake", "lower-tier", "town", "Niagara"],
  ["Nipigon", "single-tier", "township", "Thunder Bay"],
  ["Nipissing", "single-tier", "township", "Parry Sound"],
  ["Norfolk", "single-tier", "ciy", "Haldimand-Norfolk"],
  ["North Algona Wilberforce", "lower-tier", "township", "Renfrew"],
  ["North Bay", "single-tier", "city", "Nipissing"],
  ["North Dumfries", "lower-tier", "township", "Waterloo"],
  ["North Dundas", "lower-tier", "township", "Stormont, Dundas and Glengarry"],
  ["North Frontenac", "lower-tier", "township", "Frontenac"],
  [
    "North Glengarry",
    "lower-tier",
    "township",
    "Stormont, Dundas and Glengarry",
  ],
  ["North Grenville", "lower-tier", "municipality", "Leeds and Grenville"],
  ["North Huron", "lower-tier", "township", "Huron"],
  ["North Kawartha", "lower-tier", "township", "Peterborough"],
  ["North Middlesex", "lower-tier", "municipality", "Middlesex"],
  ["North Perth", "lower-tier", "municipality", "Perth"],
  [
    "North Stormont",
    "lower-tier",
    "township",
    "Stormont, Dundas and Glengarry",
  ],
  [
    "Northeastern Manitoulin and the Islands",
    "single-tier",
    "municipality",
    "Manitoulin",
  ],
  ["Northern Bruce Peninsula", "lower-tier", "municipaolity", "Bruce"],
  ["Norwich", "lower-tier", "township", "Oxford"],
  ["Oakville", "lower-tier", "town", "Halton"],
  ["O'Connor", "single-tier", "township", "Thunder Bay"],
  ["Oil Springs", "lower-tier", "village", "Lambton"],
  ["Oliver Paipoonge", "single-tier", "municipality", "Thunder Bay"],
  ["Opasatika", "single-tier", "township", "Cochrane"],
  ["Orangeville", "lower-tier", "town", "Dufferin"],
  ["Orillia", "single-tier", "city", "Simcoe"],
  ["Oro-Medonte", "lower-tier", "township", "Simcoe"],
  ["Oshawa", "lower-tier", "city", "Durham"],
  ["Otonabee-South Monaghan", "lower-tier", "township", "Peterborough"],
  ["Ottawa", "single-tier", "city", "Ottawa"],
  ["Owen Sound", "lower-tier", "city", "Grey"],
  ["Papineau-Cameron", "single-tier", "township", "Nipissing"],
  ["Parry Sound", "single-tier", "town", "Parry Sound"],
  ["Pelee", "single-tier", "township", "Essex"],
  ["Perth", "lower-tier", "town", "Lanark"],
  ["Peterborough", "single-tier", "city", "Peterborough"],
  ["Pelham", "lower-tier", "town", "Niagara"],
  ["Pembroke", "single-tier", "city", "Renfrew"],
  ["Penetanguishene", "lower-tier", "town", "Simcoe"],
  ["Perry", "single-tier", "township", "Parry Sound"],
  ["Perth East", "lower-tier", "township", "Perth"],
  ["Perth South", "lower-tier", "township", "Perth"],
  ["Petawawa", "lower-tier", "town", "Renfrew"],
  ["Petrolia", "lower-tier", "town", "Lambton"],
  ["Pickering", "lower-tier", "city", "Durham"],
  ["Pickle Lake", "single-tier", "township", "Kenora"],
  ["Plummer Additional", "single-tier", "township", "Algoma"],
  ["Plympton-Wyoming", "lower-tier", "town", "Lambton"],
  ["Point Edward", "lower-tier", "village", "Lambton"],
  ["Port Colborne", "lower-tier", "city", "Niagara"],
  ["Port Hope", "lower-tier", "municipality", "Northumberland"],
  ["Powassan", "single-tier", "municipality", "Parry Sound"],
  ["Prescott", "single-tier", "town", "Leeds and Grenville"],
  ["Prince", "single-tier", "township", "Algoma"],
  ["Prince Edward", "single-tier", "city", "Prince Edward"],
  ["Puslinch", "lower-tier", "township", "Wellington"],
  ["Quinte West", "single-tier", "city", "Hastings"],
  ["Rainy River", "single-tier", "town", "Rainy River"],
  ["Ramara", "lower-tier", "township", "Simcoe"],
  ["Red Lake", "single-tier", "municipality", "Kenora"],
  ["Red Rock", "single-tier", "municipality", "Thunder Bay"],
  ["Renfrew", "lower-tier", "town", "Renfrew"],
  ["Richmond Hill", "lower-tier", "city", "York"],
  ["Rideau Lakes", "lower-tier", "township", "Leeds and Grenville"],
  ["Russell", "lower-tier", "township", "Prescott and Russell"],
  ["Ryerson", "single-tier", "township", "Parry Sound"],
  ["Sables-Spanish Rivers", "single-tier", "township", "Sudbury"],
  ["Sarnia", "lower-tier", "city", "Lambton"],
  ["Saugeen Shores", "lower-tier", "town", "Bruce"],
  ["Sault Ste. Marie", "single-tier", "city", "Algoma"],
  ["Schreiber", "single-tier", "township", "Thunder Bay"],
  ["Scugog", "lower-tier", "township", "Durham"],
  ["Seguin", "single-tier", "township", "Parry Sound"],
  ["Selwyn", "lower-tier", "township", "Peterborough"],
  ["Severn", "lower-tier", "township", "Simcoe"],
  ["Shelburne", "lower-tier", "town", "Dufferin"],
  ["Shuniah", "single-tier", "municipality", "Thunder Bay"],
  ["Sioux Lookout", "single-tier", "municipality", "Kenora"],
  ["Sioux Narrows-Nestor Falls", "single-tier", "township", "Kenora"],
  ["Smith Falls", "single-tier", "town", "Lanark"],
  ["Smooth Rock Falls", "single-tier", "town", "Cochrane"],
  ["South Algonquin", "single-tier", "township", "Nipissing"],
  ["South Bruce", "lower-tier", "municipality", "Bruce"],
  ["South Bruce Peninsula", "lower-tier", "town", "Bruce"],
  [
    "South Dundas",
    "lower-tier",
    "municipality",
    "Stormont, Dundas and Glengarry",
  ],
  ["South Frontenac", "lower-tier", "township", "Frontenac"],
  [
    "South Glengarry",
    "lower-tier",
    "township",
    "Stormont, Dundas and Glengarry",
  ],
  ["South Huron", "lower-tier", "municipality", "Huron"],
  ["South River", "single-tier", "village", "Parry Sound"],
  [
    "South Stormont",
    "lower-tier",
    "township",
    "Stormont, Dundas and Glengarry",
  ],
  ["Southgate", "lower-tier", "township", "Grey"],
  ["Southwest Middlesex", "lower-tier", "municipality", "Middlesex"],
  ["South-West Oxford", "lower-tier", "township", "Oxford"],
  ["Southwold", "lower-tier", "township", "Elgin"],
  ["Spanish", "single-tier", "town", "Algoma"],
  ["Springwater", "lower-tier", "township", "Simcoe"],
  ["St. Catharines", "lower-tier", "city", "Niagara"],
  ["St. Clair", "lower-tier", "township", "Lambton"],
  ["St. Joseph", "single-tier", "township", "Algoma"],
  ["St. Marys", "single-tier", "town", "Perth"],
  ["St. Thomas", "single-tier", "city", "Elgin"],
  ["St. Charles", "single-tier", "municipality", "Sudbury"],
  ["Stirling-Rawdon", "lower-tier", "township", "Hastings"],
  ["Stone Mills", "lower-tier", "township", "Lennox and Addington"],
  ["Stratford", "single-tier", "city", "Perth"],
  ["Strathroy-Caradoc", "lower-tier", "municipality", "Middlesex"],
  ["Strong", "single-tier", "township", "Parry Sound"],
  ["Sundridge", "single-tier", "village", "Parry Sound"],
  ["Tarbutt", "single-tier", "township", "Algoma"],
  ["Tay", "lower-tier", "township", "Simcoe"],
  ["Tay Valley", "lower-tier", "township", "Lanark"],
  ["Tecumseth", "lower-tier", "town", "Essex"],
  ["Tehkummah", "single-tier", "township", "Manitoulin"],
  ["Temagami", "single-tier", "municipality", "Nipissing"],
  ["Temiskaming Shores", "single-tier", "city", "Timiskaming"],
  ["Terrace Bay", "single-tier", "township", "Thunder Bay"],
  ["Thames Centre", "lower-tier", "municipality", "Middlesex"],
  ["Thessalon", "single-tier", "town", "Algoma"],
  ["Thornloe", "single-tier", "village", "Timiskaming"],
  ["Thorold", "lower-tier", "city", "Niagara"],
  ["Thunder Bay", "single-tier", "city", "Thunder Bay"],
  ["The Archipelago", "single-tier", "township", "Parry Sound"],
  ["The Blue Mountains", "lower-tier", "town", "Grey"],
  ["The North Shore", "single-tier", "township", "Algoma"],
  ["Tillsonburg", "lower-tier", "town", "Oxford"],
  ["Timmins", "single-tier", "city", "Cochrane"],
  ["Tiny", "lower-tier", "township", "Simcoe"],
  ["Toronto", "single-tier", "city", "Toronto"],
  ["Trent Hills", "lower-tier", "municipality", "Northumberland"],
  ["Trent Lakes", "lower-tier", "municipality", "Peterborough"],
  ["Tudor and Cashel", "lower-tier", "township", "Hastings"],
  ["Tweed", "lower-tier", "municipality", "Hastings"],
  ["Tyendinaga", "lower-tier", "township", "Hastings"],
  ["Uxbridge", "lower-tier", "township", "Durham"],
  ["Val Rita-Harty", "single-tier", "township", "Cochrane"],
  ["Vaughan", "lower-tier", "city", "York"],
  ["Wainfleet", "lower-tier", "township", "Niagara"],
  ["Warwick", "lower-tier", "township", "Lambton"],
  ["Wasaga Beach", "lower-tier", "town", "Simcoe"],
  ["Waterloo", "lower-tier", "city", "Waterloo"],
  ["Wawa", "single-tier", "municipality", "Algoma"],
  ["Welland", "lower-tier", "city", "Niagara"],
  ["Wellesley", "lower-tier", "township", "Waterloo"],
  ["Wellington North", "lower-tier", "township", "Wellington"],
  ["West Elgin", "lower-tier", "municipality", "Elgin"],
  ["West Grey", "lower-tier", "municipality", "Grey"],
  ["West Lincoln", "lower-tier", "township", "Niagara"],
  ["West Nipissing", "single-tier", "municipality", "Nipissing"],
  ["West Perth", "lower-tier", "municipality", "Perth"],
  ["Westport", "lower-tier", "village", "Leeds and Grenville"],
  ["Whitby", "lower-tier", "town", "Durham"],
  ["Whitchurch-Stouffville", "lower-tier", "town", "York"],
  ["White River", "single-tier", "township", "Algoma"],
  ["Whitestone", "single-tier", "municipality", "Parry Sound"],
  ["Whitewater", "lower-tier", "township", "Renfrew"],
  ["Wilmot", "lower-tier", "township", "Waterloo"],
  ["Windsor", "single-tier", "city", "Essex"],
  ["Wollaston", "lower-tier", "township", "Hastings"],
  ["Woodstock", "lower-tier", "city", "Oxford"],
  ["Woolwich", "lower-tier", "township", "Waterloo"],
  ["Zorra", "lower-tier", "township", "Oxford"],
];

// upperTier shows a array collection of string arrays that include name, tier, mtype.
// upper tier municipalities are made of one or more lower-tier municipalties.
const upperTier = [
  ["Bruce", "upper-tier", "county"],
  ["Dufferin", "upper-tier", "county"],
  ["Durham", "upper-tier", "Regional Municipality"],
  ["Elgin", "upper-tier", "county"],
  ["Essex", "upper-tier", "county"],
  ["Frontenac", "upper-tier", "county"],
  ["Grey", "upper-tier", "county"],
  ["Haliburton", "upper-tier", "county"],
  ["Halton", "upper-tier", "Regional Municipality"],
  ["Hastings", "upper-tier", "county"],
  ["Huron", "upper-tier", "county"],
  ["Lambton", "upper-tier", "county"],
  ["Lanark", "upper-tier", "county"],
  ["Leeds and Grenville", "upper-tier", "United Counties"],
  ["Lennox and Addington", "upper-tier", "county"],
  ["Middlesex", "upper-tier", "county"],
  ["Muskoka", "upper-tier", "Regional Municipality"],
  ["Niagara", "upper-tier", "Regional Municipality"],
  ["Northumberland", "upper-tier", "county"],
  ["Oxford", "upper-tier", "Regional Municipality"],
  ["Peel", "upper-tier", "Regional Municipality"],
  ["Perth", "upper-tier", "county"],
  ["Peterborough", "upper-tier", "county"],
  ["Prescott and Russell", "upper-tier", "United Counties"],
  ["Renfrew", "upper-tier", "county"],
  ["Simcoe", "upper-tier", "county"],
  ["Stormont, Dundas and Glengarry", "upper-tier", "United Counties"],
  ["Waterloo", "upper-tier", "Regional Municipality"],
  ["Wellington", "upper-tier", "county"],
  ["York", "upper-tier", "Regional Municipality"],
];

export { lowerTier, upperTier };
