const description =
  "Alberta has a total of 341 municipalities that cover 99.7% of the province's land mass. 341 municipalities include 253 urban municipalities, 6 specialized municipalities, 73 rural municipalities, and 8 Metis settlements. 253 urban municipalities consists 19 cities, 105 towns, 78 villages and 51 summer villages. 73 rural municipalities comprises of 63 municipal districts, 7 improvement districts and 3 special areas.";

// ['name', 'status']
const urbanMunicipalities = [
  ["Acme", "village"],
  ["Airdrie", "city"],
  ["Alberta Beach", "village"],
  ["Alix", "village"],
  ["Alliance", "village"],
  ["Amisk", "village"],
  ["Andrew", "village"],
  ["Argentia Beach", "summer village"],
  ["Arrowwood", "village"],
  ["Athabasca", "town"],
  ["Banff", "town"],
  ["Barnwell", "village"],
  ["Barons", "village"],
  ["Barrhead", "town"],
  ["Bashaw", "town"],
  ["Bassano", "town"],
  ["Bawlf", "village"],
  ["Beaumont", "city"],
  ["Beaverlodge", "town"],
  ["Beiseker", "village"],
  ["Bentley", "town"],
  ["Berwyn", "village"],
  ["Betula Beach", "summer village"],
  ["Big Valley", "village"],
  ["Birch Cover", "summber village"],
  ["Birchcliff", "summber village"],
  ["Bittern Lake", "village"],
  ["Blackfalds", "town"],
  ["Bon Accord", "town"],
  ["Bondiss", "summer village"],
  ["Bonnyville", "town"],
  ["Bonnyville Beach", "summer village"],
  ["Bow Island", "town"],
  ["Bowden", "town"],
  ["Boyle", "village"],
  ["Breton", "village"],
  ["Books", "city"],
  ["Bruderheim", "town"],
  ["Burnstick Lake", "summer village"],
  ["Calgary", "city"],
  ["Calmar", "town"],
  ["Camrose", "city"],
  ["Canmore", "town"],
  ["Carbon", "village"],
  ["Cardston", "town"],
  ["Carmangay", "village"],
  ["Carstairs", "town"],
  ["Castle Island", "summer village"],
  ["Castor", "town"],
  ["Champion", "village"],
  ["Chauvin", "village"],
  ["Chestermere", "city"],
  ["Chipman", "village"],
  ["Claresholm", "town"],
  ["Clive", "village"],
  ["Clyde", "village"],
  ["Coaldale", "town"],
  ["Coalhurst", "town"],
  ["Cochrane", "town"],
  ["Cold Lake", "city"],
  ["Consort", "village"],
  ["Coronation", "town"],
  ["Coutts", "village"],
  ["Cowley", "village"],
  ["Cremona", "village"],
  ["Crossfield", "town"],
  ["Crystal Springs", "summer village"],
  ["Czar", "village"],
  ["Daysland", "town"],
  ["Delburne", "village"],
  ["Delia", "village"],
  ["Devon", "town"],
  ["Diamond Valley", "town"],
  ["Didsbury", "town"],
  ["Donalda", "village"],
  ["Donnelly", "village"],
  ["Drayton Valley", "town"],
  ["Drumheller", "town"],
  ["Duchess", "village"],
  ["Eckville", "town"],
  ["Edberg", "village"],
  ["Edgerton", "village"],
  ["Edmonton", "city"],
  ["Edson", "town"],
  ["Elk Point", "town"],
  ["Elnora", "village"],
  ["Empress", "village"],
  ["Fairview", "town"],
  ["Falher", "town"],
  ["Foremost", "village"],
  ["Forestburg", "village"],
  ["Fort Macleod", "town"],
  ["Fort Saskatchewan", "city"],
  ["Fox Creek", "town"],
  ["Ghost Lake", "summer village"],
  ["Gibbons", "town"],
  ["Girouxville", "village"],
  ["Glendon", "village"],
  ["Glenwood", "village"],
  ["Golden Days", "summer village"],
  ["Grande Prairie", "city"],
  ["Grandview", "summer village"],
  ["Grimshaw", "town"],
  ["Gull Lake", "summer village"],
  ["Half Moon Bay", "summer village"],
  ["Hanna", "town"],
  ["Hardisty", "town"],
  ["Hay Lakes", "village"],
  ["Heisler", "village"],
  ["High Level", "town"],
  ["High Prairie", "town"],
  ["High River", "town"],
  ["Hill Spring", "village"],
  ["Hines Creek", "village"],
  ["Hinton", "town"],
  ["Holden", "village"],
  ["Horseshoe Bay", "summer village"],
  ["Hughenden", "village"],
  ["Hussar", "village"],
  ["Innisfail", "town"],
  ["Innisfree", "village"],
  ["Irma", "village"],
  ["Irricana", "town"],
  ["Island Lake", "summer village"],
  ["Island Lake South", "summer village"],
  ["Itaska Beach", "summer village"],
  ["Jarvis Bay", "summer village"],
  ["Kapasiwin", "summer village"],
  ["Killam", "town"],
  ["Kitscoty", "village"],
  ["Lacombe", "city"],
  ["Lakeview", "summer village"],
  ["Lamont", "town"],
  ["Larkspur", "summer village"],
  ["Leduc", "city"],
  ["Legal", "town"],
  ["Lethbridge", "city"],
  ["Linden", "Village"],
  ["Lloydminster", "city"],
  ["Lomond", "village"],
  ["Longview", "village"],
  ["Lougheed", "village"],
  ["Magrath", "town"],
  ["Ma-Me-O Beach", "summer village"],
  ["Manning", "town"],
  ["Mannville", "village"],
  ["Marwayne", "village"],
  ["Mayerthorpe", "town"],
  ["McLennan", "town"],
  ["Medicine Hat", "city"],
  ["Mewatha Beach", "summer village"],
  ["Milk River", "town"],
  ["Millet", "town"],
  ["Milo", "village"],
  ["Morinville", "town"],
  ["Morrin", "village"],
  ["Mundare", "town"],
  ["Munson", "village"],
  ["Myrnam", "village"],
  ["Nakamun Park", "summer village"],
  ["Nampa", "village"],
  ["Nanton", "town"],
  ["Nobleford", "town"],
  ["Norglenworld", "summer village"],
  ["Norris Beach", "summer village"],
  ["Okotoks", "town"],
  ["Olds", "town"],
  ["Onoway", "town"],
  ["Oyen", "town"],
  ["Paradise Valley", "village"],
  ["Parkland Beach", "summer village"],
  ["Peace River", "town"],
  ["Pelican Narrows", "summer village"],
  ["Penhold", "town"],
  ["Picture Butte", "town"],
  ["Pincher Creek", "town"],
  ["Point Alison", "summer village"],
  ["Ponoka", "town"],
  ["Poplar Bay", "summer village"],
  ["Provost", "town"],
  ["Rainbow Lake", "town"],
  ["Raymond", "town"],
  ["Red Deer", "city"],
  ["Redcliff", "town"],
  ["Redwater", "town"],
  ["Rimbey", "town"],
  ["Rochon Sands", "summer village"],
  ["Rocky Mountain House", "town"],
  ["Rockyford", "village"],
  ["Rosalind", "village"],
  ["Rosemary", "village"],
  ["Ross Haven", "summer village"],
  ["Rycroft", "village"],
  ["Ryley", "village"],
  ["Sandy Beach", "summer village"],
  ["Seba Beach", "summer village"],
  ["Sedgewick", "town"],
  ["Sexsmith", "town"],
  ["Silver Beach", "summer village"],
  ["Silver Sands", "summer village"],
  ["Slave Lake", "town"],
  ["Smoky Lake", "town"],
  ["South Baptiste", "summer village"],
  ["South View", "summer village"],
  ["Spirit River", "town"],
  ["Spring Lake", "village"],
  ["Spruce Grove", "city"],
  ["St. Albert", "city"],
  ["St. Paul", "town"],
  ["Standard", "village"],
  ["Stavely", "town"],
  ["Stettler", "town"],
  ["Stirling", "village"],
  ["Stony Plain", "town"],
  ["Strathmore", "town"],
  ["Sunbreaker Cove", "summer village"],
  ["Sundance Beach", "summer village"],
  ["Sundre", "town"],
  ["Sunrise Beach", "summer village"],
  ["Sunset Beach", "summer village"],
  ["Sunset Point", "summer village"],
  ["Swan Hills", "town"],
  ["Sylvan Lake", "town"],
  ["Taber", "town"],
  ["Thorsby", "town"],
  ["Three Hills", "town"],
  ["Tofield", "town"],
  ["Trochu", "town"],
  ["Two Hills", "town"],
  ["Val Quentin", "summer village"],
  ["Valleyview", "town"],
  ["Vauxhall", "town"],
  ["Vegreville", "town"],
  ["Vermilion", "town"],
  ["Veteran", "village"],
  ["Viking", "town"],
  ["Vilna", "village"],
  ["Vulcan", "town"],
  ["Wainwright", "town"],
  ["Waiparous", "summer village"],
  ["Warburg", "village"],
  ["Warner", "village"],
  ["Waskatenau", "village"],
  ["Wembley", "town"],
  ["West Baptiste", "summer village"],
  ["West Cove", "summer village"],
  ["Westlock", "town"],
  ["Wetaskiwin", "city"],
  ["Whispering Hills", "city"],
  ["White Sands", "summer village"],
  ["Whitecourt", "town"],
  ["Yellowstone", "summer village"],
  ["Youngstown", "village"],
];

// ['name', 'status']
const ruralMunicipalities = [
  ["MD of Acadia", "municipal district"],
  ["Athabasca County", "municipal district"],
  ["County of Barrhead No. 11", "municipal district"],
  ["Beaver County", "municipal district"],
  ["Big Lakes County", "municipal district"],
  ["MD of Bighorn No. 8", "municipal district"],
  ["Birch Hills County", "municipal district"],
  ["MD of Bonnyville No. 87", "municipal district"],
  ["Brazeau County", "municipal district"],
  ["Camrose County", "municipal district"],
  ["Cardston County", "municipal district"],
  ["Clear Hills County", "municipal district"],
  ["Clearwater County", "municipal district"],
  ["Cypress County", "municipal district"],
  ["MD of Fairview No. 136", "municipal district"],
  ["Flagstaff County", "municipal district"],
  ["Foothills County", "municipal district"],
  ["County of Forty Mile No. 8", "municipal district"],
  ["County of Grande Prairie No. 1", "municipal district"],
  ["MD of Greenview No. 16", "municipal district"],
  ["Improvement District No. 4", "improvement district"],
  ["Improvement District No. 9", "improvement district"],
  ["Improvement District No. 12", "improvement district"],
  ["Improvement District No. 13", "improvement district"],
  ["Improvement District No. 24", "improvement district"],
  ["Improvement District No. 25", "improvement district"],
  ["Kananaskis Improvement District", "improvement district"],
  ["Kneehill County", "municipal district"],
  ["Lac Ste. Anne County", "municipal district"],
  ["Lacombe County", "municipal district"],
  ["Lamont County", "municipal district"],
  ["Leduc County", "municipal district"],
  ["MD of Lesser Slave River No. 124", "municipal district"],
  ["Lethbridge County", "municipal district"],
  ["County of Minburn No. 27", "municipal district"],
  ["Mountain View County", "municipal district"],
  ["County of Newell", "municipal district"],
  ["County of Northern Lights", "municipal district"],
  ["Northern Sunrise County", "municipal district"],
  ["MD of Opportunity No. 17", "municipal district"],
  ["County of Paintearth No. 18", "municipal district"],
  ["Parkland County", "municipal district"],
  ["MD of Peace No. 135", "municipal district"],
  ["MD of Pincher Creek No. 9", "municipal district"],
  ["Ponoa County", "municipal district"],
  ["MD of Provost No. 52", "municipal district"],
  ["MD of Ranchland No. 66", "municipal district"],
  ["Red Deer County", "municipal district"],
  ["Rocky View County", "municipal district"],
  ["Saddle Hills County", "municipal district"],
  ["Smoky Lake County", "municipal district"],
  ["MD of Smoky River No. 130", "municipal district"],
  ["Special Area No. 2", "special area"],
  ["Special Area No. 3", "special area"],
  ["Special Area No. 4", "special area"],
  ["MD of Spirit River No. 133", "municipal district"],
  ["County of St. Paul No. 19", "municipal district"],
  ["Starland County", "municipal district"],
  ["County of Stettler No. 6", "municipal district"],
  ["Sturgeon County", "municipal district"],
  ["MD of Taber", "municipal district"],
  ["Thorhild County", "municipal district"],
  ["County of Two Hills No. 21", "municipal district"],
  ["County of Vermilion River", "municipal district"],
  ["Vulan County", "municipal district"],
  ["MD of Wainwright No. 61", "municipal district"],
  ["County of Warner No. 5", "municipal district"],
  ["Westlock County", "municipal district"],
  ["County of Wetaskiwin No. 10", "municipal district"],
  ["Wheatland County", "municipal district"],
  ["MD of Willow Creek No. 26", "municipal district"],
  ["Woodlands County", "municipal district"],
  ["Yellowhead County", "municipal district"],
];

const municipalities = [...urbanMunicipalities, ...ruralMunicipalities];

export { description, municipalities };
