const description =
  "Prince Edward Island has 63 municipalities that cover 34.7% of the province's land mass. Prince Edward Island has 2 cities, 10 towns, 50 rural and 1 resort municipalities.";

// ['name', 'status', 'county']
const municipalities = [
  ["Charlottetown", "city", "Queens"],
  ["Summerside", "city", "Prince"],
  ["Alberton", "town", "Prince"],
  ["Borden-Carleton", "town", "Prince"],
  ["Cornwall", "town", "Queens"],
  ["Kensington", "town", "Prince"],
  ["North Rustico", "town", "Queens"],
  ["O'Leary", "town", "Prince"],
  ["Souris", "town", "Kings"],
  ["Stratford", "town", "Queens"],
  ["Three Rivers", "town", "Kings"],
  ["Tignish", "town", "Prince"],
  ["Abram-Village", "rural municipality", "Prince"],
  ["Alexandra", "rural municipality", "Queens"],
  ["Annandale-Little Pond-Howe Bay", "rural municipality", "Kings"],
  ["Bedeque and Area", "rural municipality", "Prince"],
  ["Belfast", "rural municipality", "Queens"],
  ["Brackley", "rural municipality", "Queens"],
  ["Breadalbane", "rural municipality", "Queens"],
  ["Central Kings", "rural municipality", "Kings"],
  ["Central Prince", "rural municipality", "Prince"],
  ["Clyde River", "rural municipality", "Queens"],
  ["Crapaud", "rural municipality", "Queens"],
  ["Darlington", "rural municipality", "Queens"],
  ["Eastern Kings", "rural municipality", "Kings"],
  ["Greenmount-Montrose", "rural municipality", "Prince"],
  ["Hampshire", "rural municipality", "Queens"],
  ["Hazelbrook", "rural municipality", "Queens"],
  ["Hunter River", "rural municipality", "Queens"],
  ["Kingston", "rural municipality", "Queens"],
  ["Kinkora", "rural municipality", "Prince"],
  ["Linkletter", "rural municipality", "Prince"],
  ["Lot 11 and Area", "rural municipality", "Prince"],
  ["Malpeque Bay", "rural municipality", "Queens"],
  ["Miltonvale Park", "rural municipality", "Queens"],
  ["Miminegash", "rural municipality", "Prince"],
  ["Miscouche", "rural municipality", "Prince"],
  ["Morell", "rural municipality", "Kings"],
  ["Mount Stewart", "rural municipality", "Queens"],
  ["Murray Harbour", "rural municipality", "Kings"],
  ["North Shore", "rural municipality", "Queens"],
  ["North Wiltshire", "rural municipality", "Queens"],
  ["Northport", "rural municipality", "Prince"],
  ["Sherbrooke", "rural municipality", "Prince"],
  ["Souris West", "rural municipality", "Kings"],
  ["St. Felix", "rural municipality", "Prince"],
  ["St. Louis", "rural municipality", "Prince"],
  ["St. Nicholas", "rural municipality", "Prince"],
  ["St. Peters Bay", "rural municipality", "Kings"],
  ["Tignish Shore", "rural municipality", "Prince"],
  ["Tyne Valley", "rural municipality", "Prince"],
  ["Union Road", "rural municipality", "Queens"],
  ["Victoria", "rural municipality", "Queens"],
  ["Warren Grove", "rural municipality", "Queens"],
  ["Wellington", "rural municipality", "Prince"],
  ["West River", "rural municipality", "Queens"],
  ["York", "rural municipality", "Queens"],
  [
    "Stanley Bridge, Hope River, Bayview, Cavendish and North Rustico",
    "resort municipality",
    "Queens",
  ],
];

export { description, municipalities };
