const description =
  "Saskatchewan has 774 municipalities that cover 52.1% of the province's land mass, 454 are urban municipalities, 296 are rural municipalities and 24 are northern municipalities. 454 urban municipalities include 16 cities, 147 towns, 250 villages and 41 resort villages. 24 northern municipalities include 2 norther towns, 11 norhtern villages and 11 northern hamlets.";

// ["name", "status", "ruralMunicipality"]
const urbanMunicipalities = [
  ["Estevan", "city", "Estevan No. 5"],
  ["Flin Flon", "city", ""],
  ["Humboldt", "city", "Humboldt No. 370"],
  ["Lloydminster", "city", "Britannia No. 502 and Wilton No. 472"],
  ["Martensville", "city", "Corman Park No. 344"],
  ["Meadow Lake", "city", "Meadow Lake No. 588"],
  ["Melfort", "city", "Star City No. 428"],
  ["Melville", "city", "Cana No. 214"],
  ["Moose Jaw", "city", "Moose Jaw No. 161"],
  ["North Battleford", "city", "North Battleford No. 437"],
  ["Prince Albert", "city", "Prince Albert No. 461"],
  ["Regina", "city", "Sherwood No. 159"],
  ["Saskatoon", "city", "Corman Park No. 344"],
  ["Swift Current", "city", "Swift Current No. 137"],
  ["Warman", "city", "Corman Park No. 344"],
  ["Weyburn", "city", "Weyburn No. 67"],
  ["Yorkton", "city", "Orkney No. 244"],
  ["Aberdeen", "town", "Aberdeen No. 373"],
  ["Alameda", "town", "Moose Creek No. 33"],
  ["Allan", "town", "Bayne No. 371"],
  ["Arborfield", "town", "Arborfield No. 456"],
  ["Arcola", "town", "Brock No. 64"],
  ["Asquith", "town", "Vanscoy No. 345"],
  ["Assiniboia", "town", "Lake of the Rivers No. 72"],
  ["Balcarres", "town", "Abrnethy No. 186"],
  ["Balgonie", "town", "Edenwold No. 158"],
  ["Battleford", "town", "Battle River No. 438"],
  ["Bengough", "town", "Bengough No. 40"],
  ["Bienfait", "town", "Coalfields No. 4"],
  ["Big River", "town", "Big River No. 555"],
  ["Biggar", "town", "Biggar No. 347"],
  ["Birch Hills", "town", "Birch Hills No. 460"],
  ["Blaine Lake", "town", "Blaine Lake No. 434"],
  ["Bredenbury", "town", "Saltcoats No. 213"],
  ["Broadview", "town", "Elcapo No. 154"],
  ["Bruno", "town", "Bayne No. 371"],
  ["Burstall", "town", "Deer Forks No. 232"],
  ["Cabri", "town", "Riverside No. 168"],
  ["Canora", "town", "Good Lake No. 274"],
  ["Carlyle", "town", "Antler No. 61"],
  ["Carnduff", "town", "Mount Pleasant No. 2"],
  ["Carrot River", "town", "Moose Range No. 486"],
  ["Central Butte", "town", "Enfield No. 194"],
  ["Choiceland", "town", "Torch River No. 488"],
  ["Churchbridge", "town", "Churchbridge No. 211"],
  ["Colonsay", "town", "Colonsay No. 342"],
  ["Coronach", "town", "Hart Butte No. 11"],
  ["Craik", "town", "Craik No. 222"],
  ["Cudworth", "town", "Hoodoo No. 401"],
  ["Cupar", "town", "Cupar No. 218"],
  ["Cut Knife", "town", "Cut Knife No. 439"],
  ["Dalmeny", "town", "Corman Park No. 344"],
  ["Davidson", "town", "Arm River No. 252"],
  ["Delisle", "town", "Vanscoy no. 345"],
  ["Duck Lake", "town", "Duck Lake No. 463"],
  ["Dundurn", "town", "Dundurn No. 314"],
  ["Eastend", "town", "White Valley No. 49"],
  ["Eatonia", "town", "Chesterfield No. 261"],
  ["Elrose", "town", "Money No. 257"],
  ["Esterhazy", "town", "Fertile Belt No. 183"],
  ["Eston", "town", "Snipe Lake No. 259"],
  ["Fleming", "town", "Moosomin No. 121"],
  ["Foam Lake", "town", "Foam Lake No. 276"],
  ["Fort Qu'Appelle", "town", "North Qu'Appelle No. 187"],
  ["Francis", "town", "Francis No. 127"],
  ["Govan", "town", "Last Mountain Valley No. 250"],
  ["Grand Coulee", "town", "Sherwood No. 159"],
  ["Gravelbourg", "town", "Gravelbourg No. 104"],
  ["Grenfell", "town", "Elcapo No. 154"],
  ["Gull Lake", "town", "Gull Lake No. 139"],
  ["Hafford", "town", "Redberry No. 435"],
  ["Hague", "town", "Rosthern No. 403"],
  ["Hanley", "town", "Rosedale No. 283"],
  ["Hepburn", "town", "Laird No. 404"],
  ["Herbert", "town", "Morse No. 165"],
  ["Hudson Bay", "town", "Hudson Bay No. 394"],
  ["Imperial", "town", "Big Arm No. 251"],
  ["Indian Head", "town", "Indian Head No. 156"],
  ["Ituna", "town", "Ituna Bon Accord No. 246"],
  ["Kamsack", "town", "Cote No. 271"],
  ["Kelvington", "town", "Kelvington No. 366"],
  ["Kerrobert", "town", "Progress No. 351"],
  ["Kindersley", "town", "Kindersley No. 290"],
  ["Kinistino", "town", "Kinistino No. 459"],
  ["Kipling", "town", "Kingsley No. 124"],
  ["Kyle", "town", "Lacadena No. 228"],
  ["Lafleche", "town", "Wood River No. 74"],
  ["Lampman", "town", "Browning No. 34"],
  ["Langenburg", "town", "Langenburg No. 181"],
  ["Langham", "town", "Corman Park No. 344"],
  ["Lanigan", "town", "Usborne No. 310"],
  ["Lashburn", "town", "Manitou Lake No. 442"],
  ["Leader", "town", "Happyland No. 231"],
  ["Lemberg", "town", "Abernethy No. 186"],
  ["Leroy", "town", "Leroy No. 339"],
  ["Lumsden", "town", "Lumsden No. 189"],
  ["Luseland", "town", "Progress No. 351"],
  ["Macklin", "town", "Eye Hill No. 382"],
  ["Maidstone", "town", "Eldon No. 471"],
  ["Maple Creek", "town", "Maple Creek No. 111"],
  ["Marshall", "town", "Wilton No. 472"],
  ["Midale", "town", "Cymri No. 36"],
  ["Milestone", "town", "Brock No. 64"],
  ["Moosomin", "town", "Moosomin No. 121"],
  ["Morse", "town", "Morse No. 165"],
  ["Mossbank", "town", "Lake Johnston No. 102"],
  ["Naicam", "town", "Pleasantdale No. 398"],
  ["Nipawin", "town", "Nipawin No. 487"],
  ["Nokomis", "town", "Wreford No. 280"],
  ["Norquay", "town", "Clayton No. 333"],
  ["Ogema", "town", "Key West No. 70"],
  ["Osler", "town", "Corman Park No. 344"],
  ["Outlook", "town", "Rudy No. 284"],
  ["Oxbow", "town", "Enniskillen No. 3"],
  ["Pense", "town", "Pense No. 160"],
  ["Pilot Butte", "town", "Edenwold No. 158"],
  ["Ponteix", "town", "Grassy Creek No. 78"],
  ["Porcupine Plain", "town", "Procupine No. 395"],
  ["Preeceville", "town", "Preeceville No. 334"],
  ["Qu'Appelle", "town", "South Qu'Appelle No. 157"],
  ["Radisson", "town", "Great Bend No. 405"],
  ["Radville", "town", "Laurier No. 38"],
  ["Raymore", "town", "Moose Range No. 486"],
  ["Redvers", "town", "Antler No. 61"],
  ["Regina Beach", "town", "Lumsden No. 189"],
  ["Rocanville", "town", "Rocanville No. 151"],
  ["Rockglen", "town", "Poplar Valley No. 12"],
  ["Rose Valley", "town", "Ponass Lake No. 367"],
  ["Rosthern", "town", "Rosthern No. 403"],
  ["Rouleau", "town", "Redburn No. 130"],
  ["Saltcoats", "town", "Saltcoats No. 213"],
  ["Scott", "town", "Tramping Lake No. 380"],
  ["Shaunavon", "town", "Grassy Creek No. 78"],
  ["Shellbrook", "town", "Shellbrook No. 493"],
  ["Sintaluta", "town", "Indian Head No. 156"],
  ["Southey", "town", "Cupar No. 218"],
  ["Spiritwood", "town", "Spiritwood No. 496"],
  ["Springside", "town", "St. Philips No. 301"],
  ["St. Brieux", "town", "Lake Lenore No. 399"],
  ["St. Walburg", "town", "Frenchman Butte No. 501"],
  ["Star City", "town", "Star City No. 428"],
  ["Stoughton", "town", "Tecumseh No. 65"],
  ["Strasbourg", "town", "McKillop No. 220"],
  ["Sturgis", "town", "Preeceville No. 334"],
  ["Tisdale", "town", "Tisdale No. 427"],
  ["Turtleford", "town", "Mervin No. 499"],
  ["Unity", "town", "Round Valley No. 410"],
  ["Vonda", "town", "Grant No. 372"],
  ["Wadena", "town", "Lakeview No. 337"],
  ["Wakaw", "town", "Fish Creek No. 402"],
  ["Waldheim", "town", "Laird No. 404"],
  ["Wapella", "town", "Martin No. 122"],
  ["Watrous", "town", "Morris No. 313"],
  ["Watson", "town", "Lakeside No. 338"],
  ["Wawota", "town", "Wawken No. 93"],
  ["White City", "town", "Edenwold No. 158"],
  ["Whitewood", "town", "Willowdale No. 153"],
  ["Wilkie", "town", "Tramping Lake No. 380"],
  ["Willow Bunch", "town", "Willow Bunch No. 42"],
  ["Wolseley", "town", "Wolseley No. 155"],
  ["Wynyard", "town", "Big Quill No. 308"],
  ["Yellow Grass", "town", "Scott No. 98"],
  ["Zealandia", "town", "St. Andrews No. 287"],
  ["Abbey", "village", "Miry Creek No. 229"],
  ["Abernethy", "village", "Abernethy No. 186"],
  ["Albertville", "village", "Wise Creek No. 77"],
  ["Alida", "village", "Reciprocity No. 32"],
  ["Alvena", "village", "Fish Creek No. 402"],
  ["Annaheim", "village", "St. Peter No. 369"],
  ["Archerwill", "village", "Barrier Valley No. 397"],
  ["Arran", "village", "Livingston No. 331"],
  ["Atwater", "village", "Fertile Belt No. 183"],
  ["Avonlea", "village", "Elmsthorpe No. 100"],
  ["Aylesbury", "village", "Craik No. 222"],
  ["Aylsham", "village", "Nipawin No. 487"],
  ["Bangor", "village", "Fertile Belt No. 183"],
  ["Beatty", "village", "Flett's Springs No. 429"],
  ["Beechy", "village", "Victory No. 226"],
  ["Belle Plaine", "village", "Pense No. 160"],
  ["Bethune", "village", "Duffering No. 190"],
  ["Bjorkdale", "village", "Bjorkdale No. 426"],
  ["Bladworth", "village", "McCraney No. 282"],
  ["Borden", "village", "Great Bend No. 405"],
  ["Bracken", "village", "Lone Tree No. 18"],
  ["Bradwell", "village", "Blucher No. 343"],
  ["Briercrest", "village", "Redburn No. 130"],
  ["Brock", "village", "Kindersley No. 290"],
  ["Broderick", "village", "Rudy No. 284"],
  ["Brownlee", "village", "EyeBrow No. 193"],
  ["Buchanan", "village", "Buchanan No. 304"],
  ["Buena Vista", "village", "Lumsden No. 189"],
  ["Bulyea", "village", "McKillop No. 220"],
  ["Cadillac", "village", "Wise Creek No. 77"],
  ["Calder", "village", "Calder No. 241"],
  ["Canwood", "village", "Canwood No. 494"],
  ["Carievale", "village", "Argyle No. 1"],
  ["Caronport", "village", "Caron No. 162"],
  ["Ceylon", "village", "The Gap No. 39"],
  ["Chamberlain", "village", "Sarnia No. 221"],
  ["Chaplin", "village", "Chaplin No. 164"],
  ["Christopher Lake", "village", "Lakeland No. 521"],
  ["Clavet", "village", "Blucher No. 343"],
  ["Climax", "village", "Lone Tree No. 18"],
  ["Coderre", "village", "Rodgers No. 133"],
  ["Codette", "village", "Nipawin No. 487"],
  ["Coleville", "village", "Oakdale No. 320"],
  ["Conquest", "village", "Fertile Valley No. 285"],
  ["Consul", "village", "Reno No. 51"],
  ["Craven", "village", "Longlaketon No. 219"],
  ["Creelman", "village", "Fillmore No. 96"],
  ["Debden", "village", "Canwood No. 494"],
  ["Denholm", "village", "Mayfield No. 406"],
  ["Denzil", "village", "Eye Hill No. 382"],
  ["Dilke", "village", "Sarnia No. 221"],
  ["Dinsmore", "village", "Milden No. 286"],
  ["Disley", "village", "Lumsden No. 189"],
  ["Dodsland", "village", "Winslow no. 319"],
  ["Dorintosh", "village", "Meadow Lake No. 588"],
  ["Drake", "village", "Usborne No. 310"],
  ["Drinkwater", "village", "Redburn No. 130"],
  ["Dubuc", "village", "Grayson No. 184"],
  ["Duval", "village", "Last Mountain Valley No. 250"],
  ["Dysart", "village", "Lipton No. 217"],
  ["Earl Grey", "village", "Longlaketon No. 219"],
  ["Ebenezer", "village", "Orkney No. 244"],
  ["Edam", "village", "Turtle River No. 469"],
  ["Edenwold", "village", "Edenwold No. 158"],
  ["Elbow", "village", "Loreburn No. 254"],
  ["Elfros", "village", "Elfros No. 307"],
  ["Endeavour", "village", "Preeceville No. 334"],
  ["Englefeld", "village", "St. Peter No. 369"],
  ["Ernfold", "village", "Morse No. 165"],
  ["Eyebrow", "village", "Eyebrow No. 193"],
  ["Fairlight", "village", "Maryfield No. 91"],
  ["Fenwood", "village", "Stanley No. 215"],
  ["Fillmore", "village", "Fillmore No. 96"],
  ["Flaxcombe", "village", "Kindersley No. 290"],
  ["Forget", "village", "Tecumseh No. 65"],
  ["Fosston", "village", "Ponass Lake No. 367"],
  ["Fox Valley", "village", "Fox Valley No. 171"],
  ["Frobisher", "village", "Coalfields No. 4"],
  ["Frontier", "village", "Frontier No. 19"],
  ["Gainsborough", "village", "Argyle No. 1"],
  ["Gerald", "village", "Spy Hill No. 152"],
  ["Glaslyn", "village", "Parkdale No. 498"],
  ["Glen Ewen", "village", "Enniskillen No. 3"],
  ["Glenavon", "village", "Chester No. 127"],
  ["Glenside", "village", "Rudy No. 284"],
  ["Golden Prairie", "village", "Big Stick No. 141"],
  ["Goodeve", "village", "Stanley No. 215"],
  ["Goodsoil", "village", "Beaver River No. 622"],
  ["Goodwater", "village", "Lomond No. 37"],
  ["Grayson", "village", "Grayson No. 184"],
  ["Halbrite", "village", "Cymri No. 36"],
  ["Harris", "village", "Harris No. 316"],
  ["Hawarden", "village", "Loreburn No. 254"],
  ["Hazenmore", "village", "Pinto Creek No. 75"],
  ["Hazlet", "village", "Pittville No. 169"],
  ["Heward", "village", "Tecumseh No. 65"],
  ["Hodgeville", "village", "Lawtonia No. 135"],
  ["Holdfast", "village", "Sarnia No. 221"],
  ["Hubbard", "village", "Ituna Bon Accord No. 246"],
  ["Hyas", "village", "Clayton No. 333"],
  ["Invermay", "village", "Invermay No. 305"],
  ["Jansen", "village", "Wolverine No. 340"],
  ["Kelliher", "village", "Kellross No. 247"],
  ["Kenaston", "village", "McCraney No. 282"],
  ["Kendal", "village", "Montmartre No. 126"],
  ["Kennedy", "village", "Wawken No. 93"],
  ["Kenosee Lake", "village", "Wawken No. 93"],
  ["Killaly", "village", "McLeod No. 185"],
  ["Kincaid", "village", "Pinto Creek No. 75"],
  ["Kinley", "village", "Perdue No. 346"],
  ["Kisbey", "village", "Brock No. 64"],
  ["Krydor", "village", "Redberry No. 435"],
  ["Laird", "village", "Rosthern No. 403"],
  ["Lake Lenore", "village", "Lake Lenore No. 399"],
  ["Lancer", "village", "Miry Creek No. 229"],
  ["Landis", "village", "Reford No. 379"],
  ["Lang", "village", "Scott No. 98"],
  ["Leask", "village", "Leask No. 464"],
  ["Lebret", "village", "North Qu'Appelle No. 187"],
  ["Leoville", "village", "Spiritiwood No. 496"],
  ["Leross", "village", "Kellross No. 247"],
  ["Liberty", "village", "Big Arm No. 251"],
  ["Limerick", "village", "Stonehenge No. 73"],
  ["Lintlaw", "village", "Hazel Dell No. 335"],
  ["Lipton", "village", "Lipton No. 217"],
  ["Loon Lake", "village", "Loon Lake No. 561"],
  ["Loreburn", "village", "Loreburn No. 254"],
  ["Love", "village", "Torch River No. 488"],
  ["Lucky Lake", "village", "Canaan No. 225"],
  ["MacNutt", "village", "Churchbridge No. 211"],
  ["Macoun", "village", "Cymri No. 36"],
  ["Macrorie", "village", "Fertile Valley No. 285"],
  ["Major", "village", "Prairiedale No. 321"],
  ["Makwa", "village", "Loon Lake No. 561"],
  ["Mankota", "village", "Mankota No. 45"],
  ["Manor", "village", "Moose Mountain No. 63"],
  ["Marcelin", "village", "Blaine Lake No. 434"],
  ["Marengo", "village", "Milton No. 292"],
  ["Margo", "village", "Sasman No. 336"],
  ["Markinch", "village", "Cupar No. 218"],
  ["Marquis", "village", "Marquis No. 191"],
  ["Marsden", "village", "Manitou Lake No. 442"],
  ["Maryfield", "village", "Maryfield No. 91"],
  ["Maymont", "village", "Mayfield No. 406"],
  ["McLean", "village", "South Qu'Appelle No. 157"],
  ["McTaggart", "village", "Weyburn No. 67"],
  ["Meacham", "village", "Colonsay No. 342"],
  ["Meath Park", "village", "Garden River"],
  ["Medstead", "village", "Medstead No. 497"],
  ["Mendham", "village", "Happyland No. 231"],
  ["Meota", "village", "Meota No. 468"],
  ["Mervin", "village", "Mervin No. 499"],
  ["Middle Lake", "village", "Three Lakes No. 400"],
  ["Milden", "village", "Milden No. 286"],
  ["Minton", "village", "Surprise Valley No. 9"],
  ["Mistatim", "village", "Bjorkdale No. 426"],
  ["Montmartre", "village", "Montmartre No. 126"],
  ["Mortlach", "village", "Wheatlands No. 163"],
  ["Muenster", "village", "St. Peter No. 369"],
  ["Neilburg", "village", "Hillsdale No. 440"],
  ["Netherhill", "village", "Kindersley No. 290"],
  ["Neudorg", "village", "Mcleod No. 185"],
  ["Neville", "village", "Whiska Creek No. 106"],
  ["North Portal", "village", "Coalfields No. 4"],
  ["Odessa", "village", "Francis No. 127"],
  ["Osage", "village", "Fillmore No. 96"],
  ["Paddockwood", "village", "Paddockwood No. 520"],
  ["Pangman", "village", "Norton No. 69"],
  ["Paradise Hill", "village", "Frenchman Butte No. 501"],
  ["Parkside", "village", "Leask No. 464"],
  ["Paynton", "village", "Paynton No. 470"],
  ["Pelly", "village", "St. Philips No. 301"],
  ["Pennant", "village", "Riverside No. 168"],
  ["Perdue", "village", "Perdue No. 346"],
  ["Pierceland", "village", "Beaver River No. 622"],
  ["Pilger", "village", "Three Lakes No. 400"],
  ["Pleasantdale", "village", "Pleasantdale No. 398"],
  ["Plenty", "village", "Winslow No. 319"],
  ["Plunkett", "village", "Viscount no. 341"],
  ["Prud'homme", "village", "Bayne No. 371"],
  ["Punnichy", "village", "Mount Hope No. 279"],
  ["Quill Lake", "village", "Lakeside No. 338"],
  ["Quinton", "village", "Mount Hope No. 279"],
  ["Rama", "village", "Invermay No. 305"],
  ["Rhein", "village", "Wallace No. 243"],
  ["Richard", "village", "Douglas No. 436"],
  ["Richmound", "village", "Enterprise No. 142"],
  ["Ridgedale", "village", "Connaught No. 456"],
  ["Riverhurst", "village", "Maple Bush No. 224"],
  ["Roche Percee", "village", "Coalfields No. 4"],
  ["Ruddell", "village", "Mayfield No. 406"],
  ["Rush Lake", "village", "Excelsior No. 166"],
  ["Sceptre", "village", "Clinworth No. 230"],
  ["Sedley", "village", "Francis no. 127"],
  ["Semans", "village", "Mount Hope No. 279"],
  ["Senlac", "village", "Senlac No. 411"],
  ["Shamrock", "village", "Shamrock No. 134"],
  ["Sheho", "village", "Insinger No. 275"],
  ["Shell Lake", "village", "Spiritwood No. 496"],
  ["Silton", "village", "McKillop No. 220"],
  ["Simpson", "village", "Wood Creek No. 281"],
  ["Smeaton", "village", "Torch River No. 488"],
  ["Smiley", "village", "Prairiedale No. 321"],
  ["Spalding", "village", "Spalding No. 368"],
  ["Speers", "village", "Douglas No. 436"],
  ["Spy Hill", "village", "Spy Hill No. 152"],
  ["St. Benedict", "village", "Three Lakes No. 400"],
  ["St. Gregor", "village", "St. Peter No. 369"],
  ["St. Louis", "village", "St. Louis No. 431"],
  ["Stenen", "village", "Clayton No. 333"],
  ["Steward Valley", "village", "Saskatchewan Landing No. 167"],
  ["Stockholm", "village", "Fertile Belt No. 183"],
  ["Storthoaks", "village", "Storthoaks No. 31"],
  ["Strongfield", "village", "Loreburn No. 245"],
  ["Success", "village", "Riverside No. 168"],
  ["Tantallon", "village", "Spy Hill No. 152"],
  ["Tessier", "village", "Harris No. 316"],
  ["Theodore", "village", "Insinger No. 275"],
  ["Togo", "village", "Cote No. 271"],
  ["Tompkins", "village", "Gull Lake No. 139"],
  ["Torquay", "village", "Cambria No. 6"],
  ["Tramping Lake", "village", "Tramping Lake No. 380"],
  ["Tugaske", "village", "Huron No. 223"],
  ["Tuxford", "village", "Marquis No. 191"],
  ["Val Marie", "village", "Val Marie No. 17"],
  ["Valparaiso", "village", "Star City No. 428"],
  ["Vanguard", "village", "Whiska Creek No. 106"],
  ["Vanscoy", "village", "Vanscoy No. 345"],
  ["Vibank", "village", "Francis No. 127"],
  ["Viscount", "village", "Viscount No. 341"],
  ["Waldeck", "village", "Excelsior No. 166"],
  ["Waldron", "village", "Grayson No. 184"],
  ["Waseca", "village", "Eldon No. 471"],
  ["Webb", "village", "Webb No. 138"],
  ["Weekes", "village", "Porcupine No. 395"],
  ["Weirdale", "village", "Gargen River No. 490"],
  ["Weldon", "village", "Kinistino No. 459"],
  ["White Fox", "village", "Torch River No. 488"],
  ["Wilcox", "village", "Bratt's Lake No. 129"],
  ["Windthorst", "village", "Chester No. 125"],
  ["Wiseton", "village", "Milden No. 286"],
  ["Wood Mountain", "village", "Old Post No. 43"],
  ["Yarbo", "village", "Langenburg no. 181"],
  ["Young", "village", "Morris No. 312"],
  ["Zelma", "village", "Bayne No. 371"],
  ["Zenon Park", "village", "Arborfield No. 456"],
  ["Alice Beach", "resort village", "Sarnia No. 221"],
  ["Aquadeo", "resort village", "Meota No. 468"],
  ["Beaver Flat", "resort village", "Excelsior No. 166"],
  ["Big Shell", "resort village", "Spiritwood No. 496"],
  ["Bird's Point", "resort village", "Fertile Belt No. 183"],
  ["B-Say-Tah", "resort village", "North Qu'Appelle No. 187"],
  ["Candle Lake", "resort village", "Paddockwood No. 520"],
  ["Chitek Lake", "resort village", "Big River No. 555"],
  ["Chorney Beach", "resort village", "Foam Lake No. 276"],
  ["Cochin", "resort village", "Meota No. 468"],
  ["Coteau Beach", "resort village", "Coteau No. 255"],
  ["Echo Bay", "resort village", "Spiritwood No. 496"],
  ["Etters Beach", "resort village", "Big Arm No. 251"],
  ["Fort San", "resort village", "North Qu'Appelle No. 187"],
  ["Glen Harbour", "resort village", "Mckillop No. 220"],
  ["Grandview Beach", "resort village", "Sarnia No. 221"],
  ["Greig Lake", "resort village", "Meadow Lake No. 588"],
  ["Island View", "resort village", "McKillop No. 220"],
  ["Kannata Valley", "resort village", "Longlaketon No. 219"],
  ["Katepwa", "resort village", "Abernethy No. 186"],
  ["Kivimaa-Moonlight Bay", "resort village", "Mervin No. 499"],
  ["Leslie Beach", "resort village", "Foam Lake No. 276"],
  ["Lumsden", "resort village", "Lumsden No. 189"],
  ["Manitou Beach", "resort village", "Morris No. 312"],
  ["Melville Beach", "resort village", "Grayson No. 184"],
  ["Metinota", "resort village", "Meota No. 468"],
  ["Mistusinne", "resort village", "Maple Bush No. 224"],
  ["North Grove", "resort village", "Duffering No. 190"],
  ["Pebble Baye", "resort village", "Leask no. 464"],
  ["Pelican Pointe", "resort village", "McKillop No. 220"],
  ["Saskatchewan Beach", "resort village", "McKillop No. 220"],
  ["Shields", "resort village", "Dundurn No. 314"],
  ["South Lake", "resort village", "Marquis No. 191"],
  ["Sun Valley", "resort village", "Marquis No. 191"],
  ["Sunset Cove", "resort village", "McKillop No. 220"],
  ["Thode", "resort village", "Dundurn No. 314"],
  ["Tobin Lake", "resort village", "Moose Range No. 486"],
  ["Turtle View", "resort village", "Parkdale No. 498"],
  ["Wakaw Lake", "resort village", "Hoodoo No. 401"],
  ["Wee Too Beach", "resort village", "Sarnia No. 221"],
  ["West End", "resort village", "Fertile Belt No. 183"],
];

// ['name']
const ruralMunicipalities = [
  ["Aberdeen No. 373"],
  ["Abernethy No. 186"],
  ["Antelope Park No. 322"],
  ["Antler No. 61"],
  ["Arborfield No. 456"],
  ["Argyle No. 1"],
  ["Arlington No. 79"],
  ["Arm River No. 252"],
  ["Auvergne No. 76"],
  ["Baildon No. 131"],
  ["Barrier Valley No. 397"],
  ["Battle River No. 438"],
  ["Bayne No. 371"],
  ["Beaver River No. 622"],
  ["Bengough No. 40"],
  ["Benson No. 35"],
  ["Big Arm No. 251"],
  ["Big Quill No. 308"],
  ["Big River No. 555"],
  ["Big Stick No. 141"],
  ["Biggar No. 347"],
  ["Birch Hills No. 460"],
  ["Bjorkdale No. 426"],
  ["Blaine Lake No. 434"],
  ["Blucher No. 343"],
  ["Bone Creek No. 108"],
  ["Bratt's Lake No. 129"],
  ["Britannia No. 502"],
  ["Brock No. 64"],
  ["Brokenshell No. 68"],
  ["Browning No. 34"],
  ["Buchanan No. 304"],
  ["Buckland No. 491"],
  ["Buffalo No. 409"],
  ["Calder No. 241"],
  ["Caledonia No. 99"],
  ["Cambria No. 6"],
  ["Cana No. 214"],
  ["Canaan No. 225"],
  ["Canwood No. 494"],
  ["Carmichael No. 109"],
  ["Caron No. 162"],
  ["Chaplin No. 164"],
  ["Chester No. 125"],
  ["Chesterfield No. 261"],
  ["Churchbridge No. 211"],
  ["Clayton No. 333"],
  ["Clinworth No. 230"],
  ["Coalfields No. 4"],
  ["Colonsay No. 342"],
  ["Connaught No. 457"],
  ["Corman Park No. 344"],
  ["Cote No. 271"],
  ["Coteau No. 255"],
  ["Coulee No. 136"],
  ["Craik No. 222"],
  ["Cupar No. 218"],
  ["Cut Knife No. 439"],
  ["Cymri No. 36"],
  ["Deer Forks No. 232"],
  ["Doughlas No. 436"],
  ["Duck Lake No. 463"],
  ["Dufferin No. 190"],
  ["Dundurn No. 314"],
  ["Eagle Creek No. 376"],
  ["Edenwold No. 158"],
  ["Elcapo no. 154"],
  ["Eldon No. 471"],
  ["Elfros No. 307"],
  ["Elmsthorpe No. 100"],
  ["Emerald no. 277"],
  ["Enfield No. 194"],
  ["Enniskillen No. 3"],
  ["Enterprise No. 142"],
  ["Estevan No. 5"],
  ["Excel No. 71"],
  ["Excelsior No. 166"],
  ["Eye Hill No. 382"],
  ["Eyebrow No. 193"],
  ["Fertile Belt No. 183"],
  ["Fertile Valley No. 285"],
  ["Fillmore No. 96"],
  ["Fish Creek No. 402"],
  ["Flett's Springs No. 429"],
  ["Foam Lake No. 276"],
  ["Fox Valley No. 171"],
  ["Francis No. 127"],
  ["Frenchman Butte No. 501"],
  ["Frontier No. 19"],
  ["Garden River No. 490"],
  ["Garry No. 245"],
  ["Glen Bain No. 105"],
  ["Glen McPherson No. 46"],
  ["Glenside No. 377"],
  ["Golden West No. 95"],
  ["Good Lake No. 274"],
  ["Grandview No. 349"],
  ["Grant No. 372"],
  ["Grass Lake No. 381"],
  ["Grassy Creek No. 78"],
  ["Gravelbourg No. 104"],
  ["Grayson No. 184"],
  ["Great Bend No. 405"],
  ["Griffin No. 66"],
  ["Gull Lake No. 139"],
  ["Happy Valley No. 10"],
  ["Happyland No. 231"],
  ["Harris No. 316"],
  ["Hart Butte No. 11"],
  ["Hazel Dell No. 335"],
  ["Hazelwood No. 94"],
  ["Heart's Hill No. 352"],
  ["Hillsborough No. 132"],
  ["Hillsdale No. 440"],
  ["Hoodoo No. 401"],
  ["Hudson Bay No. 394"],
  ["Humboldt No. 370"],
  ["Huron No. 223"],
  ["Indian Head No. 156"],
  ["Insinger No. 275"],
  ["Invergordon No. 430"],
  ["Invermay No. 305"],
  ["Ituna Bon Accord No. 246"],
  ["Kellross No. 247"],
  ["Kelvington No. 366"],
  ["Key West No. 70"],
  ["Keys No. 303"],
  ["Kindersley No. 290"],
  ["King George No. 256"],
  ["Kingsley No. 124"],
  ["Kinistino No. 459"],
  ["Lac Pelletier No. 107"],
  ["Lacadena No. 228"],
  ["Laird No. 404"],
  ["Lajord No. 128"],
  ["Lake Alma No. 8"],
  ["Lake Johnston No. 102"],
  ["Lake Lenore No. 399"],
  ["Lake of the Rivers No. 72"],
  ["Lakeland No. 521"],
  ["Lakeside No. 338"],
  ["Langenburg No. 181"],
  ["Last Mountain Valley No. 250"],
  ["Laurier No. 38"],
  ["Lawtonia No. 135"],
  ["Leask No. 464"],
  ["Leroy No. 339"],
  ["Lipton No. 217"],
  ["Livingston No. 331"],
  ["Lomond No. 37"],
  ["Lone Tree No. 18"],
  ["Longlaketon No. 219"],
  ["Loon Lake No. 561"],
  ["Loreburn No. 254"],
  ["Lost River No. 313"],
  ["Lumsden No. 189"],
  ["Manitou Lake No. 442"],
  ["Mankota No. 45"],
  ["Maple Bush No. 224"],
  ["Maple Creek No. 111"],
  ["Mariposa No. 350"],
  ["Marquis No. 191"],
  ["Marriott No. 317"],
  ["Martin No. 122"],
  ["Maryfield No. 91"],
  ["Mayfield No. 406"],
  ["McCraney No. 282"],
  ["McKillop No. 220"],
  ["McLeod No. 185"],
  ["Meadow Lake No. 588"],
  ["Medstead No. 497"],
  ["Meeting Lake No. 466"],
  ["Meota No. 468"],
  ["Mervin No. 499"],
  ["Milden No. 286"],
  ["Milton No. 292"],
  ["Miry Creek No. 229"],
  ["Monet No. 257"],
  ["Montmartre No. 126"],
  ["Montrose No. 315"],
  ["Moose Creek No. 33"],
  ["Moose Jaw No. 161"],
  ["Moose Mountain No. 63"],
  ["Moose Range No. 486"],
  ["Moosomin No. 121"],
  ["Morris No. 312"],
  ["Morse No. 165"],
  ["Mount Hope No. 279"],
  ["Mount Pleasant No. 2"],
  ["Mountain View No. 318"],
  ["Newcombe No. 260"],
  ["Nipawin No. 487"],
  ["North Battleford No. 437"],
  ["North Qu'Appelle No. 187"],
  ["Norton No. 69"],
  ["Oakdale No. 320"],
  ["Old Post No. 43"],
  ["Orkney No. 244"],
  ["Paddockwood No. 520"],
  ["Parkdale No. 498"],
  ["Paynton No. 490"],
  ["Pense No. 160"],
  ["Perdue No. 346"],
  ["Piapot No. 110"],
  ["Pinto Creek No. 75"],
  ["Pittville No. 169"],
  ["Pleasant Valley No. 288"],
  ["Pleasantdale No. 398"],
  ["Ponass Lake No. 367"],
  ["Poplar Valley No. 12"],
  ["Porcupine No. 395"],
  ["Prairie Rose No. 309"],
  ["Prairiedale No. 321"],
  ["Preeceville No. 334"],
  ["Prince Albert No. 461"],
  ["Progress No. 351"],
  ["Reciprocity No. 32"],
  ["Redberry No. 435"],
  ["Redburn No. 130"],
  ["Reford No. 379"],
  ["Reno No. 51"],
  ["Riverside No. 168"],
  ["Rocanville No. 151"],
  ["Rodgers No. 133"],
  ["Rosedale No. 283"],
  ["Rosemount No. 378"],
  ["Rosthern No. 403"],
  ["Round Hill No. 467"],
  ["Round Valley No. 410"],
  ["Rudy No. 284"],
  ["Saltcoats No. 213"],
  ["Sarnia No. 221"],
  ["Saskatchewan Landing No. 167"],
  ["Sasman No. 336"],
  ["Scott No. 98"],
  ["Senlac No. 411"],
  ["Shamrock No. 134"],
  ["Shellbrook No. 493"],
  ["Sherwood No. 159"],
  ["Silverwood No. 123"],
  ["Sliding Hills No. 273"],
  ["Snipe Lake No. 259"],
  ["Souris Valley No. 7"],
  ["South Qu'Appelle No. 157"],
  ["Spalding No. 368"],
  ["Spritiwood No. 496"],
  ["Spy Hill No. 152"],
  ["St. Andrews No. 287"],
  ["St. Louis No. 431"],
  ["St. Peter No. 369"],
  ["St. Philips No. 301"],
  ["Stanley No. 215"],
  ["Star City No. 428"],
  ["Stonehenge No. 73"],
  ["Storthoaks No. 31"],
  ["Surprise Valley No. 9"],
  ["Sutton No. 103"],
  ["Swift Current No. 137"],
  ["Tecumseh No. 65"],
  ["Terrell No. 101"],
  ["The Gap No. 39"],
  ["Three Lakes No. 400"],
  ["Tisdale No. 427"],
  ["Torch River No. 488"],
  ["Touchwood No. 248"],
  ["Tramping Lake No. 380"],
  ["Tullymet No. 216"],
  ["Turtle River No. 469"],
  ["Usborne No. 310"],
  ["Val Marie No. 17"],
  ["Vanscoy No. 345"],
  ["Victory No. 226"],
  ["Viscount No. 341"],
  ["Wallace No. 243"],
  ["Walpole No. 92"],
  ["Waverley No. 44"],
  ["Wawken No. 93"],
  ["Webb No. 138"],
  ["Wellington No. 97"],
  ["Weyburn No. 67"],
  ["Wheatlands No. 163"],
  ["Whiska Creek No. 106"],
  ["White Valley No. 49"],
  ["Willner No. 253"],
  ["Willow Bunch No. 42"],
  ["Willow Creek No. 458"],
  ["Willowdale No. 153"],
  ["Wilton No. 472"],
  ["Winslow No. 319"],
  ["Wise Creek No. 77"],
  ["Wolseley No. 155"],
  ["Woverine No. 340"],
  ["Wood Creek No. 281"],
  ["Wood River No. 74"],
  ["Wreford No. 280"],
];

// ['name', 'status']
const northernMunicipalities = [
  ["Creighton", "northern town"],
  ["La Ronge", "northern town"],
  ["Air Ronge", "northern village"],
  ["Beauval", "northern village"],
  ["Buffalo Narrows", "northern village"],
  ["Cumberland House", "northern village"],
  ["Denare Beach", "northern village"],
  ["Green Lake", "northern village"],
  ["Île-à-la-Crosse", "northern village"],
  ["La Loche", "northern village"],
  ["Pelican Narrows", "northern village"],
  ["Pinehouse", "northern village"],
  ["Sandy Bay", "northern village"],
  ["Black Point", "northern hamlet"],
  ["Cole Bay", "northern hamlet"],
  ["Dore Lake", "northern hamlet"],
  ["Jans Bay", "northern hamlet"],
  ["Michel Village", "northern hamlet"],
  ["Patuanak", "northern hamlet"],
  ["St. George's Hill", "northern hamlet"],
  ["Stony Rapids", "northern hamlet"],
  ["Timber Bay", "northern hamlet"],
  ["Turnor Lake", "northern hamlet"],
  ["Weyakwin", "northern hamlet"],
];

const municipalities = [
  ...urbanMunicipalities,
  ...ruralMunicipalities,
  ...northernMunicipalities,
];

export { description, municipalities };
