const description =
  "Manitoba has a total of 137 municipalities that cover 21% of the province land mass. The 137 municipalities are classified into 37 urban municipalities, 98 rural municipalities and 2 local government districts. 37 urban municipalities consists of 10 cities, 25 towns and 2 villages.";

// ['name', 'status'],
const urbanMunicipalities = [
  ["Altona", "town"],
  ["Arborg", "town"],
  ["Beausejour", "town"],
  ["Brandon", "city"],
  ["Carberry", "town"],
  ["Carman", "town"],
  ["Churchill", "town"],
  ["Dauphin", "city"],
  ["Dunnottar", "village"],
  ["Flin Flon", "city"],
  ["Gillam", "town"],
  ["Grand Rapids", "town"],
  ["Lac du Bonnet", "town"],
  ["Leaf Rapds", "town"],
  ["Lynn Lake", "town"],
  ["Melita", "town"],
  ["Minnedosa", "town"],
  ["Morden", "city"],
  ["Morris", "town"],
  ["Neepawa", "town"],
  ["Niverville", "town"],
  ["The Pas", "town"],
  ["Portage la Prairie"],
  ["Powerview-Pine Falls"],
  ["Selkirk", "city"],
  ["Snow Lake", "town"],
  ["Ste. Anne", "town"],
  ["Steinbach", "city"],
  ["Stonewall", "town"],
  ["St-Pierre-Jolys", "village"],
  ["Swan River", "town"],
  ["Teulon", "town"],
  ["Thompson", "city"],
  ["Virden", "town"],
  ["Winkler", "city"],
  ["Winnipeg", "city"],
  ["Winnipeg Beach", "town"],
];

// ['name']
const ruralMunicipalities = [
  ["Alexander"],
  ["Alonsa"],
  ["Argyle"],
  ["Armstrong"],
  ["Bifrost-Riverton"],
  ["Boissevain-Morton"],
  ["Brenda-Waskada"],
  ["Brokenhead"],
  ["Cartier"],
  ["Cartwright-Roblin"],
  ["Clanwilliam-Erickson"],
  ["Coldwell"],
  ["Cornwallis"],
  ["Dauphin"],
  ["De Salaberry"],
  ["Deloraine-Winchester"],
  ["Dufferin"],
  ["East St. Paul"],
  ["Ellice-Archie"],
  ["Elton"],
  ["Emerson-Franklin"],
  ["Ethelbert"],
  ["Fisher"],
  ["Gilbert Plains"],
  ["Gimli"],
  ["Glenboro-South Cypress"],
  ["Glenella-Lansdowne"],
  ["Grahamdale"],
  ["Grandview"],
  ["Grassland"],
  ["Grey"],
  ["Hamiota"],
  ["Hanover"],
  ["Harrison Park"],
  ["Headingley"],
  ["Kelsey"],
  ["Killarney-Turtle Mountain"],
  ["La Broquerie"],
  ["Lac du Bonnet"],
  ["Lakeshore"],
  ["Lorne"],
  ["Louise"],
  ["Macdonald"],
  ["McCreary"],
  ["Minitonas-Bowsman"],
  ["Minto-Odanah"],
  ["Montcalm"],
  ["Morris"],
  ["Mossey River"],
  ["Mountain"],
  ["Norfolk-Treherne"],
  ["North Cypress-Langford"],
  ["North Norfold"],
  ["Oakland-Wawanesa"],
  ["Oakview"],
  ["Pembina"],
  ["Piney"],
  ["Pipestone"],
  ["Portage la Prairie"],
  ["Prairie Lakes"],
  ["Prairie View"],
  ["Reynolds"],
  ["Rhineland"],
  ["Riding Mountain West"],
  ["Ritchot"],
  ["Riverdale"],
  ["Roblin"],
  ["Rockwood"],
  ["Roland"],
  ["Rosedale"],
  ["Rossburn"],
  ["Russell-Binscarth"],
  ["Sifton"],
  ["Souris-Glenwood"],
  ["Springfield"],
  ["St.Andrews"],
  ["St.Clements"],
  ["St. François Xavier"],
  ["St. Laurent"],
  ["Stanley"],
  ["Ste. Anne"],
  ["St. Rose"],
  ["Stuartburn"],
  ["Swan Valley West"],
  ["Taché"],
  ["Thompson"],
  ["Two Borders"],
  ["Victoria"],
  ["Victoria Beach"],
  ["Wallace-Woodworth"],
  ["West Interlake"],
  ["West St. Paul"],
  ["WestLake-Gladstone"],
  ["Whitehead"],
  ["Whitemouth"],
  ["Woodlands"],
  ["Yellowhead"],
];

// ['name']
const localGovernmentDistricts = [["Mystery Lake"], ["Pinawa"]];

const municipalities = [
  ...urbanMunicipalities,
  ...ruralMunicipalities,
  ...localGovernmentDistricts,
];

export { description, municipalities };
