const description =
  "New Brunswick has a total of 77 municipalities that cover 10.9% of the province's land mass. New Brunswick municipalities are distributed as 20 towns, 21 villages, 17 rural communities, 8 cities and 1 regional municipality. ";

// ['name', 'status', 'regional service commission']
const municipalities = [
  ["Alnwich", "regional community", "Greater Miramichi"],
  ["Arcadia", "village", "Capital Region"],
  ["Bathurst", "city", "Chaleur"],
  ["Beaurivage", "town", "Kent"],
  ["Beausoleil", "regional community", "Kent"],
  ["Belle-Baie", "town", "Chaleur"],
  ["Belledune", "village", "Chaleur"],
  ["Bois-Joli", "village", "Restigouche"],
  ["Betternut Valley", "regional community", "Kings"],
  ["Campbellton", "city", "Restigouche"],
  ["Campobello Island", "regional community", "Southwest"],
  ["Cap-Acadie", "town", "Southeast"],
  ["Caraquet", "town", "Acadian Peninsual"],
  ["Carleton North", "town", "Western Valley"],
  ["Central York", "regional community", "Capital Region"],
  ["Champdoré", "town", "Kent"],
  ["Dieppe", "city", "Southeast"],
  ["Doaktown", "village", "Greater Miramichi"],
  ["Eastern Charlotte", "regional community", "Southwest"],
  ["Edmundston", "city", "Northwest"],
  ["Five Rivers", "village", "Kent"],
  ["Fredericton", "city", "Capital Region"],
  ["Fredericton Junction", "village", "Capital Region"],
  ["Fundy Albert", "village", "Southeast"],
  ["Fundy Shores", "regional community", "Southeast"],
  ["Fundy-St. Martins", "village", "Fundy"],
  ["Grand Bay-Westfield", "town", "Fundy"],
  ["Grand-Bouctouche", "town", "Kent"],
  ["Grand Falls", "town", "Northwest"],
  ["Grand Lake", "village", "Captial Region"],
  ["Grand Manan", "village", "Southwest"],
  ["Hampton", "town", "Fundy"],
  ["Hanwell", "regional community", "Capital Region"],
  ["Hartland", "town", "Western Valley"],
  ["Harvey", "regional community", "Capital Region"],
  ["Haut-Madawaska", "town", "Northwest"],
  ["Hautes-Terres", "town", "Acadian Peninsula"],
  ["Heron Bay", "town", "Restigouche"],
  ["Île-de-Lamèque", "town", "Acadian Peninsula"],
  ["Kedgwick", "regional community", "Restigouche"],
  ["Lakeland Ridges", "village", "Western Valley"],
  ["Maple Hills", "regional community", "Southeast"],
  ["McAdam", "village", "Southwest"],
  ["Memramcook", "village", "Southeast"],
  ["Miramichi", "city", "Greater Miramichi"],
  ["Miramichi River Valley", "regional community", "Greater Miramichi"],
  ["Moncton", "city", "Southeast"],
  ["Nackawic-Millville", "regional community", "Capital Region"],
  ["Nashwaak", "regional community", "Capital Region"],
  ["Neguac", "village", "Acadian Peninsula"],
  ["New Maryland", "village", "Capial Region"],
  ["Nouvelle-Arcadie", "village", "Kent"],
  ["Oromocto", "town", "Capital Region"],
  ["Quispamsis", "town", "Fundy"],
  ["Riverview", "town", "Southeast"],
  ["Rivière-du-Nord", "town", "Acadian Peninsula"],
  ["Rothesay", "town", "Fundy"],
  ["Saint Andrews", "town", "Southwest"],
  ["Saint John", "city", "Fundy"],
  ["Saint-Quentin", "town", "Northwest"],
  ["Salisbury", "town", "Southeast"],
  ["Shediac", "town", "Southeast"],
  ["Shippagan", "town", "Acadian Peninsula"],
  ["Southern Victoria", "village", "Western Valley"],
  ["St. Stephen", "town", "Southwest"],
  ["Strait Shores", "regional community", "Southeast"],
  ["Sunbury-York South", "regional community", "Capital Region"],
  ["Sussex", "town", "Kings"],
  ["Tantramar", "town", "Southeast"],
  ["Three Rivers", "village", "Southeast"],
  ["Tobique Valley", "village", "Western Valley"],
  ["Tracadie", "regional municipality", "Acadian Peninsula"],
  ["Tracy", "village", "Capital Region"],
  ["Upper Miramichi", "regional community", "Greater Miramichi"],
  ["Vallée-des-Rivières", "town", "Northwest"],
  ["Valley Waters", "village", "Kings"],
  ["Woodstock", "town", "Western Valley"],
];

export { description, municipalities };
