const description =
  "Quebec has 1,110 municipalities. Quebec has 227 cities/towns, 650 municipality, 145 parishes, 44 villages, 42 townships and 2 united townships ";

// ['name', 'status', 'regionalCountyMunicipality'],

const municipalities = [
  ["Abercorn", "village", "RCM Brome-Missisquoi"],
  ["Acton Vale", "town", "RCM Acton"],
  ["Adstock", "municipality", "RCM Les Appalaches"],
  ["Aguanish", "municipality", "RCM Mingaine"],
  ["Akulivik", "northern village", "Kativik TE"],
  ["Albanel", "municipality", "RCM Maria-Chapdelaine"],
  ["Albertville", "municipality", "RCM La Matapédia"],
  ["Alleyn-et-Cawood", "municipality", "RCM Pontiac"],
  ["Alma", "town", "RCM Lac-Saint-Jean-Est"],
  ["Amherst", "township", "RCM Les Laurentides"],
  ["Amos", "town", "RCM Abitibi"],
  ["Amqui", "town", "RCM La Matapédia"],
  ["Ange-Gardien", "municipality", "RCM Rouville"],
  ["Armagh", "municipality", "RCM Bellechasse"],
  ["Arundel", "town", "RCM Les Laurentides"],
  ["Ascot Corner", "municipality", "RCM Le Haut-Saint-François"],
  ["Aston-Jonction", "municipality", "RCM Nicolet-Yamaska"],
  ["Auclair", "municipality", "RCM Témiscouata"],
  ["Audet", "municipality", "RCM Le Granit"],
  ["Aumond", "town", "RCM La Vallée-de-la-Gatineau"],
  ["Aupaluk", "northern village", "Kativik TE"],
  ["Austin", "municipality", "RCM Memphrémagog"],
  ["Authier", "municipality", "RCM Abitibi-Ouest"],
  ["Authier-Nord", "municipality", "RCM Abitibi-Ouest"],
  ["Ayer's Cliff", "village", "RCM Memphrémagog"],
  ["Baie-Comeau", "town", "RCM Manicouagan"],
  ["Baie-D'Urfé", "town", "Urban agglomeration of Montreal"],
  ["Baie-des-Sables", "municipality", "RCM La Matanie"],
  ["Baie-du-Febvre", "municipality", "RCM Nicolet-Yamaska"],
  ["Baie-Johan-Beetz", "municipality", "RCM Minganie"],
  ["Baie-Saint-Paul", "town", "RCM Charlevoix"],
  ["Baie-Sainte-Catherine", "municipality", "RCM Charlevoix-Est"],
  ["Baie-Trinité", "village", "RCM Manicouagan"],
  ["Barkmere", "town", "RCM Les Laurentides"],
  ["Barnston-Ouest", "municipality", "RCM Coaticook"],
  ["Barraute", "municipality", "RCM Abitibi"],
  ["Batiscan", "municipality", "RCM Les Chenaux"],
  ["Beaconsfield", "town", "Urban agglomeration of Montreal"],
  ["Béarn", "municipality", "RCM Témiscamingue"],
  ["BeauceVille", "town", "RCM Beauce-Centre"],
  ["Beauharnois", "town", "RCM Beauharnois-Salaberry"],
  ["Beaulac-Garthby", "municipality", "RCM Les Appalaches"],
  ["Beaumont", "municipality", "RCM Bellechasse"],
  ["Beaupré", "town", "RCM La Côte-de-Beaupré"],
  ["Bécancour", "town", "RCM Bécancour"],
  ["Bedford", "township", "RCM Brome-Missisquoi"],
  ["Bedford", "town", "RCM Brome-Missisquoi"],
  ["Bégin", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Belcourt", "municipality", "RCM La Vallée-de-l'Or"],
  ["Belleterre", "town", "RCM Témiscamingue"],
  ["Beloeil", "town", "RCM La Vallée-du-Richelieu"],
  ["Berry", "municipality", "RCM Abitibi"],
  ["Berthier-sur-Mer", "municipality", "RCM Montmagny"],
  ["Berthierville", "town", "RCM D'Autray"],
  ["Béthanie", "municipality", "RCM Acton"],
  ["Biencourt", "municipality", "RCM Témiscouata"],
  ["Blainville", "town", "RCM Thérèse-De Blainville"],
  ["Blanc-Sablon", "municipality", "RCM Le Golfe-du-Saint-Laurent"],
  ["Blue Sea", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Boileau", "municipality", "RCM Papineau"],
  ["Boisbriand", "town", "RCM Thérèse-De Blainville"],
  ["Bois-des-Filion", "town", "RCM Thérèse-De Blainville"],
  ["Bois-Franc", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Boischatel", "municipality", "RCM La Côte-de-Beaupré"],
  ["Bolton-Est", "municipality", "RCM Memphrémagog"],
  ["Bolton-Ouest", "municipality", "RCM Brome-Missisquoi"],
  ["Bonaventure", "town", "RCM Bonaventure"],
  ["Bonne-Espérance", "municipality", "RCM Le Golfe-du-Saint-Laurent"],
  ["Bonsecours", "municipality", "RCM Le Val-Saint-François"],
  ["Boucherville", "town", "Urban agglomeration of Longueuil"],
  ["Bouchette", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Bowman", "municipality", "RCM Papineau"],
  ["Brébeuf", "municipality", "RCM Les Laurentides"],
  ["Brigham", "municipality", "RCM Brome-Missisquoi"],
  ["Bristol", "municipality", "RCM Pontiac"],
  ["Brome", "village", "RCM Brome-Missisquoi"],
  ["Bromont", "town", "RCM Brome-Missisquoi"],
  ["Brossard", "town", "Urban agglomeration of Longueuil"],
  ["Brownsburg-Chatham", "town", "RCM Argenteuil"],
  ["Bryson", "municipality", "RCM Pontiac"],
  ["Bury", "municipality", "RCM Le Haut-Saint-François"],
  ["Cacouna", "municipality", "RCM Rivière-du-Loup"],
  ["Calixa-Lavallée", "municipality", "RCM Marguerite-D'Youville"],
  ["Campbell's Bay", "municipality", "RCM Pontiac"],
  ["Candiac", "town", "RCM Roussillon"],
  ["Cantley", "municipality", "RCM Les Collines-de-l'Outaouais"],
  ["Cap-Chat", "town", "RCM La Haute-Gaspésie"],
  ["Cap-Saint-Ignace", "municipality", "RCM Montmagny"],
  ["Cap-Santé", "town", "RCM Portneuf"],
  ["Caplan", "municipality", "RCM Bonaventure"],
  ["Carignan", "town", "RCM La Vallée-du-Richelieu"],
  ["Carleton-sur-Mer", "town", "RCM Avignon"],
  ["Cascapédia--Saint-Jules", "municipality", "RCM Bonaventure"],
  ["Causapscal", "town", "RCM La Matapédia"],
  ["Cayamant", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Chambly", "town", "RCM La Vallée-du-Richelieu"],
  ["Chambord", "municipality", "RCM Le Domaine-du-Roy"],
  ["Champlain", "municipality", "RCM Les Chenaux"],
  ["Champneuf", "municipality", "RCM Abitibi"],
  ["Chandler", "town", "RCM Le Rocher-Percé"],
  ["Chapais", "town", "Jamésie TE"],
  ["Charette", "municipality", "RCM Maskinongé"],
  ["Charlemagne", "town", "RCM L'Assomption"],
  ["Chartierville", "municipality", "RCM Le Haut-Saint-François"],
  ["Châteauguay", "town", "RCM Roussillon"],
  ["Chazel", "municipality", "RCM Abitibi-Ouest"],
  ["Chelsea", "municipality", "RCM Les Collines-de-l'Outaouais"],
  ["Chénéville", "municipality", "RCM Papineau"],
  ["Chertsey", "municipality", "RCM Matawinie"],
  ["Chesterville", "municipality", "RCM Arthabaska"],
  ["Chibougamau", "town", "Jamésie TE"],
  ["Chichester", "township", "RCM Pontiac"],
  ["Chisasibi", "cree village", "Eeyou Istchee TE"],
  ["Chute-aux-Outardes", "municipality", "RCM Antoine-Labelle"],
  ["Chute-Saint-Philippe", "municipality", "RCM Antoine-Labelle"],
  ["Clarenceville", "municipality", "RCM Le Haut-Richelieu"],
  ["Clarendon", "municipality", "RCM Pontiac"],
  ["Clermont", "township", "RCM Abitibi-Ouest"],
  ["Clermont", "town", "RCM Charlevoix-Est"],
  ["Clerval", "municipality", "RCM Abitibi-Ouest"],
  ["Cleveland", "town", "RCM Le Val-Saint-François"],
  ["Cloridorme", "township", "RCM La Côte-de-Gaspé"],
  ["Coaticook", "town", "RCM Coaticook"],
  ["Colombier", "municipality", "RCM La Haute-Côte-Nord"],
  ["Compton", "municipality", "RCM Coaticook"],
  ["Contrecoeur", "town", "RCM Marguerite-D'Youville"],
  ["Cookshire-Eaton", "town", "RCM Le Haut-Saint-François"],
  [
    "Côte-Nord-du-Golfe-du-Saint-Laurent",
    "municipality",
    "RCM Le Golfe-du-Saint-Laurent",
  ],
  ["Côte-Saint-Luc", "town", "Urban agglomeration of Montreal"],
  ["Coteau-du-Lac", "town", "RCM Vaudreuil-Soulanges"],
  ["Courcelles-Saint-Évariste", "municipality", "RCM Beauce-Sartigan"],
  ["Cowansville", "town", "RCM Brome-Missisquoi"],
  ["Crabtree", "town", "RCM Joliette"],
  ["Danville", "town", "RCM Les Sources"],
  ["Daveluyville", "town", "RCM Arthabaska"],
  ["Dégelis", "town", "RCM Témiscouata"],
  ["Déléage", "municipality", "RCM La Vallée-de-la-Gateneau"],
  ["Delson", "town", "RCM Roussillon"],
  ["Denholm", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Desbiens", "town", "RCM Lac-Saint-Jean-Est"],
  ["Deschaillons-sur-Saint-Laurent", "municipality", "RCM Bécancour"],
  ["Deschambault-Grondines", "municipality", "RCM Portneuf"],
  ["Deux-Montagnes", "town", "RCM Deux-Montagnes"],
  ["Disraeli", "parish", "RCM Les Appalaches"],
  ["Disraeli", "town", "RCM Les Appalaches"],
  ["Dixville", "municipality", "RCM Coaticook"],
  ["Dolbeau-Mistassini", "town", "RCM Maria-Chapdelaine"],
  ["Dollard-des-Ormeaux", "town", "Urban agglomeration of Montreal"],
  ["Donnacona", "town", "RCM Portneuf"],
  ["Dorval", "town", "Urban agglomeration of Montreal"],
  ["Dosquet", "municipality", "RCM Lotbinière"],
  ["Drummondville", "town", "RCM Drummond"],
  ["Dudswell", "municipality", "RCM Le Haut-Saint-François"],
  ["Duhamel", "municipality", "RCM Papineau"],
  ["Duhamel-Ouest", "municipality", "RCM Témiscamingue"],
  ["Dundee", "township", "RCM Le Haut-Saint-Laurent"],
  ["Dunham", "town", "RCM Brome-Missisquoi"],
  ["Duparquet", "town", "RCM Abitibi-Ouest"],
  ["Dupuy", "municipality", "RCM Abitibi-Ouest"],
  ["Durham-Sud", "municipality", "RCM Drummond"],
  ["East Angus", "town", "RCM Le Haut-Saint-François"],
  ["East Broughton", "municipality", "RCM Les Appalaches"],
  ["East Farnham", "municipality", "RCM Brome-Missisquoi"],
  ["East Hereford", "municipality", "RCM Coaticook"],
  ["Eastman", "municipality", "RCM Memphrémagog"],
  ["Eastmain", "cree village", "Eeyou Istchee TE"],
  ["Eeyou Istchee Baie-James", "municipality", "Jamésie TE"],
  ["Egan-Sud", "municipality", "RCM La Vallée-de-la-Gateneau"],
  ["Elgin", "municipality", "RCM Le Haut-Saint-Laurent"],
  ["Entrelacs", "municipality", "RCM Matawinie"],
  ["Escuminac", "municipality", "RCM Avignon"],
  ["Esprit-Saint", "municipality", "RCM Rimouski-Neigette"],
  ["Estérel", "town", "RCM Les Pays-d'en-Haut"],
  ["Farnham", "town", "RCM Brome-Missisquoi"],
  ["Ferland-et-Boilleau", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Ferme-Neuve", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Fermont", "town", "RCM Caniapiscau"],
  ["Forestville", "town", "RCM La Haute-Côte-Nord"],
  ["Fort-Coulonge", "village", "RCM Pontiac"],
  ["Fortierville", "municipality", "RCM Bécancour"],
  ["Fossambault-sur-le-Lac", "town", "RCM La Jacques-Cartier"],
  ["Frampton", "municipality", "RCM La Nouvelle-Beauce"],
  ["Franklin", "municipality", "RCM Le Haut-Saint-Laurent"],
  ["Franquelin", "municipality", "RCM Manicouagan"],
  ["Frelighsburg", " municipality", "RCM Brome-Missisquoi"],
  ["Frontenac", "municipality", "RCM Le Granit"],
  ["Fugèreville", "municipality", "RCM Témiscamingue"],
  ["Gallichan", "municipality", "RCM Abitibi-Ouest"],
  ["Gaspé", "town", "RCM La Côte-de-gaspé"],
  ["Gatineau", "town", "Equivalent territory"],
  ["Girardville", "municipality", "RCM Maria-Chapdelaine"],
  ["Godbout", "village", "RCM Manicouagan"],
  ["Godmanchester", "township", "RCM Le Haut-Saint-Laurent"],
  ["Gore", "township", "RCM Argenteuil"],
  ["Gracefield", "town", "RCM La Vallée-de-la-Gatineau"],
  ["Granby", "town", "RCM La Haute-Yamaska"],
  ["Grand-Métis", "municipality", "RCM La Mitis"],
  ["Grand-Remous", "municipality", "RCM La Vallée-de-la-Gatieau"],
  ["Grand-Saint-Esprit", "municipality", "RCM Nicolet-Yamaska"],
  ["Grande-Rivière", "town", "RCM Le Rocher-Percé"],
  ["Grande-Vallée", "village", "RCM Mékinac"],
  ["Grenville", "village", "RCM Argenteuil"],
  ["Grenville-su-la-Rouge", "municipality", "RCM Argenteuil"],
  ["Gros-Mécatina", "municipality", "RCM Le Golfe-du-Saint-Laurent"],
  [
    "Grosse-Île",
    "municipality",
    "Urban agglomeration of Les Îles-de-la-Madeleine",
  ],
  ["Grosses-Roches", "municipality", "RCM La Matanie"],
  ["Guérin", "township", "RCM Témiscamingue"],
  ["Ham-Nord", "town", "RCM Arthabaska"],
  ["Ham-Sud", "municipality", "RCM Les Sources"],
  ["Hampden", "township", "RCM Le Haut-Saint-François"],
  ["Hampstead", "town", "Urban agglomeration of Montreal"],
  ["Harrington", "township", "RCM Argenteuil"],
  ["Hatley", "municipality", "RCM Memphrémagog"],
  ["Hatley", "township", "RCM Memphrémagog"],
  ["Havelock", "township", "RCM Le Haut-Saint-Laurent"],
  ["Havre-Saint-Pierre", "municipality", "RCM Minganie"],
  ["Hébertville", "municipality", "RCM Lac-Saint-Jean-Est"],
  ["Hemmingford", "township", "RCM Les Jardins-de-Napierville"],
  ["Hemmingford", "village", "RCM Les Jardins-de-Napierville"],
  ["Henryville", "municipality", "RCM Le Haut-Richelieu"],
  ["Hérouxville", "parish", "RCM Mékinac"],
  ["Hinchinbrooke", "municipality", "RCM Le Haut-Saint-Laurent"],
  ["Honfleur", "municipality", "RCM Bellechasse"],
  ["Hope", "township", "RCM Bonaventure"],
  ["Hope Town", "municipality", "RCM Bonaventure"],
  ["Howick", "municipality", "RCM Le Haut-Saint-Laurent"],
  ["Huberdeau", "municipality", "RCM Les Laurentides"],
  ["Hudson", "town", "RCM Vaudreuil-Soulanges"],
  ["Huntingdon", "town", "RCM Le Haut-Saint-Laurent"],
  ["Ivujivik", "northern village", "Kativik TE"],
  ["Inukjuak", "nv", "Kativik TE"],
  ["Inverness", "municipality", "RCM L'Érable"],
  ["Irlande", "municipality", "RCM Les Appalaches"],
  ["Ivry-sur-le-Lac", "municipality", "RCM Les Laurentides"],
  ["Joliette", "town", "RCM Joliette"],
  ["Kamouraska", "municipality", "RCM Kamouraska"],
  ["Kangiqsualujjuaq", "nv", "Kativik TE"],
  ["Kangiqsujuaq", "nv", "Kativik TE"],
  ["Kangirsuk", "nv", "Kativik TE"],
  ["Kawawachikamach", "naskapi village", "Kativik TE"],
  ["Kazabazua", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Kiamika", "municipality", "RCM Antoine-Labelle"],
  ["Kingsbury", "village", "RCM Le Val-Saint-François"],
  ["Kingsey Falls", "town", "RCM Arthabaska"],
  ["Kinnear's Mills", "municipality", "RCM Les Appalaches"],
  ["Kipawa", "municipality", "RCM Témiscamingue"],
  ["Kirkland", "town", "Urban agglomeration of Montreal"],
  ["Kuujjuaq", "nv", "Kativik TE"],
  ["Kuujjuarapik", "nv", "Kativik TE"],
  ["L'Ancienne-Lorette", "town", "Urban agglomeration of Quebec City"],
  ["L'Ange-Gardien", "municipality", "RCM Les Collines-de-l'Outaouais"],
  ["L'Ange-Gardien", "municipality", "RCM La Côte-de-Beaupré"],
  ["L'Anse-Saint-Jean", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["L'Ascension", "municipality", "RCM Antoine-Labelle"],
  ["L'Ascension-de-Notre-Seigneur", "parish", "RCM Lac-Saint-Jean-Est"],
  ["L'Ascension-de-Patapédia", "municipality", "RCM Avignon"],
  ["L'Assomption", "town", "RCM L'Assomption"],
  ["L'Avenir", "municipality", "RCM Drummond"],
  ["L'Épiphanie", "town", "RCM L'Assomption"],
  ["L'ÎIe-Cadieux", "town", "RCM Vaudreuil-Soulanges"],
  ["L'ÎIe-d'Anticosti", "municipality", "RCM Minganie"],
  ["L'ÎIe-Dorval", "town", "Urban agglomeration of Montreal"],
  ["L'ÎIe-du-Grand-Calumet", "municipality", "RCM Pontiac"],
  ["L'ÎIe-Perrot", "town", "RCM Vaudreuil-Soulanges"],
  ["L'Isle-aux-Allumettes", "municipality", "RCM Pontiac"],
  ["L'Isle-aux-Coudres", "municipality", "RCM Charlevoix"],
  ["L'Isle-Verte", "municipality", "RCM Rivière-du-Loup"],
  ["L'Islet", "municipality", "RCM L'Islet"],
  ["Lo Bostonnais", "municipality", "Urban agglomeration of La Tuque"],
  ["La Conception", "municipality", "RCM Les Laurentides"],
  ["La Corne", "municipality", "RCM Abitibi"],
  ["La Doré", "parish", "RCM Le Domaine-du-Roy"],
  ["La Durantaye", "parish", "RCM Bellechasse"],
  ["La Guadeloupe", "village", "RCM Beauce-Sartigan"],
  ["La Macaza", "municipality", "RCM Antoine-Labelle"],
  ["La Malbaie", "town", "RCM Charlevoix-Est"],
  ["La Martre", "municipality", "RCM La Haute-Gaspésie"],
  ["La Minerve", "municipality", "RCM Les Laurentides"],
  ["La Morandière-Rochebaucourt", "municipality", "RCM Abitibi"],
  ["La Motte", "municipality", "RCM Abitibi"],
  ["La Patrie", "municipality", "RCM Le Haut-Saint-François"],
  ["La Pêche", "municipality", "RCM Les Collines-de-I'Outaouais"],
  ["La Pocatière", "town", "RCM Kamouraska"],
  ["La Prairie", "town", "RCM Roussillon"],
  ["La Présentation", "municipality", "RCM Les Maskoutains"],
  ["La Rédemption", "parish", "RCM La Mitis"],
  ["La Reine", "municipality", "RCM Abitibi-Ouest"],
  ["La Sarre", "town", "RCM Abitibi-Ouest"],
  ["La Trinité-des-Monts", "parish", "RCM Rimouski-Neigette"],
  ["La Tuque", "town", "Urban agglomeration of La Tuque"],
  ["La Visitation-de-I'ÎIe-Dupas", "municipality", "RCM D'Autray"],
  ["La Visitation-de-Yamaska", "municipality", "RCM Les Laurentides"],
  ["Labelle", "municipality", "RCM Les Laurentides"],
  ["Labrecque", "municipality", "RCM Lac-Saint-Jean-Est"],
  ["Lac-au-Saumon", "municipality", "RCM La Matapédia"],
  ["Lac-aux-Sables", "parish", "RCM Mékinac"],
  ["Lac-Beauport", "municipality", "RCM La Jacques-Cartier"],
  ["Lac-Bouchette", "municipality", "RCM Le Domaine-du-Roy"],
  ["Lac-Brome", "town", "RCM Brome-Missisquoi"],
  ["Lac-Delage", "town", "RCM La Jacques-Cartier"],
  ["Lac-des-Aigles", "town", "RCM Témiscouata"],
  ["Lac-des-Écorces", "municipality", "RCM Antoine-Labelle"],
  ["Lac-des-Plages", "municipality", "RCM Papineau"],
  ["Lac-des-Seize-ÎIes", "municipality", "RCM Les Pays-d'en-Haut"],
  ["Lac-Drolet", "municipality", "RCM Le Granit"],
  ["Lac-du-Cerf", "municipality", "RCM Antoine-Labelle"],
  ["Lac-Édouard", "municipality", "Urban agglomeration of La Tuque"],
  ["Lac-Etchemin", "municipality", "RCM Les Etchemins"],
  ["Lac-Frontière", "municipality", "RCM Montmagny"],
  ["Lac-Mégantic", "town", "RCM Le Granit"],
  ["Lac-Poulin", "village", "RCM Beauce-Sartigan"],
  ["Lac-Saguay", "village", "RCM Antoine-Labelle"],
  ["Lac-Saint-Joseph", "town", "RCM La Jacques-Cartier"],
  ["Lac-Saint-Paul", "municipality", "RCM Antoine-Labelle"],
  ["Lac-Sainte-Marie", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Lac-Sergent", "town", "RCM Portneuf"],
  ["Lac-Simon", "municipality", "RCM Papineau"],
  ["Lac-Supérieur", "municipality", "RCM Les Laurentides"],
  ["Lac-Tremblant-Nord", "municipality", "RCM Les Laurentides"],
  ["Lachute", "town", "RCM Argenteuil"],
  ["Lacolle", "municipality", "RCM Le Haut-Richelieu"],
  ["Laforce", "municipality", "RCM Témiscamingue"],
  ["Lamarche", "municipality", "RCM Lac-Saint-Jean-Est"],
  ["Lambton", "municipality", "RCM Le Granit"],
  ["Landrienne", "township", "RCM Abitibi"],
  ["Lanoraie", "municipality", "RCM D'Autray"],
  ["Lantier", "municipality", "RCM Les Laurentides"],
  ["Larouche", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Latulipe-et-Gaboury", "united township", "RCM Témiscamingue"],
  ["Launay", "township", "RCM Abitibi"],
  ["Laurier-Station", "village", "RCM Lotbinière"],
  ["Laurierville", "municipality", "RCM L'Érable"],
  ["Laval", "town", "Equivalent territory"],
  ["Lavaltrie", "town", "RCM D'Autray"],
  ["Laverlochère-Angliers", "municipality", "RCM Témiscamingue"],
  ["Lawrenceville", "village", "RCM Le Val-Saint-François"],
  ["Lebel-sur-Quévillon", "town", "Jamésie TE"],
  ["Leclercville", "municipality", "RCM Lotbinière"],
  ["Lefebvre", "municipality", "RCM Drummond"],
  ["Lejeune", "municipality", "RCM Témiscouata"],
  ["Lemieux", "municipality", "RCM Bécancour"],
  ["Léry", "town", "RCM Roussillon"],
  ["Les Bergeronnes", "municipality", "RCM La Haute-Côte-Nord"],
  ["Les Cèdres", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Les Coteaux", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Les Éboulements", "municipality", "RCM Charlevoix"],
  ["Les Escoumins", "municipality", "RCM La Haute-Côte-Nord"],
  ["Les Hauteurs", "municipality", "RCM La Mitis"],
  [
    "Les ÎIes-de-la-Madeleine",
    "municipality",
    "Urban agglomeration of Les ÎIes-de-la-Madeleine",
  ],
  ["Les Méchins", "municipality", "RCM La Matanie"],
  ["Lévis", "town", "Equivalent territory"],
  ["Lingwick", "township", "RCM Le Haut-Saint-François"],
  ["Litchfield", "municipality", "RCM Pontiac"],
  ["Lochaber", "township", "RCM Papineau"],
  ["Lochaber-Partie-Ouest", "township", "RCM Papineau"],
  ["Longue-Pointe-de-Mingan", "municipality", "RCM Minganie"],
  ["Longue-Rive", "municipality", "RCM La Haute-Côte-Nord"],
  ["Longueuil", "town", "Urban agglomeration of Longueuil"],
  ["Lorraine", "town", "RCM Thérèse-De Blainville"],
  ["Lorrainville", "municipality", "RCM Témiscamingue"],
  ["Lotbinière", "municipality", "RCM Lotbinière"],
  ["Louiseville", "town", "RCM Maskinongé"],
  ["Low", "township", "RCM La Vallée-de-la-Gatineau"],
  ["Lyster", "municipality", "RCM L'Érable"],
  ["Macamic", "town", "RCM Abitibi-Ouest"],
  ["Maddington Falls", "municipality", "RCM Arthabaska"],
  ["Magog", "town", "RCM Memphrémagog"],
  ["Malartic", "town", "RCM La Vallée-de-l'Or"],
  ["Mandeville", "municipality", "RCM D'Autray"],
  ["Maniwaki", "town", "RCM La Vallée-de-la-Gatineau"],
  ["Manseau", "municipality", "RCM Bécancour"],
  ["Mansfield-et-Pontefract", "municipality", "RCM Pontiac"],
  ["Maria", "municipality", "RCM Avignon"],
  ["Maricourt", "municipality", "RCM Le Val-Saint-François"],
  ["Marieville", "town", "RCM Rouville"],
  ["Marsoui", "village", "RCM La Haute-Gaspésie"],
  ["Marston", "township", "RCM Le Granit"],
  ["Martinville", "municipality", "RCM Coaticook"],
  ["Mascouche", "town", "RCM Les Moulins"],
  ["Maskinongé", "municipality", "RCM Maskinongé"],
  ["Massueville", "village", "RCM Pierre-De Saurel"],
  ["Matagami", "town", "Jamésie TE"],
  ["Matane", "town", "RCM La Matanie"],
  ["Matapédia", "municipality", "RCM Avignon"],
  ["Mayo", "municipality", "RCM Papineau"],
  ["McMasterville", "town", "RCM La Vallée-du-Richelieu"],
  ["Melbourne", "township", "RCM Le Val-Saint-François"],
  ["Mercier", "town", "RCM Roussillon"],
  ["Messines", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Métabetchouan--Lac-à-la-Croix", "town", "RCM La Mitis"],
  ["Métis-sur-Mer", "town", "RCM La Mitis"],
  ["Milan", "municipality", "RCM Le Granit"],
  ["Mille-Isles", "municipality", "RCM Argenteuil"],
  ["Mirabel", "town", "Equivalent territory"],
  ["Mistissini", "cree village", "Eeyou Istchee TE"],
  ["Moffet", "municipality", "RCM Témiscamingue"],
  ["Mont-Blanc", "municipality", "RCM Les Laurentides"],
  ["Mont-Carmel", "municipality", "RCM Kamouraska"],
  ["Mont-Joli", "town", "RCM La Mitis"],
  ["Mont-Laurier", "town", "RCM Antoine-Labelle"],
  ["Mont-Royal", "town", "Urban agglomeration of Montreal"],
  ["Mont-Saint-Grégoire", "municipality", "RCM Le Haut-Richelieu"],
  ["Mont-Saint-Hilaire", "town", "RCM La Vallée-du-Richelieu"],
  ["Mont-Saint-Michel", "municipality", "RCM Antoine-Labelle"],
  ["Mont-Saint-Pierre", "village", "RCM La Haute-Gaspésie"],
  ["Mont-Tremblant", "town", "RCM Les Laurentides"],
  ["Montcalm", "municipality", "RCM Les Laurentides"],
  ["Montcerf-Lytton", "municipality", "RCM La Vallée-de-la-Gatineau"],
  ["Montebello", "municipality", "RCM Papineau"],
  ["Montmagny", "town", "RCM Montmagny"],
  ["Montpellier", "municipality", "RCM Papineau"],
  ["Montréal", "town", "Urban agglomeration of Montreal"],
  ["Montréal-Est", "town", "Urban agglomeration of Montreal"],
  ["Montréal-Ouest", "town", "Urban agglomeration of Montreal"],
  ["Morin-Heights", "municipality", "RCM Les Pays-d'en-Haut"],
  ["Mulgrave-et-Derry", "municipality", "RCM Papineau"],
  ["Murdochville", "town", "RCM La Côte-de-Gaspé"],
  ["Namur", "municipality", "RCM Papineau"],
  ["Nantes", "municipality", "RCM Le Granit"],
  ["Napierville", "municipality", "RCM Les Jardins-de-Napierville"],
  ["Natashquan", "municipality", "RCM Minganie"],
  ["Nédélec", "township", "RCM Témiscamingue"],
  ["Nemaska", "cree village", "Eeyou Istchee TE"],
  ["Neuville", "town", "RCM Portneuf"],
  ["New Carlisle", "municipality", "RCM Bonaventure"],
  ["New Richmond", "town", "RCM Bonaventure"],
  ["Newport", "municipality", "RCM Le Haut-Saint-François"],
  ["Nicolet", "town", "RCM Nicolet-Yamaska"],
  ["Nominingue", "municipality", "RCM Antoine-Labelle"],
  ["Normandin", "town", "RCM Maria-Chapdelaine"],
  ["Normétal", "municipality", "RCM Abitibi-Ouest"],
  ["North Hatley", "village", "RCM Memphrémagog"],
  ["Notre-Dame-Auxiliatrice-de-Buckland", "parish", "RCM Bellechasse"],
  ["Notre-Dame-de-Bonsecours", "municipality", "RCM Papineau"],
  ["Notre-Dame-de-Ham", "municipality", "RCM Arthabaska"],
  ["Notre-Dame-de-la-Merci", "municipality", "RCM Matawinie"],
  ["Notre-Dame-de-la-Paix", "municipality", "RCM Papineau"],
  ["Notre-Dame-de-la-Salette", "municipality", "RCM Papineau"],
  ["Notre-Dame-de-l'Île-Perrot", "town", "RCM Vaudreuil-Soulanges"],
  ["Notre-Dame-de-Lorette", "municipality", "RCM Maria-Chapdelaine"],
  ["Notre-Dame-de-Lourdes", "municipality", "RCM Joliette"],
  ["Notre-Dame-de-Lourdes", "parish", "RCM L'Érable"],
  ["Notre-Dame-de-Montauban", "municipality", "RCM Mékinac"],
  ["Notre-Dame-de-Pontmain", "municipality", "RCM Antoine-Labelle"],
  ["Notre-Dame-de-Stanbridge", "municipality", "RCM Brome-Missisquoi"],
  ["Notre-Dame-des-Anges", "parish", ""],
  ["Notre-Dame-des-Bois", "municipality", "RCM Le Granit"],
  ["Notre-Dame-des-Monts", "municipality", "RCM Charlevoix-Est"],
  ["Notre-Dame-des-Neiges", "municipality", "RCM Les Basques"],
  ["Notre-Dame-des-Pins", "parish", "RCM Beauce-Sartigan"],
  ["Notre-Dame-des-Prairies", "town", "RCM Joliette"],
  ["Notre-Dame-des-Sept-Douleurs", "parish", "RCM Rivière-du-Loup"],
  ["Notre-Dame-du-Bon-Conseil", "parish", "RCM Drummond"],
  ["Notre-Dame-du-Bon-Conseil", "village", "RCM Drummond"],
  ["Notre-Dame-du-Laus", "municipality", "RCM Antoine-Labelle"],
  ["Notre-Dame-du-Mont-Carmel", "parish", "RCM Les Chenaux"],
  ["Notre-Dame-du-Nord", "municipality", "RCM Témiscamingue"],
  ["Notre-Dame-du-Portage", "municipality", "RCM Rivière-du-Loup"],
  ["Notre-Dame-du-Rosaire", "municipality", "RCM Montmagny"],
  ["Notre-Dame-du-Sacré-Coeur-d'Issoudun", "parish", "RCM Lotbinière"],
  ["Nouvelle", "municipality", "RCM Avignon"],
  ["Noyan", "municipality", "RCM Le Haut-Richelieu"],
  ["Ogden", "municipality", "RCM Memphrémagog"],
  ["Oka", "municipality", "RCM Deux-Montagnes"],
  ["Orford", "township", "RCM Memphrémagog"],
  ["Ormstown", "municipality", "RCM Le Haut-Sait-Laurent"],
  ["Otter Lake", "municipality", "RCM Pontiac"],
  ["Otterburn Park", "town", "RCM La Vallée-du-Richelieu"],
  ["Oujé-Bougoumou", "cree village", "Eeyou Istchee TE"],
  ["Packington", "parish", "RCM Témiscouata"],
  ["Padoue", "municipality", "RCM La Mitis"],
  ["Palmarolle", "municipality", "RCM Abitibi-Ouest"],
  ["Papineauville", "municipality", "RCM Papineau"],
  ["Parisville", "parish", "RCM Bécancour"],
  ["Paspébiac", "town", "RCM Bonaventure"],
  ["Percé", "town", "RCM Le Rocher-Percé"],
  ["Péribonka", "municipality", "RCM Maria-Chapdelaine"],
  ["Petit-Saguenay", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Petite-Rivière-Saint-François", "municipality", "RCM Charlevoix"],
  ["Petite-Vallée", "municipality", "RCM La Côte-de-Gaspé"],
  ["Piedmont", "municipality", "RCM Les Pays-d'en-Haut"],
  ["Pierreville", "municipality", "RCM Nicolet-Yamaska"],
  ["Pike River", "municipality", "RCM Brome-Missisquoi"],
  ["Pincourt", "town", "RCM Vaudreuil-soulanges"],
  ["Piopolis", "municipality", "RCM Le Granit"],
  ["Plaisance", "municipality", "RCM Papineau"],
  ["Plessisville", "town", "RCM L'Érable"],
  ["Pohénégamook", "town", "RCM Témiscouata"],
  ["Pointe-à-la-Croix", "municipality", "RCM Avignon"],
  ["Pointe-aux-Outardes", "village", "RCM Manicouagan"],
  ["Pointe-Calumet", "municipality", "RCM Deux-Montagnes"],
  ["Pointe-Claire", "town", "Urban agglomeration of Montreal"],
  ["Pointe-des-Cascades", "village", "RCM Vaudreuil-Soulanges"],
  ["Pointe-Fortune", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Pointe-Lebel", "village", "RCM Manicouagan"],
  ["Pont-Rouge", "town", "RCM Portneuf"],
  ["Pontiac", "municipality", "RCM Les Collines-de-I'Outaouais"],
  ["Port-Cartier", "town", "RCM Sept-Rivières"],
  ["Port-Daniel--Gascons", "municipality", "RCM Le Rocher-Percé"],
  ["Portage-du-Fort", "village", "RCM Pontiac"],
  ["Portneuf", "town", "RCM Portneuf"],
  ["Portneuf-sur-Mer", "municipality", "RCM La Haute-Côte-Nord"],
  ["Potton", "township", "RCM Memphrémagog"],
  ["Poularies", "municipality", "RCM Abitibi-Ouest"],
  ["Preissac", "municipality", "RCM Abitibi"],
  ["Prévost", "town", "RCM La Rivière-du-Nord"],
  ["Price", "village", "RCM La Mitis"],
  ["Princeville", "town", "RCM L'Érable"],
  ["Puvirnituq", "northern village", "Kativik TE"],
  ["Quaqtaq", "northern village", "Kativik TE"],
  ["Quebec City", "town", "Urban agglomeration of Quebec City"],
  ["Racine", "municipality", "RCM Le Val-Saint-François"],
  ["Ragueneau", "parish", "RCM Manicouagan"],
  ["Rapide-Danseur", "municipality", "RCM Abitibi-Ouest"],
  ["Rapides-des-Jachims", "municipality", "RCM Pontiac"],
  ["Rawdon", "municipality", "RCM Matawinie"],
  ["Rémigny", "municipality", "RCM Témiscamingue"],
  ["Repentigny", "town", "RCM L'Assomption"],
  ["Richmond", "town", "RCM Le Val-Saint-François"],
  ["Rigaud", "town", "RCM Vaudreuil-Soulanges"],
  ["Rimouski", "town", "RCM Rimouski-Neigette"],
  ["Ripon", "municipality", "RCM Papineau"],
  ["Ristigouche-Sud-Est", "municipality", "RCM Avignon"],
  ["Rivière-à-Claude", "municipality", "RCM La Haute-Gaspésie"],
  ["Rivière-à-Pierre", "municipality", "RCM Portneuf"],
  ["Rivière-au-Tonnerre", "municipality", "RCM Minganie"],
  ["Rivière-Beaudette", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Rivière-Bleue", "municipality", "RCM Témiscouata"],
  ["Rivière-du-Loup", "town", "RCM Rivière-du-Loup"],
  ["Rivière-Éternité", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Rivière-Héva", "municipality", "RCM La Vallée-de-l'Or"],
  ["Rivière-Ouelle", "municipality", "RCM Kamouraska"],
  ["Rivière-Rouge", "town", "RCM Antoine-Labelle"],
  ["Rivière-Saint-Jean", "municipality", "RCM Minganie"],
  ["Roberval", "town", "RCM Le Domaine-du-Roy"],
  ["Roquemaure", "municipality", "RCM Abitibi-Ouest"],
  ["Rosemère", "town", "RCM Thérèse-De Blainville"],
  ["Rougemont", "municipality", "RCM Rouville"],
  ["Rouyn-Noranda", "town", "Equivalent territory"],
  ["Roxton", "township", "RCM Acton"],
  ["Roxton Falls", "village", "RCM Acton"],
  ["Roxton Pond", "municipality", "RCM La Haute-Yamaska"],
  ["Sacré-Coeur", "municipality", "RCM La Haute-Côte-Nord"],
  ["Sacré-Coeur-de-Jésus", "parish", "RCM Les Appalaches"],
  ["Saguenay", "town", "Equivalent territory"],
  ["Saint-Adalbert", "municipality", "RCM L'Islet"],
  ["Saint-Adelme", "parish", "RCM La Matanie"],
  ["Saint-Adelphe", "parish", "RCM Mékinac"],
  ["Saint-Adolphe-d'Howard", "municipality", "RCM Les Pays-d'en-Haut"],
  ["Saint-Adrien", "municipality", "RCM Les Sources"],
  ["Saint-Adrien-d'Irlande", "municipality", "RCM Les Appalaches"],
  ["Saint-Agapit", "municipality", "RCM Lotninière"],
  ["Saint-Aimé", "municipality", "RCM Pierre-De Saurel"],
  ["Saint-Aimé-des-Lacs", "municipality", "RCM Charlevoix-Est"],
  ["Saint-Aimé-du-Lac-des-Îles", "municipality", "RCM Antoine-Labelle"],
  ["Saint-Alban", "municipality", "RCM Portneuf"],
  ["Saint-Albert", "municipality", "RCM Arthabaska"],
  ["Saint-Alexandre", "municipality", "RCM Le Haut-Richelieu"],
  ["Saint-Alexandre-de-Kamouraska", "municipality", "RCM Kamouraska"],
  ["Saint-Alexandre-des-Lacs", "parish", "RCM La Matapédia"],
  ["Saint-Alexis", "municipality", "RCM Montcalm"],
  ["Saint-Alexis-de-Matapédia", "municipality", "RCM Avignon"],
  ["Saint-Alexis-des-Monts", "parish", "RCM Maskinongé"],
  ["Saint-Alfred", "municipality", "RCM Beauce-Centre"],
  ["Saint-Alphonse", "municipality", "RCM Bonaventure"],
  ["Saint-Alphonse-de-Granby", "municipality", "RCM La Haute-Yamaska"],
  ["Saint-Alphonse-Rodriguez", "municipality", "RCM Matawinie"],
  ["Saint-Amable", "town", "RCM Marguerite-D'Youville"],
  ["Saint-Ambroise", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Saint-Ambroise-de-Kildare", "municipality", "RCM Joliette"],
  ["Saint-Anaclet-de-Lessard", "parish", "RCM Rimouski-Neigette"],
  ["Saint-André-Avellin", "municipality", "RCM Papineau"],
  ["Saint-André-d'Argenteuil", "municipality", "RCM Argenteuil"],
  ["Saint-André-de-Kamouraska", "municipality", "RCM Kamouraska"],
  ["Saint-André-de-Restigouche", "municipality", "RCM Avignon"],
  ["Saint-André-du-Lac-Saint-Jean", "village", "RCM Le Domaine-du-Roy"],
  ["Saint-Anicet", "municipality", "RCM Le Haut-Saint-Laurent"],
  ["Saint-Anselme", "municipality", "RCM Bellechasse"],
  ["Saint-Antoine-de-l'Isle-aux-Grues", "parish", "RCM Montmagny"],
  ["Saint-Antoine-de-Tilly", "municipality", "RCM Lotbinière"],
  ["Saint-Antoine-sur-Richelieu", "municipality", "RCM La Vallée-du-Richelieu"],
  ["Saint-Antonin", "town", "RCM Rivière-du-Loup"],
  ["Saint-Apollinaire", "municipality", "RCM Lotbinière"],
  ["Saint-Armand", "municipality", "RCM Brome-Missisquoi"],
  ["Saint-Arsène", "parish", "RCM Rivière-du-Loup"],
  ["Saint-Athanase", "municipality", "RCM Témiscouata"],
  ["Saint-Aubert", "municipality", "RCM L'Islet"],
  ["Saint-Augustin", "municipality", "RCM Le Golfe-du-Saint-Laurent"],
  ["Saint-Augustin", "parish", "RCM Maria-Chapdelaine"],
  ["Saint-Augustin-de-Desmaures", "town", "Urban agglomeration of Quebec City"],
  ["Saint-Augustin-de-Woburn", "parish", "RCM Le Granit"],
  ["Saint-Barnabé", "parish", "RCM Maskinongé"],
  ["Saint-Barnabé-Sud", "municipality", "RCM Les Maskoutains"],
  ["Saint-Barthélemy", "parish", "RCM D'Autray"],
  ["Saint-Basile", "town", "RCM Portneuf"],
  ["Saint-Basile-le-Grand", "town", "RCM La Vallée-du-Richelieu"],
  ["Saint-Benjamin", "municipality", "RCM Les Etchemins"],
  ["Saint-Benoît-du-Lac", "municipality", "RCM Memphrémagog"],
  ["Saint-Benoît-Labre", "municipality", "RCM Beauce-Sartigan"],
  ["Saint-Bernard", "municipality", "RCM La Nouvelle-Beauce"],
  [
    "Saint-Bernard-de-Lacolle",
    "municipality",
    "RCM Les Jardins-de-Napierville",
  ],
  ["Saint-Bernard-de-Michaudville", "municipality", "RCM Les Maskoutains"],
  ["Saint-Blaise-sur-Richelieu", "municipality", "RCM Le Haut-Richelieu"],
  ["Saint-Bonaventure", "municipality", "RCM Drummond"],
  ["Saint-Boniface", "municipality", "RCM Maskinongé"],
  ["Saint-Bruno-de-Guigues", "municipality", "RCM Témiscamingue"],
  ["Saint-Bruno-de-Kamouraska", "municipality", "RCM Kamouraska"],
  ["Saint-Bruno-de-Montarville", "town", "Urban agglomeration of Longueuil"],
  ["Saint-Calixte", "municipality", "RCM Montcalm"],
  ["Saint-Camille", "township", "RCM Les Sources"],
  ["Saint-Camille-de-Lellis", "parish", "RCM Les Etchemins"],
  ["Saint-Casimir", "municipality", "RCM Portneuf"],
  ["Saint-Célestin", "municipality", "RCM Nicolet-Yamaska"],
  ["Saint-Célestin", "village", "RCM Nicolet-Yamaska"],
  ["Saint-Césaire", "town", "RCM Rouville"],
  ["Saint-Charles-Borromée", "town", "RCM Joliette"],
  ["Saint-Charles-de-Bellechasse", "municipality", "RCM Bellechasse"],
  ["Saint-Charles-de-Bourget", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Saint-Charles-Garnier", "parish", "RCM La Mitis"],
  ["Saint-Charles-sur-Richelieu", "municipality", "RCM La Vallée-du-Richelieu"],
  ["Saint-Christophe-d'Arthabaska", "parish", "RCM Arthabaska"],
  ["Saint-Chrysostome", "municipality", "RCM Le Haut-Saint-Laurent"],
  ["Saint-Claude", "municipality", "RCM Le Val-Saint-François"],
  ["Saint-Clément", "municipality", "RCM Les Basques"],
  ["Saint-Cléophas", "parish", "RCM La Matapédia"],
  ["Saint-Cléophas-de-Brandon", "municipality", "RCM D'Autray"],
  ["Saint-Clet", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Saint-Colomban", "town", "RCM La Rivière-du-Nord"],
  ["Saint-Côme", "municipality", "RCM Matawinie"],
  ["Saint-Côme--Linière", "municipality", "RCM Beauce-Sartigan"],
  ["Saint-Constant", "town", "RCM Roussillon"],
  ["Saint-Cuthbert", "municipality", "RCM D'Autray"],
  ["Saint-Cyprien", "municipality", "RCM Rivière-du-Loup"],
  ["Saint-Cyprien", "parish", "RCM Les Etchemins"],
  [
    "Saint-Cyprien-de-Napierville",
    "municipality",
    "RCM Les Jardins-de-Napierville",
  ],
  ["Saint-Cyrille-de-Lessard", "parish", "RCM L'Islet"],
  ["Saint-Cyrille-de-Wendover", "municipality", "RCM Drummond"],
  ["Saint-Damase", "municipality", "RCM Les Maskoutains"],
  ["Saint-Damase", "parish", "RCM La Matapédia"],
  ["Saint-Samase-de-L'Islet", "municipality", "RCM L'Islet"],
  ["Saint-Damien", "parish", "RCM Matawinie"],
  ["Saint-Damien-de-Buckland", "parish", "RCM Bellechasse"],
  ["Saint-David", "municipality", "RCM Pierre-De Saurel"],
  ["Saint-David-de-Falardeau", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Saint-Denis-De La Boutillerie", "municipality", "RCM Kamouraska"],
  ["Saint-Denis-de-Brompton", "municipality", "RCM Le Val-Saint-François"],
  ["Saint-Denis-sur-Richelieu", "municipality", "RCM La Vallée-du-Richelieu"],
  ["Saint-Didace", "parish", "RCM D'Autray"],
  ["Saint-Dominique", "municipality", "RCM Les Maskoutains"],
  ["Saint-Dominique-du-Rosaire", "municipality", "RCM Abitibi"],
  ["Saint-Donat", "municipality", "RCM Matawinie"],
  ["Saint-Donat", "parish", "RCM La Mitis"],
  ["Saint-Edmond-de-Grantham", "municipality", "RCM Drummond"],
  ["Saint-Edmond-les-Plaines", "municipality", "RCM Maria-Chapdelaine"],
  ["Saint-Édouard", "municipality", "RCM Les Jardins-de-Napierville"],
  ["Saint-Édouard-de-Fabre", "parish", "RCM Témiscamingue"],
  ["Saint-Édouard-de-Lotbinière", "parish", "RCM Lotbinière"],
  ["Saint-Édouard-de-Maskinongé", "municipality", "RCM Maskinongé"],
  ["Saint-Élie-de-Caxton", "municipality", "RCM Maskinnongé"],
  ["Saint-Éloi", "parish", "RCM Les Basques"],
  ["Saint-Elphège", "parish", "RCM Nicolet-Yamaska"],
  ["Saint-Elzéar", "municipality", "RCM Bonaventure"],
  ["Saint-Elzéar", "municipality", "RCM La Nouvelle-Beauce"],
  ["Saint-Elzéar-de-Témisouata", "municipality", "RCM Témiscouata"],
  ["Saint-Émile-de-Suffolk", "municipality", "RCM Papineau"],
  ["Saint-Éphrem-de-Beauce", "municipality", "RCM Beauce-Sartigan"],
  ["Saint-Épiphane", "municipality", "RCM Rivière-du-Loup"],
  ["Saint-Esprit", "municipality", "RCM Montcalm"],
  ["Saint-Étienne-de-Beauharnois", "municipality", "RCM Beauharnois-Salaberry"],
  ["Saint-Étienne-de-Bolton", "municipality", "RCM Memphrémagog"],
  ["Saint-Étienne-des-Grès", "parish", "RCM Maskinongé"],
  ["Saint-Eugène", "municipality", "RCM Drummond"],
  ["Saint-Eugène-d'Argentenay", "municipality", "RCM Maria-Chapdelaine"],
  ["Saint-Eugène-de-Guigues", "municipality", "RCM Témiscamingue"],
  ["Saint-Eugène-de-Ladrière", "parish", "RCM Rimouski-Neigette"],
  ["Saint-Eusèbe", "parish", "RCM Témiscouata"],
  ["Saint-Eustache", "town", "RCM Deux-Montagnes"],
  ["Saint-Fabien", "parish", "RCM Rimouski-Neigette"],
  ["Saint-Fabien-de-Panet", "parish", "RCM Montmagny"],
  ["Saint-Félicien", "town", "RCM Le Domaine-du-Roy"],
  ["Saint-Félix-de-Kingsey", "municipality", "RCM Drummond"],
  ["Saint-Félix-de-Valois", "municipality", "RCM Matawinie"],
  ["Saint-Félix-d'Otis", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Saint-Ferdinand", "municipality", "RCM L'Érable"],
  ["Saint-Ferréol-les-Neiges", "municipality", "RCM La Côte-de-Beaupré"],
  ["Saint-Flavien", "municipality", "RCM Lotbinière"],
  ["Saint-Fortunat", "municipality", "RCM Les Appalaches"],
  ["Saint-François-d'Assise", "municipality", "RCM Avignon"],
  ["Saint-François-de-la-Rivière-du-Sud", "municipality", "RCM Montmagny"],
  ["Saint-François-de-l'Île-d'Orléans", "municipality", "RCM L'Île-d'Orléans"],
  ["Saint-François-de-Sales", "municipality", "RCM Le Domaine-du-Roy"],
  ["Saint-François-du-Lac", "municipality", "RCM Nicolet-Yamaska"],
  [
    "Saint-François-Xavier-de-Brompton",
    "municipality",
    "RCM Le Val-Saint-François",
  ],
  ["Saint-Frédéric", "parish", "RCM Beauce-Centre"],
  ["Saint-Fulgence", "municipality", "RCM Le Fjord-du-Saguenay"],
  ["Saint-Gabriel", "town", "RCM D'Autray"],
  ["Saint-Gabriel-de-Brandon", "municipality", "RCM D'Autray"],
  ["Saint-Gabriel-de-Rimouski", "municipality", "RCM La Mitis"],
  ["Saint-Gabriel-de-Valcartier", "municipality", "RCM La Jacques-Cartier"],
  ["Saint-Gabriel-Lalemant", "municipality", "RCM Kamouraska"],
  ["Saint-Gédéon", "municipality", "RCM Lac-Saint-Jean-Est"],
  ["Saint-Gédéon-de-Beauce", "municipality", "RCM Beauce-Sartigan"],
  ["Saint-Georges", "town", "RCM Beauce-Sartigan"],
  ["Saint-Georges-de-Windsor", "municipality", "RCM Les Sources"],
  ["Saint-Gérard-Majella", "parish", "RCM Pierre-De Saurel"],
  ["Saint-Germain-de-Grantham", "municipality", "RCM Dummond"],
  ["Saint-Germain-de-Kamouraska", "municipality", "RCM Kamouraska"],
  ["Saint-Gervais", "municipality", "RCM Bellechasse"],
  ["Saint-Gilbert", "Parish", "RCM Portneuf"],
  ["Saint-Gilles", "municipality", "RCM Lotbinière"],
  ["Saint-Godefroi", "township", "RCM Bonaventure"],
  ["Saint-Guillaume", "municipality", "RCM Drummond"],
  ["Saint-Henri", "municipality", "RCM Bellechasse"],
  ["Saint-Henri-de-Taillon", "municipality", "RCM Lac-Saint-Jean-Est"],
  ["Saint-Herménégilde", "municipality", "RCM Coaticook"],
  ["Saint-Hilaire-de-Dorset", "parish", "RCM Beauce-Sartigan"],
  ["Saint-Hilarion", "paris", "RCM Charlevoix"],
  ["Saint-Hippolyte", "municipality", "RCM La Rivière-du-Nord"],
  ["Saint-Honoré", "town", "RCM Le Fjord-du-Saguenay"],
  ["Saint-Honoré-de-Shenley", "municipality", "RCM Beauce-Sartigan"],
  ["Saint-Hubert-de-Rivière-du-Loup", "municipality", "RCM Rivière-du-Loup"],
  ["Saint-Hugues", "municipality", "RCM Les Maskoutains"],
  ["Saint-Hyacinthe", "town", "RCM Les Maskoutains"],
  ["Saint-Ignace-de-Loyola", "municipality", "RCM D'Autra"],
  ["Saint-Ignace-de-Stanbridge", "municipality", "RCM Brome-Missisquoi"],
  ["Saint-Irénée", "municipality", "RCM Charlevoix-Est"],
  ["Saint-Isidore", "municipality", "RCM La Nouvelle-Beauce"],
  ["Saint-Isidore", "parish", "RCM Roussillon"],
  ["Saint-Isidore-de-Clifton", "municipality", "RCM Le Haut-Saint-François"],
  ["Saint-Jacques", "municipality", "RCM Montcaln"],
  ["Saint-Jacques-de-Leeds", "municipality", "RCM Les Appalaches"],
  ["Saint-Jacques-le-Majeur-de-Wolfestown", "parish", "RCM Les Appalaches"],
  ["Saint-Jacques-le-Mineur", "municipality", "RCM Les Jardins-de-Napierville"],
  ["Saint-Janvier-de-Joly", "municipality", "RCM Lotbinière"],
  ["Saint-Jean-Baptiste", "municipality", "RCM La Vallée-du-Richelieu"],
  ["Saint-Jean-de-Brébeuf", "municipality", "RCM Les Appalaches"],
  ["Saint-Jean-de-Cherbourg", "parish", "RCM La Matanie"],
  ["Saint-Jean-de-Dieu", "municipality", "RCM Les Basques"],
  ["Saint-Jean-de-la-Lande", "municipality", "RCM Témiscouata"],
  ["Saint-Jean-de-l'Île-d'Orléans", "municipality", "RCM L'Île-d'Orléans"],
  ["Saint-Jean-de-Matha", "municipality", "RCM Matawinie"],
  ["Saint-Jean-Port-Joli", "municipality", "RCM L'Islet"],
  ["Saint-Jean-sur-Richelieu", "town", "RCM Le Haut-Richelieu"],
  ["Saint-Jérôme", "town", "RCM La Rivière-du-Nord"],
  ["Saint-Joachim", "parish", "RCM La Côte-de-Beaupré"],
  ["Saint-Joachim-de-Shefford", "municipality", "RCM La Haute-Yamaska"],
  ["Saint-Joseph-de-Beauce", "town", "RCM Beauce-Centre"],
  ["Saint-Joseph-de-Coleraine", "municipality", "RCM Les Appalaches"],
  ["Saint-Joseph-de-Kamouraska", "parish", "RCM Kamouraska"],
  ["Saint-Joseph-de-Lepage", "parish", "RCM La Mitis"],
  ["Saint-Joseph-des-Érables", "municipality", "RCM Beauce-Centre"],
  ["Saint-Joseph-de-Sorel", "town", "RCM Pierre-De-Saurel"],
  ["Saint-Joseph-du-Lac", "municipality", "RCM Deux-Montagnes"],
  ["Saint-Jude", "municipality", "RCM Les Maskoutains"],
  ["Saint-Jules", "parish", "RCM Beauce-Centre"],
  ["Saint-Julien", "municipality", "RCM Les Appalaches"],
  ["Saint-Just-de-Bretenières", "municipality", "RCM Montmagny"],
  ["Saint-Juste-du-Lac", "municipality", "RCM Témiscouata"],
  ["Saint-Justin", "municipality", "RCM Maskinongé"],
  ["Saint-Lambert", "parish", "RCM Abitibi-Ouest"],
  ["Saint-Lambert", "town", "Urban agglomeration of Longueuil"],
  ["Saint-Lambert-de-Lauzon", "municipality", "RCM La Nouvelle-Beauce"],
  ["Saint-Laurent-de-l'Île-d'Orléans", "municipality", "RCM L'Île-d'Orléans"],
  ["Saint-Lazare", "town", "RCM Vaudreuil-Soulanges"],
  ["Saint-Lazare-de-Bellechasse", "municipality", "RCM Bellechasse"],
  ["Saint-Léandre", "parish", "RCM La Matanie"],
  ["Saint-Léonard-d'Aston", "municipality", "RCM Nicolet-Yamaska"],
  ["Saint-Léonard-de-Portneuf", "municipality", "RCM Portneuf"],
  ["Saint-Léon-de-Standon", "parish", "RCM Bellechasse"],
  ["Saint-Léon-le-Grand", "parish", "RCM La Matapédia"],
  ["Saint-Léon-le-Grand", "parish", "RCM Maskinongé"],
  ["Saint-Liboire", "municipality", "RCM Les Maskoutains"],
  ["Saint-Liguori", "municipality", "RCM Montcalm"],
  ["Saint-Lin--Laurentides", "town", "RCM Montcalm"],
  ["Saint-Louis", "municipality", "RCM Les Maskoutains"],
  ["Saint-Louis-de-Blandford", "municipality", "RCM Arthabaska"],
  ["Saint-Louis-de-Gonzague", "municipality", "RCM Les Etchemins"],
  ["Saint-Louis-de-Gonzague", "parish", "RCM Beauharnois-Salaberry"],
  [
    "Saint-Louis-de-Gonzague-du-Cap-Tourmente",
    "parish",
    "RCM La Côte-de-Beaupré",
  ],
  ["Saint-Louis-du-Ha! Ha!", "parish", "RCM Témiscouata"],
  ["Saint-Luc-de-Bellechasse", "municipality", "RCM Les Etchemins"],
  ["Saint-Luc-de-Vincennes", "municipality", "RCM Les Chenaux"],
  ["Saint-Lucien", "municipality", "RCM Dummond"],
  ["Saint-Ludger", "municipality", "RCM Le Granit"],
  ["Saint-Ludger-de-Milot", "municipality", "RCM Lac-Saint-Jean-Est"],
  ["Saint-Magloire", "municipality", "RCM Les Etchemins"],
  ["Saint-Majorique-de-Grantham", "parish", "RCM Drummond"],
  ["Saint-Malachie", "parish", "RCM Bellechasse"],
  ["Saint-Malo", "municipality", "RCM Coaticook"],
  ["Saint-Marc-de-Figuery", "parish", "RCM Abitibi"],
  ["Saint-Marc-des-Carrières", "town", "RCM Portneuf"],
  ["Saint-Marc-du-Lac-Long", "parish", "RCM Témiscouata"],
  ["Saint-Marcel", "municipality", "RCM L'Islet"],
  ["Saint-Marcel-de-Richelieu", "municipality", "RCM Les Maskoutains"],
  ["Saint-Marcellin", "parish", "RCM Rimouski-Neigette"],
  ["Saint-Marc-sur-Richelieu", "municipality", "RCM La Vallée-du-Richelieu"],
  ["Saint-Martin", "parish", "RCM Beauce-Sartigan"],
  ["Saint-Mathias-sur-Richelieu", "municipality", "RCM Rouville"],
  ["Saint-Mathieu", "municipality", "RCM Roussillon"],
  ["Saint-Mathieu-de-Beloeil", "municipality", "RCM La Vallée-du-Richelieu"],
  ["Saint-Mathieu-de-Rioux", "municipality", "RCM Les Basques"],
  ["Saint-Mathieu-d'Harricana", "municipality", "RCM Abitibi"],
  ["Saint-Mathieu-du-Parc", "municipality", "RCM Maskinongé"],
  ["Saint-Maurice", "parish", "RCM Les Chenaux"],
  ["Saint-Maxime-du-Mont-Louis", "municipality", "RCM La Haute-Gaspésie"],
  ["Saint-Médard", "municipality", "RCM Les Basques"],
  ["Saint-Michel", "municipality", "RCM Les Jardins-de-Napierville"],
  ["Saint-Michel-de-Bellechasse", "municipality", "RCM Bellechasse"],
  ["Saint-Michel-des-Saints", "municipality", "RCM Matawinie"],
  ["Saint-Michel-du-Squatec", "municipality", "Rcm Témiscouata"],
  ["Saint-Modeste", "municipality", "RCM Rivière-du-Loup"],
  ["Saint-Moïse", "parish", "RCM La Matapédia"],
  ["Saint-Narcisse", "parish", "RCM Les Chenaux"],
  ["Saint-Narcisse-de-Beaurivage", "parish", "RCM Lotbinière"],
  ["Saint-Narcisse-de-Rimouski", "parish", "RCM Rimouski-Neigette"],
  ["Saint-Nazaire", "municipality", "RCM Lac-Saint-Jean-Est"],
  ["Saint-Nazaire-d'Acton", "parish", "RCM Acton"],
  ["Saint-Nazaire-de-Dorchester", "parish", "RCM Bellechasse"],
  ["Saint-Nérée-de-Bellechasse", "municipality", "RCM Bellechasse"],
  ["Saint-Noël", "village", "RCM La Matapédia"],
  ["Saint-Norbert", "parish", "RCM D'Autray"],
  ["Saint-Norbert-d'Arthabaska", "municipality", "RCM Arthabaska"],
  ["Saint-Octave-de-Métis", "parish", "RCM La Mitis"],
  ["Saint-Odilon-de-Cranbourne", "municipality", "RCM Beauce-Centre"],
  ["Saint-Omer", "municipality", "RCM L'Islet"],
  ["Saint-Ours", "town", "RCM Pierre-De Saurel"],
  ["Saint-Pacôme", "municipality", "RCM Kamouraska"],
  ["Saint-Pamphile", "town", "RCM L'Islet"],
  ["Saint-Pascal", "town", "RCM Kamouraska"],
  ["Saint-Patrice-de-Beaurivage", "municipality", "RCM Lotbinière"],
  [
    "Saint-Patrice-de-Sherrington",
    "municipality",
    "RCM Les Jardins-de-Napierville",
  ],
  ["Saint-Paul", "municipality", "RCM Joliette"],
  ["Saint-Paul-d'Abbotsford", "municipality", "RCM Rouville"],
  ["Saint-Paul-de-la-Croix", "municipality", "RCM Rivière-du-Loup"],
  ["Saint-Paul-de-l'Île-aux-Noix", "municipality", "RCM Le Haut-Richelieu"],
  ["Saint-Paul-de-Montminy", "municipality", "RCM Montmagny"],
  ["Saint-Paulin", "municipality", "RCM Maskinongé"],
  ["Saint-Philémon", "parish", "RCM Bellechasse"],
  ["Saint-Philibert", "municipality", "RCM Beauce-Sartigan"],
  ["Saint-Philippe", "town", "RCM Roussillon"],
  ["Saint-Philippe-de-Néri", "parish", "RCM Kamouraska"],
  ["Saint-Pie", "town", "RCM Les Maskoutains"],
  ["Saint-Pie-de-Guire", "parish", "RCM Drummond"],
  ["Saint-Pierre", "village", "RCM Joliette"],
  ["Saint-Pierre-Baptiste", "parish", "RCM L'Érable"],
  ["Saint-Pierre-de-Broughton", "municipality", "RCM Les Appalaches"],
  ["Saint-Pierre-de-Lamy", "municipality", "RCM Témiscouata"],
  ["Saint-Pierre-de-la-Rivière-du-Sud", "parish", "RCM Montmagny"],
  ["Saint-Pierre-de-l'Île-d'Orléans", "municipality", "RCM L'Île-d'Orléans"],
  ["Saint-Pierre-les-Becquets", "municipality", "RCM Bécancour"],
  ["Saint-Placide", "municipality", "RCM Deux-Montagnes"],
  ["Saint-Polycarpe", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Saint-Prime", "municipality", "RCM Le Domaine-du-Roy"],
  ["Saint-Prosper", "municipality", "RCM Les Etchemins"],
  ["Saint-Prosper-de-Champlain", "municipality", "RCM Les Chenaux"],
  ["Saint-Raphaël", "municipality", "RCM Bellechasse"],
  ["Saint-Raymond", "town", "RCM Portneuf"],
  ["Saint-Rémi", "town", "RCM Les Jardins-de-Napierville"],
  ["Saint-Rémi-de-Tingwick", "municipality", "RCM Arthabaska"],
  ["Saint-René", "parish", "RCM Beauce-Sartigan"],
  ["Sait-René-de-Matane", "municipality", "RCM La Matanie"],
  ["Saint-Robert", "municipality", "RCM Pierre-De Saurel"],
  ["Saint-Robert-Bellarmin", "municipality", "RCM Le Granit"],
  ["Saint-Roch-de-I'Achigan", "municipality", "RCM Montcalm"],
  ["Saint-Roch-de-Mékinac", "parish", "RCM Mékinac"],
  ["Saint-Roch-de-Richelieu", "municipality", "RCM Pierre-De Saurel"],
  ["Saint-Roch-des-Aulnaies", "municipality", "RCM L'Islet"],
  ["Saint-Roch-Ouest", "municipality", "RCM Montcalm"],
  ["Saint-Romain", "municipality", "RCM Le Granit"],
  ["Saint-Rosaire", "parish", "RCM Arthabaska"],
  ["Saint-Samuel", "municipality", "RCM Arthabaska"],
  ["Saint-Sauveur", "town", "RCM Les Pays-d'en-Haut"],
  ["Saint-Sébastien", "municipality", "RCM Le Granit"],
  ["Saint-Sébastien", "municipality", "RCM Le Haut-Richelieu"],
  ["Saint-Sévère", "parish", "RCM Maskinongé"],
  ["Saint-Séverin", "parish", "RCM Mékinac"],
  ["Saint-Séverin", "parish", "RCM Beauce-Centre"],
  ["Saint-Siméon", "municipality", "RCM Charlevoix-Est"],
  ["Saint-Siméon", "parish", "RCM Bonaventure"],
  ["Saint-Simon", "municipality", "RCM Les Maskoutains"],
  ["Saint-Simon-de-Rimouski", "municipality", "RCM Les Basques"],
  ["Saint-Simon-les-Mines", "municipality", "RCM Beauce-Sartigan"],
  ["Saint-Sixte", "municipality", "RCM Papineau"],
  ["Saint-Stanislas", "municipality", "RCM Les Chenaux"],
  ["Saint-Stanislas", "municipality", "RCM Maria-Chapdelaine"],
  ["Saint-Stanislas-de-Kostka", "municipality", "RCM Beauharnois-Salaberry"],
  ["Saint-Sulpice", "parish", "RCM L'Assomption"],
  ["Saint-Sylvère", "municipality", "RCM Bécancour"],
  ["Saint-Sylvestre", "municipality", "RCM Lotninière"],
  ["Saint-Télesphore", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Saint-Tharcisius", "parish", "RCM La Matapédia"],
  ["Saint-Théodore-d'Acton", "municipality", "RCM Acton"],
  ["Saint-Théophile", "municipality", "RCM Beauce-Sartigan"],
  ["Saint-Thomas", "municipality", "RCM Joliette"],
  ["Saint-Thomas-Didyme", "municipality", "RCM Maria-Chapdelaine"],
  ["Saint-Thuribe", "parish", "RCM Portneuf"],
  ["Saint-Tite", "town", "RCM Mékinac"],
  ["Saint-Tite-des-Caps", "municipality", "RCM La Côte-de-Beaupré"],
  ["Saint-Ubalde", "municipality", "RCM Portneuf"],
  ["Saint-Ulric", "municipality", "RCM La Matanie"],
  ["Saint-Urbain", "parish", "RCM Charlevoix"],
  ["Saint-Urbain-Premier", "municipality", "RCM Beauharnois-Salaberry"],
  ["Saint-Valentin", "municipality", "RCM Le Haut-Richelieu"],
  ["Saint-Valère", "municipality", "RCM Arthabaska"],
  ["Saint-Valérien", "parish", "RCM Rimouski-Neigette"],
  ["Saint-Valérien-de-Milton", "municipality", "RCM Les Maskoutains"],
  ["Saint-Vallier", "municipality", "RCM Belechasse"],
  ["Saint-Venant-de-Paquette", "municipality", "RCM Coaticook"],
  ["Saint-Vianney", "municipality", "RCM La Matapédia"],
  ["Saint-Victor", "municipality", "RCM Beauce-Centre"],
  ["Saint-Wenceslas", "municipality", "RCM Nicolet-Yamaska"],
  ["Saint-Zacharie", "municipality", "RCM Les Etchemins"],
  ["Saint-Zénon", "municipality", "RCM Matawinie"],
  ["Saint-Zénon-du-Lac-Humqui", "parish", "RCM La Matapédia"],
  ["Saint-Zéphirin-de-Courval", "parish", "RCM Nicolet-Yamaska"],
  ["Saint-Zotique", "town", "RCM Vaudreuil-Soulanges"],
  ["Saint-Adèle", "town", "RCM Les Pays-d'en-Haut"],
  ["Sainte-Agathe-de-Latbinière", "municipality", "RCM Lotbinière"],
  ["Saint-Agathe-des-Monts", "town", "RCM Les Laurentides"],
  ["Sainte-Angèle-de-Mérici", "municipality", "RCM La Mitis"],
  ["Sainte-Angèle-de-Monnoir", "municipality", "RCM Rouville"],
  ["Sainte-Angèle-de-Prémont", "municipality", "RCM Maskinongé"],
  ["Sainte-Anne-de-Beaupré", "town", "RCM Le Côte-de-Beaupré"],
  ["Sainte-Anne-de-Bellevue", "town", "Urban agglomeration of Montreal"],
  ["Sainte-Anne-de-la-Pérade", "municipality", "RCM Les Chenaux"],
  ["Sainte-Anne-de-la-Rochelle", "municipality", "RCM Le Val-Saint-François"],
  ["Sainte-Anne-de-Sabrevois", "parish", "RCM Le Haut-Richelieu"],
  ["Sainte-Anne-des-Lacs", "parish", "RCM Les Pays-d'en-Haut"],
  ["Sainte-Anne-des-Monts", "town", "RCM La Haute-Gaspésie"],
  ["Sainte-Anne-de-Sorel", "municipality", "RCM Pierre-De Saurel"],
  ["Sainte-Anne-des-Plaines", "town", "RCM Thérèse-De Blainville"],
  ["Sainte-Anne-du-Lac", "municipality", "RCM Antoine-Labelle"],
  ["Sainte-Apolline-de-Patton", "parish", "RCM Montmagny"],
  ["Sainte-Aurélie", "municipality", "RCM Les Etchemins"],
  ["Sainte-Barbe", "municipality", "RCM Le Haute-Saint-Laurent"],
  ["Sainte-Béatrix", "municipality", "RCM Matawinie"],
  ["Sainte-Brigide-d'Iberville", "municipality", "RCM Le Haut-Richelieu"],
  ["Sainte-Brigitte-de-Laval", "town", "RCM La Jacques-Cartier"],
  ["Sainte-Brigitte-des-Saults", "parish", "Rcm Drummond"],
  ["Sainte-Catherine", "town", "RCM Roussillon"],
  ["Sainte-Catherine-de-Hatley", "municipality", "RCM Memphrémagog"],
  ["Sainte-Catherine-de-la-Jacques-Cartier", "town", "RCM La Jacques-Cartier"],
  ["Sainte-Cécile-de-Lévrard", "parish", "RCM Bécancour"],
  ["Sainte-Cécile-de-Milton", "municipality", "RCM La Haute-Yamaska"],
  ["Sainte-Cécile-de-Whitton", "municipality", "RCM Le Granit"],
  ["Sainte-Christine", "parish", "RCM Acton"],
  ["Sainte-Christine-d'Auvergne", "municipality", "RCM Portneuf"],
  ["Sainte-Claire", "municipality", "RCM Bellechasse"],
  ["Sainte-Clotilde", "municipality", "RCM Les Jardins-de-Napierville"],
  ["Sainte-Clotilde-de-Beauce", "municipality", "RCM Les Appalaches"],
  ["Sainte-Clotilde-de-Horton", "municipality", "RCM Arthabaska"],
  ["Sainte-Croix", "municipality", "RCM Lotbinière"],
  ["Sainte-Edwidge-de-Clifton", "township", "RCM Coaticook"],
  ["Sainte-Élisabeth", "municipality", "RCM D'Autray"],
  ["Sainte-Élizabeth-de-Warwick", "municipality", "RCM Arthabaska"],
  ["Sainte-Émélie-de-l'Énergie", "municipality", "RCM Matawinie"],
  ["Sainte-Eulalie", "municipality", "RCM Nicolet-Yamaska"],
  ["Sainte-Euphémie-sur-Rivière-du-Sud", "municipality", "RCM Montmagny"],
  ["Sainte-Famille-de-l'Île-d'Orléans", "municipality", "RCM L'Île-d'Orléans"],
  ["Sainte-Félicité", "municipality", "RCM La Matanie"],
  ["Sainte-Félicité", "municipality", "RCM L'Islet"],
  ["Sainte-Flavie", "parish", "RCM La Mitis"],
  ["Sainte-Florence", "municipality", "RCM La Matapédia"],
  ["Sainte-Françoise", "municipality", "RCM Bécancour"],
  ["Sainte-Françoise", "parish", "RCM Les Basques"],
  ["Sainte-Geneviève-de-Batiscan", "parish", "RCM Les Chenaux"],
  ["Sainte=Geneviève-de-Berthier", "municipality", "RCM D'Autray"],
  ["Sainte-Germaine-Boulé", "municipality", "RCM Abitibi-Ouest"],
  ["Sainte-Gertrude-Manneville", "municipality", "RCM Abitibi"],
  ["Sainte-Hedwidge", "municipality", "RCM Le Domaine-du-Roy"],
  ["Sainte-Hélène-de-Bagot", "municipality", "RCM Les Maskoutains"],
  ["Sainte-Hélène-de-Chester", "municipality", "RCM Arthabaska"],
  ["Sainte-Hélène-de-Kamouraska", "municipality", "RCM Kamouraska"],
  ["Sainte-Hélène-de-Mancebourg", "parish", "RCM Abitibi-Ouest"],
  ["Sainte-Hénédine", "parish", "RCM La Nouvelle-Beauce"],
  ["Sainte-Irène", "parish", "RCM La Matapédia"],
  ["Sainte-Jeanne-d'Arc", "village", "RCM Maria-Chapdelaine"],
  ["Sainte-Jeanne-d'Arc-de-la-Mitis", "municipality", "RCM La Mitis"],
  ["Sainte-Julie", "town", "RCM Marguerite-D'Youville"],
  ["Sainte-Julienne", "municipality", "RCM Montcalm"],
  ["Sainte-Justine", "municipality", "RCM Les Etchemins"],
  ["Sainte-Justine-de-Newton", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Sainte-Louise", "parish", "RCM L'Islet"],
  ["Sainte-Luce", "municipality", "RCM La Mitis"],
  ["Sainte-Lucie-de-Beauregard", "municipality", "RCM Montmagny"],
  ["Sainte-Lucie-des-Laurentides", "municipality", "RCM Les Laurentides"],
  ["Sainte-Madeleine", "village", "RCM Les Maskoutains"],
  [
    "Sainte-Madeleine-de-la-Rivière-Madeleine",
    "municipality",
    "RCM La Haute-Gaspésie",
  ],
  ["Sainte-Marcelline-de-Kildare", "municipality", "RCM Matawinie"],
  ["Sainte-Marguerite", "parish", "RCM La Nouvelle-Beauce"],
  ["Sainte-Marguerite-du-Lac-Masson", "town", "RCM Les Pays-d'en-Haut"],
  ["Sainte-Marguerite-Marie", "municipality", "RCM La Matapédia"],
  ["Sainte-Marie", "town", "RCM La Nouvelle-Beauce"],
  ["Sainte-Marie-de-Blandford", "municipality", "RCM Bécancour"],
  ["Sainte-Marie-Salomé", "municipality", "RCM Montcalm"],
  ["Sainte-Marthe", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Sainte-Marthe-sur-le-Lac", "town", "RCM Deux-Montagnes"],
  ["Sainte-Martine", "municipality", "RCM Beauharnois-Salaberry"],
  ["Sainte-Mélanie", "municipality", "RCM Joliette"],
  ["Sainte-Monique", "municipality", "RCM Lac-Saint-Jean-Est"],
  ["Sainte-Monique", "municipality", "RCM Nicolet-Yamaska"],
  ["Sainte-Paule", "municipality", "RCM La Matanie"],
  ["Sainte-Perpétue", "municipality", "RCM L'Islet"],
  ["Sainte-Perpétue", "parish", "RCM Nicolet-Yamaska"],
  ["Sainte-Pétronille", "village", "RCM L'Île-d'Orléans"],
  ["Sainte-Praxède", "parish", "RCM Les Appalaches"],
  ["Sainte-Rita", "municipality", "RCM Les Basques"],
  ["Sainte-Rose-de-Watford", "municipality", "RCM Les Etchemins"],
  ["Sainte-Rose-du-Nord", "parish", "RCM Le Fjord-du-Saguenay"],
  ["Sainte-Sabine", "municipality", "RCM Brome-Missisquoi"],
  ["Sainte-Sabine", "parish", "RCM Les Etchemins"],
  ["Sainte-Séraphine", "parish", "RCM Arthabaska"],
  ["Sainte-Sophie", "municipality", "RCM La Rivière-du-Nord"],
  ["Sainte-Sophie-de-Lévrard", "parish", "RCM Bécancour"],
  ["Sainte-Sophie-d'Halifax", "municipality", "RCM L'Érable"],
  ["Sainte-Thécle", "municipality", "RCM Mékinac"],
  ["Sainte-Thérèse", "town", "RCM Thérèse-De Blainville"],
  ["Sainte-Thérèse-de-Gaspé", "municipality", "RCM Le Rocher-Percé"],
  [
    "Sainte-Thérèse-de-la-Gatineau",
    "municipality",
    "RCM La Vallée-de-la-Gatineau",
  ],
  ["Sainte-Ursule", "municipality", "RCM Maskinongé"],
  ["Sainte-Victoire-de-Sorel", "municipality", "RCM Pierre-De Saurel"],
  ["Saints-Anges", "municipality", "RCM La Nouvelle-Beauce"],
  ["Saints-Martyrs-Canadiens", "parish", "RCM Arthabaska"],
  ["Salaberry-de-Valleyfield", "town", "RCM Beauharnois-Salaberry"],
  ["Salluit", "nv", "Kativik TE"],
  ["Sayabec", "municipality", "RCM La Matapédia"],
  ["Schefferville", "town", "RCM Caniapiscau"],
  ["Scotstown", "town", "RCM Le Haut-Saint-François"],
  ["Scott", "municipality", "RCM La Nouvelle-Beauce"],
  ["Senneterre", "parish", "RCM La Vallée-de-I'OR"],
  ["Senneterre", "town", "RCM La Vallée-de-I'OR"],
  ["Senneville", "village", "Urban agglomeration of Montreal"],
  ["Sept-Îles", "town", "RCM Sept-Rivières"],
  ["Shannon", "town", "RCM La Jacques-Cartier"],
  ["Shawinigan", "town", "Equivalent territory"],
  ["Shawville", "municipality", "RCM Pontiac"],
  ["Sheenboro", "municipality", "RCM Pontiac"],
  ["Shefford", "township", "RCM La Haute-Yamaska"],
  ["Sherbrooke", "town", "Equivalent territory"],
  ["Shigawake", "municipality", "RCM Bonaventure"],
  ["Sorel-Tracy", "town", "RCM Pierre-De Saurel"],
  ["Stanbridge East", "municipality", "RCM Brome-Missisquoi"],
  ["Stanbridge Station", "municipality", "RCM Brome-Missisquoi"],
  ["Stanstead", "township", "RCM Memphrémagog"],
  ["Stanstead", "town", "RCM Memphrémagog"],
  ["Stanstead-Est", "municipality", "RCM Coaticook"],
  ["Stoke", "municipality", "RCM Le Val-Saint-François"],
  ["Stoneham-et-Tewkesbury", "united township", "RCM La Jacques-Cartier"],
  ["Stornoway", "municipality", "RCM Le Granit"],
  ["Startford", "township", "RCM Le Granit"],
  ["Stukely-Sud", "village", "RCM Memphrémagog"],
  ["Sutton", "town", "RCM Brome-Missisquoi"],
  ["Tadoussac", "village", "RCM La Haute-Côte-Nord"],
  ["Taschereau", "municipality", "RCM Abitibi-Ouest"],
  ["Tasiujaq", "nv", "Kativik TE"],
  ["Témiscaming", "town", "RCM Témiscamingue"],
  ["Témiscouata-sur-le-Lac", "town", "RCM Témiscouata"],
  ["Terrasse-Vaudreuil", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Terrebonne", "town", "RCM Les Moulins"],
  ["Thetford Mines", "town", "RCM Les Appalaches"],
  ["Thorne", "municipality", "RCM Pontiac"],
  ["Thurso", "town", "RCM Paineau"],
  ["Tingwick", "municipality", "RCM Arthabaska"],
  ["Tourville", "municipality", "RCM L'Islet"],
  ["Trécesson", "township", "RCM Abitibi"],
  ["Très-Saint-Rédempteur", "municipality", "RCM Vaudreuil-Soulanges"],
  ["Très-Saint-Sacrement", "municipality", "RCM Le Haut-Saint-Laurent"],
  ["Tring-Jonction", "village", "RCM Beauce-Centre"],
  ["Trois-Pistoles", "town", "RCM Les Basques"],
  ["Trois-Rives", "municipality", "RCM Mékinac"],
  ["Trois-Rivières", "town", "Equivalent territory"],
  ["Ulverton", "municipality", "RCM Le Val-Saint-François"],
  ["Umiujaq", "nv", "Kativik TE"],
  ["Upton", "municipality", "RCM Acton"],
  ["Val-Alain", "municipality", "RCM Lotbinière"],
  ["Val-Brillant", "municipality", "RCM La Matapédia"],
  ["Val-d'Or", "town", "RCM La Vallée-de-I'Or"],
  ["Val-David", "village", "RCM Les Laurentides"],
  ["Val-des-Bois", "municipality", "RCM Papineau"],
  ["Val-des-Lacs", "municipality", "RCM Les Laurentides"],
  ["Val-des-Monts", "municipality", "RCM Les Collines-de-I'Outaouais"],
  ["Val-des-Sources", "town", "RCM Les Sources"],
  ["Val-Joli", "municipality", "RCM Le Val-Saint-François"],
  ["Val-Morin", "municipality", "RCM Les Laurentides"],
  ["Val-Racine", "municipality", "RCM Le Granit"],
  ["Val-Saint-Gilles", "municipality", "RCM Abitibi-Ouest"],
  ["Valcourt", "township", "RCM Le Val-Saint-François"],
  ["Valcourt", "town", "RCM Le Val-Saint-François"],
  ["Vallée-Jonction", "municipality", "RCM La Nouvelle-Beauce"],
  ["Varennes", "town", "RCM Marguerite-D'Youville"],
  ["Vaudreuil-Dorion", "town", "RCM Vaudreuil-Soulanges"],
  ["Vaudreuil-sur-le-Lac", "village", "RCM Vaudreuil-Soulanges"],
  ["Venise-en-Québec", "municipality", "RCM Le Haut-Richelieu"],
  ["Verchères", "municipality", "RCM Marguerite-D'Youville"],
  ["Victoriaville", "town", "RCM Arthabaska"],
  ["Ville-Marie", "town", "RCM Témiscamingue"],
  ["Villeroy", "municipality", "RCM L'Érable"],
  ["Waltham", "municipality", "RCM Pontiac"],
  ["Warden", "village", "RCM La Haute-Yamaska"],
  ["Warwick", "town", "RCM Arthabaska"],
  ["Waskaganish", "cree village", "Eeyou Istchee TE"],
  ["Waswanipi", "cree village", "Eeyou Istchee TE"],
  ["Waterloo", "town", "RCM La Haute-Yamaska"],
  ["Waterville", "town", "RCM Coaticook"],
  ["Weedon", "municipality", "RCM Le Haut-Saint-François"],
  ["Wemindji", "cree village", "Eeyou Istchee TE"],
  ["Wentworth", "township", "RCM Argenteuil"],
  ["Wentworth-Nord", "municipality", "RCM Les Pays-d'en-Haut"],
  ["Westbury", "township", "RCM Le Haut-Saint-François"],
  ["Westmount", "town", "Urban agglomeration of Montreal"],
  ["Whapmagoostui", "cree village", "Eeyou Istchee TE"],
  ["Wickham", "municipality", "RCM Drummond"],
  ["Windsor", "town", "RCM Le Val-Saint-François"],
  ["Wotton", "municipality", "RCM Les Sources"],
  ["Yamachiche", "municipality", "RCM Maskinongé"],
  ["Yamaska", "municipality", "RCM Pierre-De Saurel"],
];

export { description, municipalities };
