const description =
  "British Columbia has a total of 161 municipalities that cover 11% of province's land mass. 161 municipalities consist of 50 district municipality, 52 cities, 41 villages, 14 towns, 1 island municipality, 2 mountain resort municipality and 1 resort municipality.";

// ['name', 'status', 'regional district']
const municipalities = [
  ["Abbotsford", "city", "Fraser Valley"],
  ["Armstrong", "city", "North Okanagan"],
  ["Burnaby", "city", "Metro Vancouver"],
  ["Campbell River", "city", "Strathcona"],
  ["Castlegar", "city", "Central Kootenay"],
  ["Chilliwack", "city", "Fraser Valley"],
  ["Colwood", "city", "Capital"],
  ["Coquitlam", "city", "Metro Vancouver"],
  ["Courtenay", "city", "Comox Valley"],
  ["Cranbrook", "city", "East Kootenay"],
  ["Dawson Creek", "city", "Peace River"],
  ["Delta", "city", "Metro Vancouver"],
  ["Duncan", "city", "Cowichan Valley"],
  ["Enderby", "city", "North Okanagan"],
  ["Fernie", "city", "East Kootenay"],
  ["Fort St. John", "city", "Peace River"],
  ["Grand Forks", "city", "Kootenay Boundary"],
  ["Greenwood", "city", "Kootenay"],
  ["Kamloops", "city", "Thompson-Nicola"],
  ["Kelowna", "city", "Central Okanagan"],
  ["Kimberley", "city", "East Kootenay"],
  ["Langford", "city", "Capital"],
  ["Langley", "city", "Metro Vancouver"],
  ["Maple Ridge", "city", "Metro Vancouver"],
  ["Merritt", "city", "Thompson-Nicola"],
  ["Mission", "city", "Fraser Valley"],
  ["Nanaimo", "city", "Nanaimo"],
  ["Nelson", "city", "Central Kootenay"],
  ["New Westminster", "city", "Metro Vancouver"],
  ["North Vancouver", "city", "Metro Vancouver"],
  ["Parksville", "city", "Nanaimo"],
  ["Penticton", "city", "Okanagan-Similkameen"],
  ["Pitt Meadows", "city", "Metro Vancouver"],
  ["Port Alberni", "city", "Alberni-Clayoquot"],
  ["Port Coquitlam", "city", "Metro Vancouver"],
  ["Port Moody", "city", "Metro Vancouver"],
  ["Powell River", "city", "qathet"],
  ["Prince George", "city", "Fraser-Fort George"],
  ["Prince Rupert", "city", "North Coast"],
  ["Quesnel", "city", "Cariboo"],
  ["Revelstoke", "city", "Columbia Shuswap"],
  ["Richmond", "city", "Metro Vancouver"],
  ["Rossland", "city", "Kootenay Boundary"],
  ["Salmon Arm", "city", "Columbia Shuswap"],
  ["Surrey", "city", "Metro Vancouver"],
  ["Terrace", "city", "Kitimat-Stikine"],
  ["Trail", "city", "Kootenay Boundary"],
  ["Vancouver", "city", "Metro Vancouver"],
  ["Vernon", "city", "North Okanagan"],
  ["Victoria", "city", "Capital"],
  ["West Kelowna", "city", "Central Okanagan"],
  ["White Rock", "city", "Metro Vancouver"],
  ["Williams Lake", "city", "Cariboo"],
  ["100 Mile House", "district municipality", "Cariboo"],
  ["Barriere", "district municipality", "Thompson-Nicola"],
  ["Central Saanich", "district municipality", "Capital"],
  ["Chetwynd", "district municipality", "Peace River"],
  ["Clearwater", "district municipality", "Thompson-Nicola"],
  ["Coldstream", "district municipality", "North Okanagan"],
  ["Elkford", "district municipality", "East Kootenay"],
  ["Esquimalt", "district municipality", "Capital"],
  ["Fort St. James", "district municipality", "Bulkley-Nechako"],
  ["Highlands", "district municipality", "capital"],
  ["Hope", "district municipality", "Fraser Valley"],
  ["Houston", "district municipality", "Bulkley-Nechako"],
  ["Hudson's Hope", "district municipality", "Peace River"],
  ["Invermere", "district municipality", "East Kootenay"],
  ["Kent", "district municipality", "Fraser Valley"],
  ["Kitimat", "district municipality", "Kitimat-Stikine"],
  ["Lake Country", "district municipality", "Central Okanagan"],
  ["Langley", "district municipality", "Metro Vancouver"],
  ["Lantzville", "district municipality", "Nanaimo"],
  ["Lillooet", "district municipality", "Squamish Lillooet"],
  ["Logan Lake", "district municipality", "Thompson-Nicola"],
  ["Machenzie", "district municipality", "Fraser-Fort George"],
  ["Metchosin", "district municipality", "Capital"],
  ["New Hazelton", "district municipality", "Kitimat-Stikine"],
  ["North Cowichan", "district municipality", "Cowichan Valley"],
  ["North Saanich", "district municipality", "Capital"],
  ["North Vancouver", "district municipality", "Metro Vancouver"],
  ["Northern Rockies", "district municipality", "Northern Rockies"],
  ["Oak Bay", "district municipality", "Capital"],
  ["Peachland", "district municipality", "Central Okanagan"],
  ["Port Edward", "district municipality", "North Coast"],
  ["Port Hardy", "district municipality", "Mount Waddington"],
  ["Saanich", "district municipality", "Capital"],
  ["Sechelt", "district municipality", "Sunshine Coast"],
  ["Sicamous", "district municipality", "Columbia Shuswap"],
  ["Sooke", "district municipality", "Capital"],
  ["Spallumcheen", "district municipality", "North Okanagan"],
  ["Sparwood", "district municipality", "East Kootenay"],
  ["Squamish", "district municipality", "Squamish-Lillooet"],
  ["Steward", "district municipality", "Kitimat-Stikine"],
  ["Summerland", "district municipality", "Okanagan-Similkameen"],
  ["Taylor", "district municipality", "Peace River"],
  ["Tofino", "district municipality", "Alberni-Clayoquot"],
  ["Tumbler Ridge", "district municipality", "Peace River"],
  ["Ucluelet", "district municipality", "Alberni-Clayoquot"],
  ["Vanderhoof", "district municipality", "Bulkley-Nechako"],
  ["Wells", "district municipality", "Cariboo"],
  ["West Vancouver", "district municipality", "Metro Vancouver"],
  [
    "shíshálh Nation",
    "first nations government district",
    "qathet and Sunshine Coast",
  ],
  ["Bowen Island", "island municipality", "Metro Vancouver"],
  ["Sun Peaks Mountain", "mountain resort municipality", "Thompson-Nicola"],
  ["Whistler", "resort municipality", "Squamish-Lillooet"],
  ["Comox", "town", "Comox Valley"],
  ["Creston", "town", "Central Kootenay"],
  ["Gibsons", "town", "Sunshine Coast"],
  ["Golden", "town", "Columbia Shuswap"],
  ["Ladysmith", "town", "Cowichan Valley"],
  ["Lake Cowichan", "town", "Cowichan Valley"],
  ["Oliver", "town", "Okanagan-Similkameen"],
  ["Osoyoos", "town", "Okanagan-Similkameen"],
  ["Port McNeill", "town", "Mount Waddington"],
  ["Princeton", "town", "Okanagan-Similkameen"],
  ["Qualicum Beach", "town", "Nanaimo"],
  ["Sidney", "town", "Captial"],
  ["Smithers", "town", "Bulkley-Nechako"],
  ["View Royal", "town", "Capital"],
  ["Alert Bay", "village", "Mount Waddington"],
  ["Anmore", "village", "Metro Vancouver"],
  ["Ashcroft", "village", "Thompson-Nicola"],
  ["Belcarra", "village", "Metro-Vancouver"],
  ["Burns Lake", "village", "Bulkley-Nechako"],
  ["Cache Creek", "village", "Thompson Nicola"],
  ["Canal Flats", "village", "East Kootenay"],
  ["Chase", "village", "Thompson-Nicola"],
  ["Clinton", "village", "Thompson-Nicola"],
  ["Cumberland", "village", "Comox Valley"],
  ["Daajing Giids", "village", "North Coast"],
  ["Fraser Lake", "village", "Bulkley-Nechako"],
  ["Fruitvale", "village", "Kootenay Boundary"],
  ["Gold River", "village", "Strathcona"],
  ["Granisle", "village", "Bulkley-Nechako"],
  ["Harrison Hot Springs", "village", "Fraser Valley"],
  ["Hazelton", "village", "Kitimat-Stikine"],
  ["Kaslo", "village", "Central Kootenay"],
  ["Keremeos", "village", "Okanagan-Similkameen"],
  ["Lions Bay", "village", "Metro Vancouver"],
  ["Lumby", "village", "North Okanagan"],
  ["Lytton", "village", "Thompson-Nicola"],
  ["Masset", "village", "North Coast"],
  ["McBride", "village", "Fraser-Fort George"],
  ["Midway", "village", "Kootenay Boundary"],
  ["Montrose", "village", "Kootenay Boundary"],
  ["Nakusp", "village", "Central Kootenay"],
  ["New Denver", "village", "Central Kootenay"],
  ["Pemberton", "village", "Squamish-Lillooet"],
  ["Port Alice", "village", "Mount Waddington"],
  ["Port Clements", "village", "North Coast"],
  ["Pouce Coupe", "village", "Peace River"],
  ["Radium Hot Springs", "village", "East Kootenay"],
  ["Salmo", "village", "Central Kootenay"],
  ["Sayward", "village", "Strathcona"],
  ["Silverton", "village", "Central Kootenay"],
  ["Slocan", "village", "Central Kootenay"],
  ["Tahsis", "village", "Strathcona"],
  ["Telkwa", "village", "Bulkley-Nechako"],
  ["Valemount", "village", "Fraser-Fort George"],
  ["Warfield", "village", "Kootenay Boundary"],
  ["Zeballos", "village", "Strathcona"],
];

export { description, municipalities };
